// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/v2/client/api_keys"
	"github.com/aclerici38/pocket-id-go-client/v2/client/application_configuration"
	"github.com/aclerici38/pocket-id-go-client/v2/client/application_images"
	"github.com/aclerici38/pocket-id-go-client/v2/client/audit_logs"
	"github.com/aclerici38/pocket-id-go-client/v2/client/custom_claims"
	"github.com/aclerici38/pocket-id-go-client/v2/client/health"
	"github.com/aclerici38/pocket-id-go-client/v2/client/o_id_c"
	"github.com/aclerici38/pocket-id-go-client/v2/client/s_c_i_m"
	"github.com/aclerici38/pocket-id-go-client/v2/client/user_groups"
	"github.com/aclerici38/pocket-id-go-client/v2/client/users"
	"github.com/aclerici38/pocket-id-go-client/v2/client/version"
	"github.com/aclerici38/pocket-id-go-client/v2/client/well_known"
)

// Default pocket ID API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new pocket ID API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *PocketIDAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new pocket ID API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *PocketIDAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new pocket ID API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *PocketIDAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(PocketIDAPI)
	cli.Transport = transport
	cli.APIKeys = api_keys.New(transport, formats)
	cli.ApplicationConfiguration = application_configuration.New(transport, formats)
	cli.ApplicationImages = application_images.New(transport, formats)
	cli.AuditLogs = audit_logs.New(transport, formats)
	cli.CustomClaims = custom_claims.New(transport, formats)
	cli.Health = health.New(transport, formats)
	cli.OIDc = o_id_c.New(transport, formats)
	cli.Scim = s_c_i_m.New(transport, formats)
	cli.UserGroups = user_groups.New(transport, formats)
	cli.Users = users.New(transport, formats)
	cli.Version = version.New(transport, formats)
	cli.WellKnown = well_known.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// PocketIDAPI is a client for pocket ID API
type PocketIDAPI struct {
	APIKeys api_keys.ClientService

	ApplicationConfiguration application_configuration.ClientService

	ApplicationImages application_images.ClientService

	AuditLogs audit_logs.ClientService

	CustomClaims custom_claims.ClientService

	Health health.ClientService

	OIDc o_id_c.ClientService

	Scim s_c_i_m.ClientService

	UserGroups user_groups.ClientService

	Users users.ClientService

	Version version.ClientService

	WellKnown well_known.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *PocketIDAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.APIKeys.SetTransport(transport)
	c.ApplicationConfiguration.SetTransport(transport)
	c.ApplicationImages.SetTransport(transport)
	c.AuditLogs.SetTransport(transport)
	c.CustomClaims.SetTransport(transport)
	c.Health.SetTransport(transport)
	c.OIDc.SetTransport(transport)
	c.Scim.SetTransport(transport)
	c.UserGroups.SetTransport(transport)
	c.Users.SetTransport(transport)
	c.Version.SetTransport(transport)
	c.WellKnown.SetTransport(transport)
}
