// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIAPIKeysIDReader is a Reader for the DeleteAPIAPIKeysID structure.
type DeleteAPIAPIKeysIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIAPIKeysIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIAPIKeysIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/api-keys/{id}] DeleteAPIAPIKeysID", response, response.Code())
	}
}

// NewDeleteAPIAPIKeysIDNoContent creates a DeleteAPIAPIKeysIDNoContent with default headers values
func NewDeleteAPIAPIKeysIDNoContent() *DeleteAPIAPIKeysIDNoContent {
	return &DeleteAPIAPIKeysIDNoContent{}
}

/*
DeleteAPIAPIKeysIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteAPIAPIKeysIDNoContent struct {
}

// IsSuccess returns true when this delete Api Api keys Id no content response has a 2xx status code
func (o *DeleteAPIAPIKeysIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api Api keys Id no content response has a 3xx status code
func (o *DeleteAPIAPIKeysIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api Api keys Id no content response has a 4xx status code
func (o *DeleteAPIAPIKeysIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api Api keys Id no content response has a 5xx status code
func (o *DeleteAPIAPIKeysIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api Api keys Id no content response a status code equal to that given
func (o *DeleteAPIAPIKeysIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api Api keys Id no content response
func (o *DeleteAPIAPIKeysIDNoContent) Code() int {
	return 204
}

func (o *DeleteAPIAPIKeysIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/api-keys/{id}][%d] deleteApiApiKeysIdNoContent", 204)
}

func (o *DeleteAPIAPIKeysIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/api-keys/{id}][%d] deleteApiApiKeysIdNoContent", 204)
}

func (o *DeleteAPIAPIKeysIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
