// Code generated by go-swagger; DO NOT EDIT.

package s_c_i_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIScimServiceProviderIDReader is a Reader for the DeleteAPIScimServiceProviderID structure.
type DeleteAPIScimServiceProviderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIScimServiceProviderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIScimServiceProviderIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/scim/service-provider/{id}] DeleteAPIScimServiceProviderID", response, response.Code())
	}
}

// NewDeleteAPIScimServiceProviderIDNoContent creates a DeleteAPIScimServiceProviderIDNoContent with default headers values
func NewDeleteAPIScimServiceProviderIDNoContent() *DeleteAPIScimServiceProviderIDNoContent {
	return &DeleteAPIScimServiceProviderIDNoContent{}
}

/*
DeleteAPIScimServiceProviderIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteAPIScimServiceProviderIDNoContent struct {
}

// IsSuccess returns true when this delete Api scim service provider Id no content response has a 2xx status code
func (o *DeleteAPIScimServiceProviderIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api scim service provider Id no content response has a 3xx status code
func (o *DeleteAPIScimServiceProviderIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api scim service provider Id no content response has a 4xx status code
func (o *DeleteAPIScimServiceProviderIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api scim service provider Id no content response has a 5xx status code
func (o *DeleteAPIScimServiceProviderIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api scim service provider Id no content response a status code equal to that given
func (o *DeleteAPIScimServiceProviderIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api scim service provider Id no content response
func (o *DeleteAPIScimServiceProviderIDNoContent) Code() int {
	return 204
}

func (o *DeleteAPIScimServiceProviderIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/scim/service-provider/{id}][%d] deleteApiScimServiceProviderIdNoContent", 204)
}

func (o *DeleteAPIScimServiceProviderIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/scim/service-provider/{id}][%d] deleteApiScimServiceProviderIdNoContent", 204)
}

func (o *DeleteAPIScimServiceProviderIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
