// Code generated by go-swagger; DO NOT EDIT.

package s_c_i_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
)

// NewPostAPIScimServiceProviderParams creates a new PostAPIScimServiceProviderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIScimServiceProviderParams() *PostAPIScimServiceProviderParams {
	return &PostAPIScimServiceProviderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIScimServiceProviderParamsWithTimeout creates a new PostAPIScimServiceProviderParams object
// with the ability to set a timeout on a request.
func NewPostAPIScimServiceProviderParamsWithTimeout(timeout time.Duration) *PostAPIScimServiceProviderParams {
	return &PostAPIScimServiceProviderParams{
		timeout: timeout,
	}
}

// NewPostAPIScimServiceProviderParamsWithContext creates a new PostAPIScimServiceProviderParams object
// with the ability to set a context for a request.
func NewPostAPIScimServiceProviderParamsWithContext(ctx context.Context) *PostAPIScimServiceProviderParams {
	return &PostAPIScimServiceProviderParams{
		Context: ctx,
	}
}

// NewPostAPIScimServiceProviderParamsWithHTTPClient creates a new PostAPIScimServiceProviderParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIScimServiceProviderParamsWithHTTPClient(client *http.Client) *PostAPIScimServiceProviderParams {
	return &PostAPIScimServiceProviderParams{
		HTTPClient: client,
	}
}

/*
PostAPIScimServiceProviderParams contains all the parameters to send to the API endpoint

	for the post API scim service provider operation.

	Typically these are written to a http.Request.
*/
type PostAPIScimServiceProviderParams struct {

	/* ServiceProvider.

	   SCIM service provider information
	*/
	ServiceProvider *models.GithubComPocketIDPocketIDBackendInternalDtoScimServiceProviderCreateDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API scim service provider params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIScimServiceProviderParams) WithDefaults() *PostAPIScimServiceProviderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API scim service provider params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIScimServiceProviderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API scim service provider params
func (o *PostAPIScimServiceProviderParams) WithTimeout(timeout time.Duration) *PostAPIScimServiceProviderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API scim service provider params
func (o *PostAPIScimServiceProviderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API scim service provider params
func (o *PostAPIScimServiceProviderParams) WithContext(ctx context.Context) *PostAPIScimServiceProviderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API scim service provider params
func (o *PostAPIScimServiceProviderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API scim service provider params
func (o *PostAPIScimServiceProviderParams) WithHTTPClient(client *http.Client) *PostAPIScimServiceProviderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API scim service provider params
func (o *PostAPIScimServiceProviderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServiceProvider adds the serviceProvider to the post API scim service provider params
func (o *PostAPIScimServiceProviderParams) WithServiceProvider(serviceProvider *models.GithubComPocketIDPocketIDBackendInternalDtoScimServiceProviderCreateDTO) *PostAPIScimServiceProviderParams {
	o.SetServiceProvider(serviceProvider)
	return o
}

// SetServiceProvider adds the serviceProvider to the post API scim service provider params
func (o *PostAPIScimServiceProviderParams) SetServiceProvider(serviceProvider *models.GithubComPocketIDPocketIDBackendInternalDtoScimServiceProviderCreateDTO) {
	o.ServiceProvider = serviceProvider
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIScimServiceProviderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ServiceProvider != nil {
		if err := r.SetBodyParam(o.ServiceProvider); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
