// Code generated by go-swagger; DO NOT EDIT.

package user_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIUserGroupsIDReader is a Reader for the DeleteAPIUserGroupsID structure.
type DeleteAPIUserGroupsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIUserGroupsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIUserGroupsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/user-groups/{id}] DeleteAPIUserGroupsID", response, response.Code())
	}
}

// NewDeleteAPIUserGroupsIDNoContent creates a DeleteAPIUserGroupsIDNoContent with default headers values
func NewDeleteAPIUserGroupsIDNoContent() *DeleteAPIUserGroupsIDNoContent {
	return &DeleteAPIUserGroupsIDNoContent{}
}

/*
DeleteAPIUserGroupsIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteAPIUserGroupsIDNoContent struct {
}

// IsSuccess returns true when this delete Api user groups Id no content response has a 2xx status code
func (o *DeleteAPIUserGroupsIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api user groups Id no content response has a 3xx status code
func (o *DeleteAPIUserGroupsIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api user groups Id no content response has a 4xx status code
func (o *DeleteAPIUserGroupsIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api user groups Id no content response has a 5xx status code
func (o *DeleteAPIUserGroupsIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api user groups Id no content response a status code equal to that given
func (o *DeleteAPIUserGroupsIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api user groups Id no content response
func (o *DeleteAPIUserGroupsIDNoContent) Code() int {
	return 204
}

func (o *DeleteAPIUserGroupsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/user-groups/{id}][%d] deleteApiUserGroupsIdNoContent", 204)
}

func (o *DeleteAPIUserGroupsIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/user-groups/{id}][%d] deleteApiUserGroupsIdNoContent", 204)
}

func (o *DeleteAPIUserGroupsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
