// Code generated by go-swagger; DO NOT EDIT.

package user_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIUserGroupsIDParams creates a new DeleteAPIUserGroupsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIUserGroupsIDParams() *DeleteAPIUserGroupsIDParams {
	return &DeleteAPIUserGroupsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIUserGroupsIDParamsWithTimeout creates a new DeleteAPIUserGroupsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIUserGroupsIDParamsWithTimeout(timeout time.Duration) *DeleteAPIUserGroupsIDParams {
	return &DeleteAPIUserGroupsIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIUserGroupsIDParamsWithContext creates a new DeleteAPIUserGroupsIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIUserGroupsIDParamsWithContext(ctx context.Context) *DeleteAPIUserGroupsIDParams {
	return &DeleteAPIUserGroupsIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIUserGroupsIDParamsWithHTTPClient creates a new DeleteAPIUserGroupsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIUserGroupsIDParamsWithHTTPClient(client *http.Client) *DeleteAPIUserGroupsIDParams {
	return &DeleteAPIUserGroupsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIUserGroupsIDParams contains all the parameters to send to the API endpoint

	for the delete API user groups ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIUserGroupsIDParams struct {

	/* ID.

	   User Group ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API user groups ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIUserGroupsIDParams) WithDefaults() *DeleteAPIUserGroupsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API user groups ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIUserGroupsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API user groups ID params
func (o *DeleteAPIUserGroupsIDParams) WithTimeout(timeout time.Duration) *DeleteAPIUserGroupsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API user groups ID params
func (o *DeleteAPIUserGroupsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API user groups ID params
func (o *DeleteAPIUserGroupsIDParams) WithContext(ctx context.Context) *DeleteAPIUserGroupsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API user groups ID params
func (o *DeleteAPIUserGroupsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API user groups ID params
func (o *DeleteAPIUserGroupsIDParams) WithHTTPClient(client *http.Client) *DeleteAPIUserGroupsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API user groups ID params
func (o *DeleteAPIUserGroupsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API user groups ID params
func (o *DeleteAPIUserGroupsIDParams) WithID(id string) *DeleteAPIUserGroupsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API user groups ID params
func (o *DeleteAPIUserGroupsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIUserGroupsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
