// Code generated by go-swagger; DO NOT EDIT.

package user_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIUserGroupsParams creates a new GetAPIUserGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIUserGroupsParams() *GetAPIUserGroupsParams {
	return &GetAPIUserGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIUserGroupsParamsWithTimeout creates a new GetAPIUserGroupsParams object
// with the ability to set a timeout on a request.
func NewGetAPIUserGroupsParamsWithTimeout(timeout time.Duration) *GetAPIUserGroupsParams {
	return &GetAPIUserGroupsParams{
		timeout: timeout,
	}
}

// NewGetAPIUserGroupsParamsWithContext creates a new GetAPIUserGroupsParams object
// with the ability to set a context for a request.
func NewGetAPIUserGroupsParamsWithContext(ctx context.Context) *GetAPIUserGroupsParams {
	return &GetAPIUserGroupsParams{
		Context: ctx,
	}
}

// NewGetAPIUserGroupsParamsWithHTTPClient creates a new GetAPIUserGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIUserGroupsParamsWithHTTPClient(client *http.Client) *GetAPIUserGroupsParams {
	return &GetAPIUserGroupsParams{
		HTTPClient: client,
	}
}

/*
GetAPIUserGroupsParams contains all the parameters to send to the API endpoint

	for the get API user groups operation.

	Typically these are written to a http.Request.
*/
type GetAPIUserGroupsParams struct {

	/* PaginationLimit.

	   Number of items per page

	   Default: 20
	*/
	PaginationLimit *int64

	/* PaginationPage.

	   Page number for pagination

	   Default: 1
	*/
	PaginationPage *int64

	/* Search.

	   Search term to filter user groups by name
	*/
	Search *string

	/* SortColumn.

	   Column to sort by
	*/
	SortColumn *string

	/* SortDirection.

	   Sort direction (asc or desc)

	   Default: "\"asc\""
	*/
	SortDirection *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUserGroupsParams) WithDefaults() *GetAPIUserGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUserGroupsParams) SetDefaults() {
	var (
		paginationLimitDefault = int64(20)

		paginationPageDefault = int64(1)

		sortDirectionDefault = string("\"asc\"")
	)

	val := GetAPIUserGroupsParams{
		PaginationLimit: &paginationLimitDefault,
		PaginationPage:  &paginationPageDefault,
		SortDirection:   &sortDirectionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API user groups params
func (o *GetAPIUserGroupsParams) WithTimeout(timeout time.Duration) *GetAPIUserGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API user groups params
func (o *GetAPIUserGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API user groups params
func (o *GetAPIUserGroupsParams) WithContext(ctx context.Context) *GetAPIUserGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API user groups params
func (o *GetAPIUserGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API user groups params
func (o *GetAPIUserGroupsParams) WithHTTPClient(client *http.Client) *GetAPIUserGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API user groups params
func (o *GetAPIUserGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPaginationLimit adds the paginationLimit to the get API user groups params
func (o *GetAPIUserGroupsParams) WithPaginationLimit(paginationLimit *int64) *GetAPIUserGroupsParams {
	o.SetPaginationLimit(paginationLimit)
	return o
}

// SetPaginationLimit adds the paginationLimit to the get API user groups params
func (o *GetAPIUserGroupsParams) SetPaginationLimit(paginationLimit *int64) {
	o.PaginationLimit = paginationLimit
}

// WithPaginationPage adds the paginationPage to the get API user groups params
func (o *GetAPIUserGroupsParams) WithPaginationPage(paginationPage *int64) *GetAPIUserGroupsParams {
	o.SetPaginationPage(paginationPage)
	return o
}

// SetPaginationPage adds the paginationPage to the get API user groups params
func (o *GetAPIUserGroupsParams) SetPaginationPage(paginationPage *int64) {
	o.PaginationPage = paginationPage
}

// WithSearch adds the search to the get API user groups params
func (o *GetAPIUserGroupsParams) WithSearch(search *string) *GetAPIUserGroupsParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get API user groups params
func (o *GetAPIUserGroupsParams) SetSearch(search *string) {
	o.Search = search
}

// WithSortColumn adds the sortColumn to the get API user groups params
func (o *GetAPIUserGroupsParams) WithSortColumn(sortColumn *string) *GetAPIUserGroupsParams {
	o.SetSortColumn(sortColumn)
	return o
}

// SetSortColumn adds the sortColumn to the get API user groups params
func (o *GetAPIUserGroupsParams) SetSortColumn(sortColumn *string) {
	o.SortColumn = sortColumn
}

// WithSortDirection adds the sortDirection to the get API user groups params
func (o *GetAPIUserGroupsParams) WithSortDirection(sortDirection *string) *GetAPIUserGroupsParams {
	o.SetSortDirection(sortDirection)
	return o
}

// SetSortDirection adds the sortDirection to the get API user groups params
func (o *GetAPIUserGroupsParams) SetSortDirection(sortDirection *string) {
	o.SortDirection = sortDirection
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIUserGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PaginationLimit != nil {

		// query param pagination[limit]
		var qrPaginationLimit int64

		if o.PaginationLimit != nil {
			qrPaginationLimit = *o.PaginationLimit
		}
		qPaginationLimit := swag.FormatInt64(qrPaginationLimit)
		if qPaginationLimit != "" {

			if err := r.SetQueryParam("pagination[limit]", qPaginationLimit); err != nil {
				return err
			}
		}
	}

	if o.PaginationPage != nil {

		// query param pagination[page]
		var qrPaginationPage int64

		if o.PaginationPage != nil {
			qrPaginationPage = *o.PaginationPage
		}
		qPaginationPage := swag.FormatInt64(qrPaginationPage)
		if qPaginationPage != "" {

			if err := r.SetQueryParam("pagination[page]", qPaginationPage); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if o.SortColumn != nil {

		// query param sort[column]
		var qrSortColumn string

		if o.SortColumn != nil {
			qrSortColumn = *o.SortColumn
		}
		qSortColumn := qrSortColumn
		if qSortColumn != "" {

			if err := r.SetQueryParam("sort[column]", qSortColumn); err != nil {
				return err
			}
		}
	}

	if o.SortDirection != nil {

		// query param sort[direction]
		var qrSortDirection string

		if o.SortDirection != nil {
			qrSortDirection = *o.SortDirection
		}
		qSortDirection := qrSortDirection
		if qSortDirection != "" {

			if err := r.SetQueryParam("sort[direction]", qSortDirection); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
