// Code generated by go-swagger; DO NOT EDIT.

package user_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
)

// PutAPIUserGroupsIDUsersReader is a Reader for the PutAPIUserGroupsIDUsers structure.
type PutAPIUserGroupsIDUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIUserGroupsIDUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIUserGroupsIDUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/user-groups/{id}/users] PutAPIUserGroupsIDUsers", response, response.Code())
	}
}

// NewPutAPIUserGroupsIDUsersOK creates a PutAPIUserGroupsIDUsersOK with default headers values
func NewPutAPIUserGroupsIDUsersOK() *PutAPIUserGroupsIDUsersOK {
	return &PutAPIUserGroupsIDUsersOK{}
}

/*
PutAPIUserGroupsIDUsersOK describes a response with status code 200, with default header values.

OK
*/
type PutAPIUserGroupsIDUsersOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupDto
}

// IsSuccess returns true when this put Api user groups Id users o k response has a 2xx status code
func (o *PutAPIUserGroupsIDUsersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api user groups Id users o k response has a 3xx status code
func (o *PutAPIUserGroupsIDUsersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api user groups Id users o k response has a 4xx status code
func (o *PutAPIUserGroupsIDUsersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api user groups Id users o k response has a 5xx status code
func (o *PutAPIUserGroupsIDUsersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api user groups Id users o k response a status code equal to that given
func (o *PutAPIUserGroupsIDUsersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api user groups Id users o k response
func (o *PutAPIUserGroupsIDUsersOK) Code() int {
	return 200
}

func (o *PutAPIUserGroupsIDUsersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/user-groups/{id}/users][%d] putApiUserGroupsIdUsersOK %s", 200, payload)
}

func (o *PutAPIUserGroupsIDUsersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/user-groups/{id}/users][%d] putApiUserGroupsIdUsersOK %s", 200, payload)
}

func (o *PutAPIUserGroupsIDUsersOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupDto {
	return o.Payload
}

func (o *PutAPIUserGroupsIDUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
