// Code generated by go-swagger; DO NOT EDIT.

package user_groups

import (
	"context"
	"net/http"
	"time"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIUserGroupsIDParams creates a new PutAPIUserGroupsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIUserGroupsIDParams() *PutAPIUserGroupsIDParams {
	return NewPutAPIUserGroupsIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutAPIUserGroupsIDParamsWithTimeout creates a new PutAPIUserGroupsIDParams object
// with the ability to set a timeout on a request.
func NewPutAPIUserGroupsIDParamsWithTimeout(timeout time.Duration) *PutAPIUserGroupsIDParams {
	return &PutAPIUserGroupsIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutAPIUserGroupsIDParamsWithContext creates a new PutAPIUserGroupsIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIUserGroupsIDParams].
func NewPutAPIUserGroupsIDParamsWithContext(ctx context.Context) *PutAPIUserGroupsIDParams {
	return &PutAPIUserGroupsIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutAPIUserGroupsIDParamsWithHTTPClient creates a new PutAPIUserGroupsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIUserGroupsIDParamsWithHTTPClient(client *http.Client) *PutAPIUserGroupsIDParams {
	return &PutAPIUserGroupsIDParams{
		HTTPClient: client,
	}
}

/*
PutAPIUserGroupsIDParams contains all the parameters to send to the API endpoint

	for the put API user groups ID operation.

	Typically these are written to a http.Request.
*/
type PutAPIUserGroupsIDParams struct {

	/* ID.

	   User Group ID
	*/
	ID string

	/* UserGroup.

	   User group information
	*/
	UserGroup *models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put API user groups ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUserGroupsIDParams) WithDefaults() *PutAPIUserGroupsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API user groups ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUserGroupsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API user groups ID params.
func (o *PutAPIUserGroupsIDParams) WithTimeout(timeout time.Duration) *PutAPIUserGroupsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API user groups ID params.
func (o *PutAPIUserGroupsIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put API user groups ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIUserGroupsIDParams].
func (o *PutAPIUserGroupsIDParams) WithContext(ctx context.Context) *PutAPIUserGroupsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API user groups ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIUserGroupsIDParams].
func (o *PutAPIUserGroupsIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put API user groups ID params.
func (o *PutAPIUserGroupsIDParams) WithHTTPClient(client *http.Client) *PutAPIUserGroupsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API user groups ID params.
func (o *PutAPIUserGroupsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put API user groups ID params.
func (o *PutAPIUserGroupsIDParams) WithID(id string) *PutAPIUserGroupsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API user groups ID params.
func (o *PutAPIUserGroupsIDParams) SetID(id string) {
	o.ID = id
}

// WithUserGroup adds the userGroup to the put API user groups ID params.
func (o *PutAPIUserGroupsIDParams) WithUserGroup(userGroup *models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto) *PutAPIUserGroupsIDParams {
	o.SetUserGroup(userGroup)
	return o
}

// SetUserGroup adds the userGroup to the put API user groups ID params.
func (o *PutAPIUserGroupsIDParams) SetUserGroup(userGroup *models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto) {
	o.UserGroup = userGroup
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutAPIUserGroupsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.UserGroup != nil {
		if err := r.SetBodyParam(o.UserGroup); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
