// Code generated by go-swagger; DO NOT EDIT.

package application_configuration

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new application configuration API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new application configuration API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new application configuration API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for application configuration API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetAPIApplicationConfiguration(params *GetAPIApplicationConfigurationParams, opts ...ClientOption) (*GetAPIApplicationConfigurationOK, error)

	GetAPIApplicationConfigurationAll(params *GetAPIApplicationConfigurationAllParams, opts ...ClientOption) (*GetAPIApplicationConfigurationAllOK, error)

	PostAPIApplicationConfigurationSyncLdap(params *PostAPIApplicationConfigurationSyncLdapParams, opts ...ClientOption) (*PostAPIApplicationConfigurationSyncLdapNoContent, error)

	PostAPIApplicationConfigurationTestEmail(params *PostAPIApplicationConfigurationTestEmailParams, opts ...ClientOption) (*PostAPIApplicationConfigurationTestEmailNoContent, error)

	PutAPIApplicationConfiguration(params *PutAPIApplicationConfigurationParams, opts ...ClientOption) (*PutAPIApplicationConfigurationOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetAPIApplicationConfiguration lists public application configurations

Get all public application configurations
*/
func (a *Client) GetAPIApplicationConfiguration(params *GetAPIApplicationConfigurationParams, opts ...ClientOption) (*GetAPIApplicationConfigurationOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIApplicationConfigurationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIApplicationConfiguration",
		Method:             "GET",
		PathPattern:        "/api/application-configuration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIApplicationConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIApplicationConfigurationOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIApplicationConfiguration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIApplicationConfigurationAll lists all application configurations

Get all application configurations including private ones
*/
func (a *Client) GetAPIApplicationConfigurationAll(params *GetAPIApplicationConfigurationAllParams, opts ...ClientOption) (*GetAPIApplicationConfigurationAllOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIApplicationConfigurationAllParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIApplicationConfigurationAll",
		Method:             "GET",
		PathPattern:        "/api/application-configuration/all",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIApplicationConfigurationAllReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIApplicationConfigurationAllOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIApplicationConfigurationAll: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIApplicationConfigurationSyncLdap synchronizes l d a p

Manually trigger LDAP synchronization
*/
func (a *Client) PostAPIApplicationConfigurationSyncLdap(params *PostAPIApplicationConfigurationSyncLdapParams, opts ...ClientOption) (*PostAPIApplicationConfigurationSyncLdapNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIApplicationConfigurationSyncLdapParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIApplicationConfigurationSyncLdap",
		Method:             "POST",
		PathPattern:        "/api/application-configuration/sync-ldap",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIApplicationConfigurationSyncLdapReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIApplicationConfigurationSyncLdapNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIApplicationConfigurationSyncLdap: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIApplicationConfigurationTestEmail sends test email

Send a test email to verify email configuration
*/
func (a *Client) PostAPIApplicationConfigurationTestEmail(params *PostAPIApplicationConfigurationTestEmailParams, opts ...ClientOption) (*PostAPIApplicationConfigurationTestEmailNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIApplicationConfigurationTestEmailParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIApplicationConfigurationTestEmail",
		Method:             "POST",
		PathPattern:        "/api/application-configuration/test-email",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIApplicationConfigurationTestEmailReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIApplicationConfigurationTestEmailNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIApplicationConfigurationTestEmail: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIApplicationConfiguration updates application configurations

Update application configuration settings
*/
func (a *Client) PutAPIApplicationConfiguration(params *PutAPIApplicationConfigurationParams, opts ...ClientOption) (*PutAPIApplicationConfigurationOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIApplicationConfigurationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIApplicationConfiguration",
		Method:             "PUT",
		PathPattern:        "/api/application-configuration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIApplicationConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIApplicationConfigurationOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIApplicationConfiguration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
