// Code generated by go-swagger; DO NOT EDIT.

package application_configuration

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIApplicationConfigurationReader is a Reader for the GetAPIApplicationConfiguration structure.
type GetAPIApplicationConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIApplicationConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIApplicationConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIApplicationConfigurationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIApplicationConfigurationOK creates a GetAPIApplicationConfigurationOK with default headers values
func NewGetAPIApplicationConfigurationOK() *GetAPIApplicationConfigurationOK {
	return &GetAPIApplicationConfigurationOK{}
}

// GetAPIApplicationConfigurationOK describes a response with status code 200, with default header values.
//
// OK
type GetAPIApplicationConfigurationOK struct {
	Payload []*models.GithubComPocketIDPocketIDBackendInternalDtoPublicAppConfigVariableDto
}

// IsSuccess returns true when this get Api application configuration o k response has a 2xx status code
func (o *GetAPIApplicationConfigurationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api application configuration o k response has a 3xx status code
func (o *GetAPIApplicationConfigurationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api application configuration o k response has a 4xx status code
func (o *GetAPIApplicationConfigurationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api application configuration o k response has a 5xx status code
func (o *GetAPIApplicationConfigurationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api application configuration o k response a status code equal to that given
func (o *GetAPIApplicationConfigurationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api application configuration o k response
func (o *GetAPIApplicationConfigurationOK) Code() int {
	return 200
}

func (o *GetAPIApplicationConfigurationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-configuration][%d] getApiApplicationConfigurationOK %s", 200, payload)
}

func (o *GetAPIApplicationConfigurationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-configuration][%d] getApiApplicationConfigurationOK %s", 200, payload)
}

func (o *GetAPIApplicationConfigurationOK) GetPayload() []*models.GithubComPocketIDPocketIDBackendInternalDtoPublicAppConfigVariableDto {
	return o.Payload
}

func (o *GetAPIApplicationConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIApplicationConfigurationDefault creates a GetAPIApplicationConfigurationDefault with default headers values
func NewGetAPIApplicationConfigurationDefault(code int) *GetAPIApplicationConfigurationDefault {
	return &GetAPIApplicationConfigurationDefault{
		_statusCode: code,
	}
}

// GetAPIApplicationConfigurationDefault describes a response with status code -1, with default header values.
//
// Error
type GetAPIApplicationConfigurationDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this get API application configuration default response has a 2xx status code
func (o *GetAPIApplicationConfigurationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API application configuration default response has a 3xx status code
func (o *GetAPIApplicationConfigurationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API application configuration default response has a 4xx status code
func (o *GetAPIApplicationConfigurationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API application configuration default response has a 5xx status code
func (o *GetAPIApplicationConfigurationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API application configuration default response a status code equal to that given
func (o *GetAPIApplicationConfigurationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get API application configuration default response
func (o *GetAPIApplicationConfigurationDefault) Code() int {
	return o._statusCode
}

func (o *GetAPIApplicationConfigurationDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-configuration][%d] GetAPIApplicationConfiguration default %s", o._statusCode, payload)
}

func (o *GetAPIApplicationConfigurationDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-configuration][%d] GetAPIApplicationConfiguration default %s", o._statusCode, payload)
}

func (o *GetAPIApplicationConfigurationDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *GetAPIApplicationConfigurationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
