// Code generated by go-swagger; DO NOT EDIT.

package application_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetApplicationConfigurationParams creates a new GetApplicationConfigurationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetApplicationConfigurationParams() *GetApplicationConfigurationParams {
	return &GetApplicationConfigurationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationConfigurationParamsWithTimeout creates a new GetApplicationConfigurationParams object
// with the ability to set a timeout on a request.
func NewGetApplicationConfigurationParamsWithTimeout(timeout time.Duration) *GetApplicationConfigurationParams {
	return &GetApplicationConfigurationParams{
		timeout: timeout,
	}
}

// NewGetApplicationConfigurationParamsWithContext creates a new GetApplicationConfigurationParams object
// with the ability to set a context for a request.
func NewGetApplicationConfigurationParamsWithContext(ctx context.Context) *GetApplicationConfigurationParams {
	return &GetApplicationConfigurationParams{
		Context: ctx,
	}
}

// NewGetApplicationConfigurationParamsWithHTTPClient creates a new GetApplicationConfigurationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetApplicationConfigurationParamsWithHTTPClient(client *http.Client) *GetApplicationConfigurationParams {
	return &GetApplicationConfigurationParams{
		HTTPClient: client,
	}
}

/*
GetApplicationConfigurationParams contains all the parameters to send to the API endpoint

	for the get application configuration operation.

	Typically these are written to a http.Request.
*/
type GetApplicationConfigurationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get application configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetApplicationConfigurationParams) WithDefaults() *GetApplicationConfigurationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get application configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetApplicationConfigurationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get application configuration params
func (o *GetApplicationConfigurationParams) WithTimeout(timeout time.Duration) *GetApplicationConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get application configuration params
func (o *GetApplicationConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get application configuration params
func (o *GetApplicationConfigurationParams) WithContext(ctx context.Context) *GetApplicationConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get application configuration params
func (o *GetApplicationConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get application configuration params
func (o *GetApplicationConfigurationParams) WithHTTPClient(client *http.Client) *GetApplicationConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get application configuration params
func (o *GetApplicationConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
