// Code generated by go-swagger; DO NOT EDIT.

package application_configuration

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIApplicationConfigurationAllReader is a Reader for the GetAPIApplicationConfigurationAll structure.
type GetAPIApplicationConfigurationAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIApplicationConfigurationAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIApplicationConfigurationAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIApplicationConfigurationAllDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIApplicationConfigurationAllOK creates a GetAPIApplicationConfigurationAllOK with default headers values
func NewGetAPIApplicationConfigurationAllOK() *GetAPIApplicationConfigurationAllOK {
	return &GetAPIApplicationConfigurationAllOK{}
}

// GetAPIApplicationConfigurationAllOK describes a response with status code 200, with default header values.
//
// OK
type GetAPIApplicationConfigurationAllOK struct {
	Payload []*models.GithubComPocketIDPocketIDBackendInternalDtoAppConfigVariableDto
}

// IsSuccess returns true when this get Api application configuration all o k response has a 2xx status code
func (o *GetAPIApplicationConfigurationAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api application configuration all o k response has a 3xx status code
func (o *GetAPIApplicationConfigurationAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api application configuration all o k response has a 4xx status code
func (o *GetAPIApplicationConfigurationAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api application configuration all o k response has a 5xx status code
func (o *GetAPIApplicationConfigurationAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api application configuration all o k response a status code equal to that given
func (o *GetAPIApplicationConfigurationAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api application configuration all o k response
func (o *GetAPIApplicationConfigurationAllOK) Code() int {
	return 200
}

func (o *GetAPIApplicationConfigurationAllOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-configuration/all][%d] getApiApplicationConfigurationAllOK %s", 200, payload)
}

func (o *GetAPIApplicationConfigurationAllOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-configuration/all][%d] getApiApplicationConfigurationAllOK %s", 200, payload)
}

func (o *GetAPIApplicationConfigurationAllOK) GetPayload() []*models.GithubComPocketIDPocketIDBackendInternalDtoAppConfigVariableDto {
	return o.Payload
}

func (o *GetAPIApplicationConfigurationAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIApplicationConfigurationAllDefault creates a GetAPIApplicationConfigurationAllDefault with default headers values
func NewGetAPIApplicationConfigurationAllDefault(code int) *GetAPIApplicationConfigurationAllDefault {
	return &GetAPIApplicationConfigurationAllDefault{
		_statusCode: code,
	}
}

// GetAPIApplicationConfigurationAllDefault describes a response with status code -1, with default header values.
//
// Error
type GetAPIApplicationConfigurationAllDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this get API application configuration all default response has a 2xx status code
func (o *GetAPIApplicationConfigurationAllDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API application configuration all default response has a 3xx status code
func (o *GetAPIApplicationConfigurationAllDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API application configuration all default response has a 4xx status code
func (o *GetAPIApplicationConfigurationAllDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API application configuration all default response has a 5xx status code
func (o *GetAPIApplicationConfigurationAllDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API application configuration all default response a status code equal to that given
func (o *GetAPIApplicationConfigurationAllDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get API application configuration all default response
func (o *GetAPIApplicationConfigurationAllDefault) Code() int {
	return o._statusCode
}

func (o *GetAPIApplicationConfigurationAllDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-configuration/all][%d] GetAPIApplicationConfigurationAll default %s", o._statusCode, payload)
}

func (o *GetAPIApplicationConfigurationAllDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-configuration/all][%d] GetAPIApplicationConfigurationAll default %s", o._statusCode, payload)
}

func (o *GetAPIApplicationConfigurationAllDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *GetAPIApplicationConfigurationAllDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
