// Code generated by go-swagger; DO NOT EDIT.

package application_configuration

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIApplicationConfigurationParams creates a new GetAPIApplicationConfigurationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIApplicationConfigurationParams() *GetAPIApplicationConfigurationParams {
	return &GetAPIApplicationConfigurationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIApplicationConfigurationParamsWithTimeout creates a new GetAPIApplicationConfigurationParams object
// with the ability to set a timeout on a request.
func NewGetAPIApplicationConfigurationParamsWithTimeout(timeout time.Duration) *GetAPIApplicationConfigurationParams {
	return &GetAPIApplicationConfigurationParams{
		timeout: timeout,
	}
}

// NewGetAPIApplicationConfigurationParamsWithContext creates a new GetAPIApplicationConfigurationParams object
// with the ability to set a context for a request.
func NewGetAPIApplicationConfigurationParamsWithContext(ctx context.Context) *GetAPIApplicationConfigurationParams {
	return &GetAPIApplicationConfigurationParams{
		Context: ctx,
	}
}

// NewGetAPIApplicationConfigurationParamsWithHTTPClient creates a new GetAPIApplicationConfigurationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIApplicationConfigurationParamsWithHTTPClient(client *http.Client) *GetAPIApplicationConfigurationParams {
	return &GetAPIApplicationConfigurationParams{
		HTTPClient: client,
	}
}

/*
GetAPIApplicationConfigurationParams contains all the parameters to send to the API endpoint

	for the get API application configuration operation.

	Typically these are written to a http.Request.
*/
type GetAPIApplicationConfigurationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API application configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIApplicationConfigurationParams) WithDefaults() *GetAPIApplicationConfigurationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API application configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIApplicationConfigurationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API application configuration params
func (o *GetAPIApplicationConfigurationParams) WithTimeout(timeout time.Duration) *GetAPIApplicationConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API application configuration params
func (o *GetAPIApplicationConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API application configuration params
func (o *GetAPIApplicationConfigurationParams) WithContext(ctx context.Context) *GetAPIApplicationConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API application configuration params
func (o *GetAPIApplicationConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API application configuration params
func (o *GetAPIApplicationConfigurationParams) WithHTTPClient(client *http.Client) *GetAPIApplicationConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API application configuration params
func (o *GetAPIApplicationConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIApplicationConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
