// Code generated by go-swagger; DO NOT EDIT.

package application_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
)

// NewPutAPIApplicationConfigurationParams creates a new PutAPIApplicationConfigurationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIApplicationConfigurationParams() *PutAPIApplicationConfigurationParams {
	return &PutAPIApplicationConfigurationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIApplicationConfigurationParamsWithTimeout creates a new PutAPIApplicationConfigurationParams object
// with the ability to set a timeout on a request.
func NewPutAPIApplicationConfigurationParamsWithTimeout(timeout time.Duration) *PutAPIApplicationConfigurationParams {
	return &PutAPIApplicationConfigurationParams{
		timeout: timeout,
	}
}

// NewPutAPIApplicationConfigurationParamsWithContext creates a new PutAPIApplicationConfigurationParams object
// with the ability to set a context for a request.
func NewPutAPIApplicationConfigurationParamsWithContext(ctx context.Context) *PutAPIApplicationConfigurationParams {
	return &PutAPIApplicationConfigurationParams{
		Context: ctx,
	}
}

// NewPutAPIApplicationConfigurationParamsWithHTTPClient creates a new PutAPIApplicationConfigurationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIApplicationConfigurationParamsWithHTTPClient(client *http.Client) *PutAPIApplicationConfigurationParams {
	return &PutAPIApplicationConfigurationParams{
		HTTPClient: client,
	}
}

/*
PutAPIApplicationConfigurationParams contains all the parameters to send to the API endpoint

	for the put API application configuration operation.

	Typically these are written to a http.Request.
*/
type PutAPIApplicationConfigurationParams struct {

	/* Body.

	   Application Configuration
	*/
	Body *models.GithubComPocketIDPocketIDBackendInternalDtoAppConfigUpdateDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API application configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIApplicationConfigurationParams) WithDefaults() *PutAPIApplicationConfigurationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API application configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIApplicationConfigurationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API application configuration params
func (o *PutAPIApplicationConfigurationParams) WithTimeout(timeout time.Duration) *PutAPIApplicationConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API application configuration params
func (o *PutAPIApplicationConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API application configuration params
func (o *PutAPIApplicationConfigurationParams) WithContext(ctx context.Context) *PutAPIApplicationConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API application configuration params
func (o *PutAPIApplicationConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API application configuration params
func (o *PutAPIApplicationConfigurationParams) WithHTTPClient(client *http.Client) *PutAPIApplicationConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API application configuration params
func (o *PutAPIApplicationConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API application configuration params
func (o *PutAPIApplicationConfigurationParams) WithBody(body *models.GithubComPocketIDPocketIDBackendInternalDtoAppConfigUpdateDto) *PutAPIApplicationConfigurationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API application configuration params
func (o *PutAPIApplicationConfigurationParams) SetBody(body *models.GithubComPocketIDPocketIDBackendInternalDtoAppConfigUpdateDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIApplicationConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
