// Code generated by go-swagger; DO NOT EDIT.

package custom_claims

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/models"
)

// PutAPICustomClaimsUserGroupUserGroupIDReader is a Reader for the PutAPICustomClaimsUserGroupUserGroupID structure.
type PutAPICustomClaimsUserGroupUserGroupIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPICustomClaimsUserGroupUserGroupIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPICustomClaimsUserGroupUserGroupIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/custom-claims/user-group/{userGroupId}] PutAPICustomClaimsUserGroupUserGroupID", response, response.Code())
	}
}

// NewPutAPICustomClaimsUserGroupUserGroupIDOK creates a PutAPICustomClaimsUserGroupUserGroupIDOK with default headers values
func NewPutAPICustomClaimsUserGroupUserGroupIDOK() *PutAPICustomClaimsUserGroupUserGroupIDOK {
	return &PutAPICustomClaimsUserGroupUserGroupIDOK{}
}

/*
PutAPICustomClaimsUserGroupUserGroupIDOK describes a response with status code 200, with default header values.

Updated custom claims
*/
type PutAPICustomClaimsUserGroupUserGroupIDOK struct {
	Payload []*models.GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto
}

// IsSuccess returns true when this put Api custom claims user group user group Id o k response has a 2xx status code
func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api custom claims user group user group Id o k response has a 3xx status code
func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api custom claims user group user group Id o k response has a 4xx status code
func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api custom claims user group user group Id o k response has a 5xx status code
func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api custom claims user group user group Id o k response a status code equal to that given
func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api custom claims user group user group Id o k response
func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) Code() int {
	return 200
}

func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/custom-claims/user-group/{userGroupId}][%d] putApiCustomClaimsUserGroupUserGroupIdOK %s", 200, payload)
}

func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/custom-claims/user-group/{userGroupId}][%d] putApiCustomClaimsUserGroupUserGroupIdOK %s", 200, payload)
}

func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) GetPayload() []*models.GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto {
	return o.Payload
}

func (o *PutAPICustomClaimsUserGroupUserGroupIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
