// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIUsersIDParams creates a new DeleteAPIUsersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIUsersIDParams() *DeleteAPIUsersIDParams {
	return &DeleteAPIUsersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIUsersIDParamsWithTimeout creates a new DeleteAPIUsersIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIUsersIDParamsWithTimeout(timeout time.Duration) *DeleteAPIUsersIDParams {
	return &DeleteAPIUsersIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIUsersIDParamsWithContext creates a new DeleteAPIUsersIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIUsersIDParamsWithContext(ctx context.Context) *DeleteAPIUsersIDParams {
	return &DeleteAPIUsersIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIUsersIDParamsWithHTTPClient creates a new DeleteAPIUsersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIUsersIDParamsWithHTTPClient(client *http.Client) *DeleteAPIUsersIDParams {
	return &DeleteAPIUsersIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIUsersIDParams contains all the parameters to send to the API endpoint

	for the delete API users ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIUsersIDParams struct {

	/* ID.

	   User ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIUsersIDParams) WithDefaults() *DeleteAPIUsersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIUsersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API users ID params
func (o *DeleteAPIUsersIDParams) WithTimeout(timeout time.Duration) *DeleteAPIUsersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API users ID params
func (o *DeleteAPIUsersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API users ID params
func (o *DeleteAPIUsersIDParams) WithContext(ctx context.Context) *DeleteAPIUsersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API users ID params
func (o *DeleteAPIUsersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API users ID params
func (o *DeleteAPIUsersIDParams) WithHTTPClient(client *http.Client) *DeleteAPIUsersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API users ID params
func (o *DeleteAPIUsersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API users ID params
func (o *DeleteAPIUsersIDParams) WithID(id string) *DeleteAPIUsersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API users ID params
func (o *DeleteAPIUsersIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIUsersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
