// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIUsersIDWebauthnCredentialsCredentialIDReader is a Reader for the DeleteAPIUsersIDWebauthnCredentialsCredentialID structure.
type DeleteAPIUsersIDWebauthnCredentialsCredentialIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent creates a DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent with default headers values
func NewDeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent() *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent {
	return &DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent{}
}

// DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent describes a response with status code 204, with default header values.
//
// No Content
type DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent struct {
}

// IsSuccess returns true when this delete Api users Id webauthn credentials credential Id no content response has a 2xx status code
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api users Id webauthn credentials credential Id no content response has a 3xx status code
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api users Id webauthn credentials credential Id no content response has a 4xx status code
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api users Id webauthn credentials credential Id no content response has a 5xx status code
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api users Id webauthn credentials credential Id no content response a status code equal to that given
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api users Id webauthn credentials credential Id no content response
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) Code() int {
	return 204
}

func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/users/{id}/webauthn-credentials/{credentialId}][%d] deleteApiUsersIdWebauthnCredentialsCredentialIdNoContent", 204)
}

func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/users/{id}/webauthn-credentials/{credentialId}][%d] deleteApiUsersIdWebauthnCredentialsCredentialIdNoContent", 204)
}

func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault creates a DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault with default headers values
func NewDeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault(code int) *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault {
	return &DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault{
		_statusCode: code,
	}
}

// DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault describes a response with status code -1, with default header values.
//
// Error
type DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this delete API users ID webauthn credentials credential ID default response has a 2xx status code
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete API users ID webauthn credentials credential ID default response has a 3xx status code
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete API users ID webauthn credentials credential ID default response has a 4xx status code
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete API users ID webauthn credentials credential ID default response has a 5xx status code
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete API users ID webauthn credentials credential ID default response a status code equal to that given
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete API users ID webauthn credentials credential ID default response
func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/users/{id}/webauthn-credentials/{credentialId}][%d] DeleteAPIUsersIDWebauthnCredentialsCredentialID default %s", o._statusCode, payload)
}

func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/users/{id}/webauthn-credentials/{credentialId}][%d] DeleteAPIUsersIDWebauthnCredentialsCredentialID default %s", o._statusCode, payload)
}

func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *DeleteAPIUsersIDWebauthnCredentialsCredentialIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
