// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIUsersMeProfilePictureParams creates a new DeleteAPIUsersMeProfilePictureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIUsersMeProfilePictureParams() *DeleteAPIUsersMeProfilePictureParams {
	return &DeleteAPIUsersMeProfilePictureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIUsersMeProfilePictureParamsWithTimeout creates a new DeleteAPIUsersMeProfilePictureParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIUsersMeProfilePictureParamsWithTimeout(timeout time.Duration) *DeleteAPIUsersMeProfilePictureParams {
	return &DeleteAPIUsersMeProfilePictureParams{
		timeout: timeout,
	}
}

// NewDeleteAPIUsersMeProfilePictureParamsWithContext creates a new DeleteAPIUsersMeProfilePictureParams object
// with the ability to set a context for a request.
func NewDeleteAPIUsersMeProfilePictureParamsWithContext(ctx context.Context) *DeleteAPIUsersMeProfilePictureParams {
	return &DeleteAPIUsersMeProfilePictureParams{
		Context: ctx,
	}
}

// NewDeleteAPIUsersMeProfilePictureParamsWithHTTPClient creates a new DeleteAPIUsersMeProfilePictureParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIUsersMeProfilePictureParamsWithHTTPClient(client *http.Client) *DeleteAPIUsersMeProfilePictureParams {
	return &DeleteAPIUsersMeProfilePictureParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIUsersMeProfilePictureParams contains all the parameters to send to the API endpoint

	for the delete API users me profile picture operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIUsersMeProfilePictureParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API users me profile picture params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIUsersMeProfilePictureParams) WithDefaults() *DeleteAPIUsersMeProfilePictureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API users me profile picture params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIUsersMeProfilePictureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API users me profile picture params
func (o *DeleteAPIUsersMeProfilePictureParams) WithTimeout(timeout time.Duration) *DeleteAPIUsersMeProfilePictureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API users me profile picture params
func (o *DeleteAPIUsersMeProfilePictureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API users me profile picture params
func (o *DeleteAPIUsersMeProfilePictureParams) WithContext(ctx context.Context) *DeleteAPIUsersMeProfilePictureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API users me profile picture params
func (o *DeleteAPIUsersMeProfilePictureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API users me profile picture params
func (o *DeleteAPIUsersMeProfilePictureParams) WithHTTPClient(client *http.Client) *DeleteAPIUsersMeProfilePictureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API users me profile picture params
func (o *DeleteAPIUsersMeProfilePictureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIUsersMeProfilePictureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
