// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIUsersIDProfilePicturePngReader is a Reader for the GetAPIUsersIDProfilePicturePng structure.
type GetAPIUsersIDProfilePicturePngReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIUsersIDProfilePicturePngReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIUsersIDProfilePicturePngOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/users/{id}/profile-picture.png] GetAPIUsersIDProfilePicturePng", response, response.Code())
	}
}

// NewGetAPIUsersIDProfilePicturePngOK creates a GetAPIUsersIDProfilePicturePngOK with default headers values
func NewGetAPIUsersIDProfilePicturePngOK(writer io.Writer) *GetAPIUsersIDProfilePicturePngOK {
	return &GetAPIUsersIDProfilePicturePngOK{

		Payload: writer,
	}
}

/*
GetAPIUsersIDProfilePicturePngOK describes a response with status code 200, with default header values.

PNG image
*/
type GetAPIUsersIDProfilePicturePngOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get Api users Id profile picture png o k response has a 2xx status code
func (o *GetAPIUsersIDProfilePicturePngOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api users Id profile picture png o k response has a 3xx status code
func (o *GetAPIUsersIDProfilePicturePngOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api users Id profile picture png o k response has a 4xx status code
func (o *GetAPIUsersIDProfilePicturePngOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api users Id profile picture png o k response has a 5xx status code
func (o *GetAPIUsersIDProfilePicturePngOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api users Id profile picture png o k response a status code equal to that given
func (o *GetAPIUsersIDProfilePicturePngOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api users Id profile picture png o k response
func (o *GetAPIUsersIDProfilePicturePngOK) Code() int {
	return 200
}

func (o *GetAPIUsersIDProfilePicturePngOK) Error() string {
	return fmt.Sprintf("[GET /api/users/{id}/profile-picture.png][%d] getApiUsersIdProfilePicturePngOK", 200)
}

func (o *GetAPIUsersIDProfilePicturePngOK) String() string {
	return fmt.Sprintf("[GET /api/users/{id}/profile-picture.png][%d] getApiUsersIdProfilePicturePngOK", 200)
}

func (o *GetAPIUsersIDProfilePicturePngOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetAPIUsersIDProfilePicturePngOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
