// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIUsersIDReader is a Reader for the GetAPIUsersID structure.
type GetAPIUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIUsersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIUsersIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIUsersIDOK creates a GetAPIUsersIDOK with default headers values
func NewGetAPIUsersIDOK() *GetAPIUsersIDOK {
	return &GetAPIUsersIDOK{}
}

// GetAPIUsersIDOK describes a response with status code 200, with default header values.
//
// OK
type GetAPIUsersIDOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoUserDto
}

// IsSuccess returns true when this get Api users Id o k response has a 2xx status code
func (o *GetAPIUsersIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api users Id o k response has a 3xx status code
func (o *GetAPIUsersIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api users Id o k response has a 4xx status code
func (o *GetAPIUsersIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api users Id o k response has a 5xx status code
func (o *GetAPIUsersIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api users Id o k response a status code equal to that given
func (o *GetAPIUsersIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api users Id o k response
func (o *GetAPIUsersIDOK) Code() int {
	return 200
}

func (o *GetAPIUsersIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/users/{id}][%d] getApiUsersIdOK %s", 200, payload)
}

func (o *GetAPIUsersIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/users/{id}][%d] getApiUsersIdOK %s", 200, payload)
}

func (o *GetAPIUsersIDOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoUserDto {
	return o.Payload
}

func (o *GetAPIUsersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoUserDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIUsersIDDefault creates a GetAPIUsersIDDefault with default headers values
func NewGetAPIUsersIDDefault(code int) *GetAPIUsersIDDefault {
	return &GetAPIUsersIDDefault{
		_statusCode: code,
	}
}

// GetAPIUsersIDDefault describes a response with status code -1, with default header values.
//
// Error
type GetAPIUsersIDDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this get API users ID default response has a 2xx status code
func (o *GetAPIUsersIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API users ID default response has a 3xx status code
func (o *GetAPIUsersIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API users ID default response has a 4xx status code
func (o *GetAPIUsersIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API users ID default response has a 5xx status code
func (o *GetAPIUsersIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API users ID default response a status code equal to that given
func (o *GetAPIUsersIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get API users ID default response
func (o *GetAPIUsersIDDefault) Code() int {
	return o._statusCode
}

func (o *GetAPIUsersIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/users/{id}][%d] GetAPIUsersID default %s", o._statusCode, payload)
}

func (o *GetAPIUsersIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/users/{id}][%d] GetAPIUsersID default %s", o._statusCode, payload)
}

func (o *GetAPIUsersIDDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *GetAPIUsersIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
