// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/models"
)

// NewPostAPISignupParams creates a new PostAPISignupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPISignupParams() *PostAPISignupParams {
	return &PostAPISignupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPISignupParamsWithTimeout creates a new PostAPISignupParams object
// with the ability to set a timeout on a request.
func NewPostAPISignupParamsWithTimeout(timeout time.Duration) *PostAPISignupParams {
	return &PostAPISignupParams{
		timeout: timeout,
	}
}

// NewPostAPISignupParamsWithContext creates a new PostAPISignupParams object
// with the ability to set a context for a request.
func NewPostAPISignupParamsWithContext(ctx context.Context) *PostAPISignupParams {
	return &PostAPISignupParams{
		Context: ctx,
	}
}

// NewPostAPISignupParamsWithHTTPClient creates a new PostAPISignupParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPISignupParamsWithHTTPClient(client *http.Client) *PostAPISignupParams {
	return &PostAPISignupParams{
		HTTPClient: client,
	}
}

/*
PostAPISignupParams contains all the parameters to send to the API endpoint

	for the post API signup operation.

	Typically these are written to a http.Request.
*/
type PostAPISignupParams struct {

	/* User.

	   User information
	*/
	User *models.GithubComPocketIDPocketIDBackendInternalDtoSignUpDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API signup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPISignupParams) WithDefaults() *PostAPISignupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API signup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPISignupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API signup params
func (o *PostAPISignupParams) WithTimeout(timeout time.Duration) *PostAPISignupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API signup params
func (o *PostAPISignupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API signup params
func (o *PostAPISignupParams) WithContext(ctx context.Context) *PostAPISignupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API signup params
func (o *PostAPISignupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API signup params
func (o *PostAPISignupParams) WithHTTPClient(client *http.Client) *PostAPISignupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API signup params
func (o *PostAPISignupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the post API signup params
func (o *PostAPISignupParams) WithUser(user *models.GithubComPocketIDPocketIDBackendInternalDtoSignUpDto) *PostAPISignupParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the post API signup params
func (o *PostAPISignupParams) SetUser(user *models.GithubComPocketIDPocketIDBackendInternalDtoSignUpDto) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPISignupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.User != nil {
		if err := r.SetBodyParam(o.User); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
