// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"context"
	"net/http"
	"time"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIOneTimeAccessEmailParams creates a new PostAPIOneTimeAccessEmailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIOneTimeAccessEmailParams() *PostAPIOneTimeAccessEmailParams {
	return NewPostAPIOneTimeAccessEmailParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAPIOneTimeAccessEmailParamsWithTimeout creates a new PostAPIOneTimeAccessEmailParams object
// with the ability to set a timeout on a request.
func NewPostAPIOneTimeAccessEmailParamsWithTimeout(timeout time.Duration) *PostAPIOneTimeAccessEmailParams {
	return &PostAPIOneTimeAccessEmailParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAPIOneTimeAccessEmailParamsWithContext creates a new PostAPIOneTimeAccessEmailParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIOneTimeAccessEmailParams].
func NewPostAPIOneTimeAccessEmailParamsWithContext(ctx context.Context) *PostAPIOneTimeAccessEmailParams {
	return &PostAPIOneTimeAccessEmailParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAPIOneTimeAccessEmailParamsWithHTTPClient creates a new PostAPIOneTimeAccessEmailParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIOneTimeAccessEmailParamsWithHTTPClient(client *http.Client) *PostAPIOneTimeAccessEmailParams {
	return &PostAPIOneTimeAccessEmailParams{
		HTTPClient: client,
	}
}

/*
PostAPIOneTimeAccessEmailParams contains all the parameters to send to the API endpoint

	for the post API one time access email operation.

	Typically these are written to a http.Request.
*/
type PostAPIOneTimeAccessEmailParams struct {

	/* Body.

	   Email request information
	*/
	Body *models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsUnauthenticatedUserDto

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post API one time access email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOneTimeAccessEmailParams) WithDefaults() *PostAPIOneTimeAccessEmailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API one time access email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOneTimeAccessEmailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API one time access email params.
func (o *PostAPIOneTimeAccessEmailParams) WithTimeout(timeout time.Duration) *PostAPIOneTimeAccessEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API one time access email params.
func (o *PostAPIOneTimeAccessEmailParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post API one time access email params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIOneTimeAccessEmailParams].
func (o *PostAPIOneTimeAccessEmailParams) WithContext(ctx context.Context) *PostAPIOneTimeAccessEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API one time access email params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIOneTimeAccessEmailParams].
func (o *PostAPIOneTimeAccessEmailParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post API one time access email params.
func (o *PostAPIOneTimeAccessEmailParams) WithHTTPClient(client *http.Client) *PostAPIOneTimeAccessEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API one time access email params.
func (o *PostAPIOneTimeAccessEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API one time access email params.
func (o *PostAPIOneTimeAccessEmailParams) WithBody(body *models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsUnauthenticatedUserDto) *PostAPIOneTimeAccessEmailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API one time access email params.
func (o *PostAPIOneTimeAccessEmailParams) SetBody(body *models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsUnauthenticatedUserDto) {
	o.Body = body
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAPIOneTimeAccessEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
