// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"context"
	"net/http"
	"time"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIUsersIDOneTimeAccessEmailParams creates a new PostAPIUsersIDOneTimeAccessEmailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIUsersIDOneTimeAccessEmailParams() *PostAPIUsersIDOneTimeAccessEmailParams {
	return NewPostAPIUsersIDOneTimeAccessEmailParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAPIUsersIDOneTimeAccessEmailParamsWithTimeout creates a new PostAPIUsersIDOneTimeAccessEmailParams object
// with the ability to set a timeout on a request.
func NewPostAPIUsersIDOneTimeAccessEmailParamsWithTimeout(timeout time.Duration) *PostAPIUsersIDOneTimeAccessEmailParams {
	return &PostAPIUsersIDOneTimeAccessEmailParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAPIUsersIDOneTimeAccessEmailParamsWithContext creates a new PostAPIUsersIDOneTimeAccessEmailParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIUsersIDOneTimeAccessEmailParams].
func NewPostAPIUsersIDOneTimeAccessEmailParamsWithContext(ctx context.Context) *PostAPIUsersIDOneTimeAccessEmailParams {
	return &PostAPIUsersIDOneTimeAccessEmailParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAPIUsersIDOneTimeAccessEmailParamsWithHTTPClient creates a new PostAPIUsersIDOneTimeAccessEmailParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIUsersIDOneTimeAccessEmailParamsWithHTTPClient(client *http.Client) *PostAPIUsersIDOneTimeAccessEmailParams {
	return &PostAPIUsersIDOneTimeAccessEmailParams{
		HTTPClient: client,
	}
}

/*
PostAPIUsersIDOneTimeAccessEmailParams contains all the parameters to send to the API endpoint

	for the post API users ID one time access email operation.

	Typically these are written to a http.Request.
*/
type PostAPIUsersIDOneTimeAccessEmailParams struct {

	/* Body.

	   Email request options
	*/
	Body *models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto

	/* ID.

	   User ID
	*/
	ID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post API users ID one time access email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) WithDefaults() *PostAPIUsersIDOneTimeAccessEmailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API users ID one time access email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API users ID one time access email params.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) WithTimeout(timeout time.Duration) *PostAPIUsersIDOneTimeAccessEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API users ID one time access email params.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post API users ID one time access email params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIUsersIDOneTimeAccessEmailParams].
func (o *PostAPIUsersIDOneTimeAccessEmailParams) WithContext(ctx context.Context) *PostAPIUsersIDOneTimeAccessEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API users ID one time access email params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIUsersIDOneTimeAccessEmailParams].
func (o *PostAPIUsersIDOneTimeAccessEmailParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post API users ID one time access email params.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) WithHTTPClient(client *http.Client) *PostAPIUsersIDOneTimeAccessEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API users ID one time access email params.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API users ID one time access email params.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) WithBody(body *models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto) *PostAPIUsersIDOneTimeAccessEmailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API users ID one time access email params.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) SetBody(body *models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto) {
	o.Body = body
}

// WithID adds the id to the post API users ID one time access email params.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) WithID(id string) *PostAPIUsersIDOneTimeAccessEmailParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post API users ID one time access email params.
func (o *PostAPIUsersIDOneTimeAccessEmailParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAPIUsersIDOneTimeAccessEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
