// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"context"
	"net/http"
	"time"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIUsersIDOneTimeAccessTokenParams creates a new PostAPIUsersIDOneTimeAccessTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIUsersIDOneTimeAccessTokenParams() *PostAPIUsersIDOneTimeAccessTokenParams {
	return NewPostAPIUsersIDOneTimeAccessTokenParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAPIUsersIDOneTimeAccessTokenParamsWithTimeout creates a new PostAPIUsersIDOneTimeAccessTokenParams object
// with the ability to set a timeout on a request.
func NewPostAPIUsersIDOneTimeAccessTokenParamsWithTimeout(timeout time.Duration) *PostAPIUsersIDOneTimeAccessTokenParams {
	return &PostAPIUsersIDOneTimeAccessTokenParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAPIUsersIDOneTimeAccessTokenParamsWithContext creates a new PostAPIUsersIDOneTimeAccessTokenParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIUsersIDOneTimeAccessTokenParams].
func NewPostAPIUsersIDOneTimeAccessTokenParamsWithContext(ctx context.Context) *PostAPIUsersIDOneTimeAccessTokenParams {
	return &PostAPIUsersIDOneTimeAccessTokenParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAPIUsersIDOneTimeAccessTokenParamsWithHTTPClient creates a new PostAPIUsersIDOneTimeAccessTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIUsersIDOneTimeAccessTokenParamsWithHTTPClient(client *http.Client) *PostAPIUsersIDOneTimeAccessTokenParams {
	return &PostAPIUsersIDOneTimeAccessTokenParams{
		HTTPClient: client,
	}
}

/*
PostAPIUsersIDOneTimeAccessTokenParams contains all the parameters to send to the API endpoint

	for the post API users ID one time access token operation.

	Typically these are written to a http.Request.
*/
type PostAPIUsersIDOneTimeAccessTokenParams struct {

	// Body.
	//
	// Token options
	Body models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessTokenCreateDto

	// ID.
	//
	// User ID
	ID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post API users ID one time access token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) WithDefaults() *PostAPIUsersIDOneTimeAccessTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API users ID one time access token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API users ID one time access token params.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) WithTimeout(timeout time.Duration) *PostAPIUsersIDOneTimeAccessTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API users ID one time access token params.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post API users ID one time access token params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIUsersIDOneTimeAccessTokenParams].
func (o *PostAPIUsersIDOneTimeAccessTokenParams) WithContext(ctx context.Context) *PostAPIUsersIDOneTimeAccessTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API users ID one time access token params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIUsersIDOneTimeAccessTokenParams].
func (o *PostAPIUsersIDOneTimeAccessTokenParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post API users ID one time access token params.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) WithHTTPClient(client *http.Client) *PostAPIUsersIDOneTimeAccessTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API users ID one time access token params.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API users ID one time access token params.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) WithBody(body models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessTokenCreateDto) *PostAPIUsersIDOneTimeAccessTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API users ID one time access token params.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) SetBody(body models.GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessTokenCreateDto) {
	o.Body = body
}

// WithID adds the id to the post API users ID one time access token params.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) WithID(id string) *PostAPIUsersIDOneTimeAccessTokenParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post API users ID one time access token params.
func (o *PostAPIUsersIDOneTimeAccessTokenParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAPIUsersIDOneTimeAccessTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
