// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/models"
)

// NewPostAPISignupTokensParams creates a new PostAPISignupTokensParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPISignupTokensParams() *PostAPISignupTokensParams {
	return &PostAPISignupTokensParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPISignupTokensParamsWithTimeout creates a new PostAPISignupTokensParams object
// with the ability to set a timeout on a request.
func NewPostAPISignupTokensParamsWithTimeout(timeout time.Duration) *PostAPISignupTokensParams {
	return &PostAPISignupTokensParams{
		timeout: timeout,
	}
}

// NewPostAPISignupTokensParamsWithContext creates a new PostAPISignupTokensParams object
// with the ability to set a context for a request.
func NewPostAPISignupTokensParamsWithContext(ctx context.Context) *PostAPISignupTokensParams {
	return &PostAPISignupTokensParams{
		Context: ctx,
	}
}

// NewPostAPISignupTokensParamsWithHTTPClient creates a new PostAPISignupTokensParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPISignupTokensParamsWithHTTPClient(client *http.Client) *PostAPISignupTokensParams {
	return &PostAPISignupTokensParams{
		HTTPClient: client,
	}
}

/*
PostAPISignupTokensParams contains all the parameters to send to the API endpoint

	for the post API signup tokens operation.

	Typically these are written to a http.Request.
*/
type PostAPISignupTokensParams struct {

	/* Token.

	   Signup token information
	*/
	Token *models.GithubComPocketIDPocketIDBackendInternalDtoSignupTokenCreateDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API signup tokens params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPISignupTokensParams) WithDefaults() *PostAPISignupTokensParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API signup tokens params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPISignupTokensParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API signup tokens params
func (o *PostAPISignupTokensParams) WithTimeout(timeout time.Duration) *PostAPISignupTokensParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API signup tokens params
func (o *PostAPISignupTokensParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API signup tokens params
func (o *PostAPISignupTokensParams) WithContext(ctx context.Context) *PostAPISignupTokensParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API signup tokens params
func (o *PostAPISignupTokensParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API signup tokens params
func (o *PostAPISignupTokensParams) WithHTTPClient(client *http.Client) *PostAPISignupTokensParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API signup tokens params
func (o *PostAPISignupTokensParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the post API signup tokens params
func (o *PostAPISignupTokensParams) WithToken(token *models.GithubComPocketIDPocketIDBackendInternalDtoSignupTokenCreateDto) *PostAPISignupTokensParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the post API signup tokens params
func (o *PostAPISignupTokensParams) SetToken(token *models.GithubComPocketIDPocketIDBackendInternalDtoSignupTokenCreateDto) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPISignupTokensParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Token != nil {
		if err := r.SetBodyParam(o.Token); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
