// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIUsersIDProfilePictureParams creates a new PutAPIUsersIDProfilePictureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIUsersIDProfilePictureParams() *PutAPIUsersIDProfilePictureParams {
	return &PutAPIUsersIDProfilePictureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIUsersIDProfilePictureParamsWithTimeout creates a new PutAPIUsersIDProfilePictureParams object
// with the ability to set a timeout on a request.
func NewPutAPIUsersIDProfilePictureParamsWithTimeout(timeout time.Duration) *PutAPIUsersIDProfilePictureParams {
	return &PutAPIUsersIDProfilePictureParams{
		timeout: timeout,
	}
}

// NewPutAPIUsersIDProfilePictureParamsWithContext creates a new PutAPIUsersIDProfilePictureParams object
// with the ability to set a context for a request.
func NewPutAPIUsersIDProfilePictureParamsWithContext(ctx context.Context) *PutAPIUsersIDProfilePictureParams {
	return &PutAPIUsersIDProfilePictureParams{
		Context: ctx,
	}
}

// NewPutAPIUsersIDProfilePictureParamsWithHTTPClient creates a new PutAPIUsersIDProfilePictureParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIUsersIDProfilePictureParamsWithHTTPClient(client *http.Client) *PutAPIUsersIDProfilePictureParams {
	return &PutAPIUsersIDProfilePictureParams{
		HTTPClient: client,
	}
}

/*
PutAPIUsersIDProfilePictureParams contains all the parameters to send to the API endpoint

	for the put API users ID profile picture operation.

	Typically these are written to a http.Request.
*/
type PutAPIUsersIDProfilePictureParams struct {

	/* File.

	   Profile picture image file (PNG, JPG, or JPEG)
	*/
	File runtime.NamedReadCloser

	/* ID.

	   User ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API users ID profile picture params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUsersIDProfilePictureParams) WithDefaults() *PutAPIUsersIDProfilePictureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API users ID profile picture params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUsersIDProfilePictureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) WithTimeout(timeout time.Duration) *PutAPIUsersIDProfilePictureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) WithContext(ctx context.Context) *PutAPIUsersIDProfilePictureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) WithHTTPClient(client *http.Client) *PutAPIUsersIDProfilePictureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) WithFile(file runtime.NamedReadCloser) *PutAPIUsersIDProfilePictureParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WithID adds the id to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) WithID(id string) *PutAPIUsersIDProfilePictureParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API users ID profile picture params
func (o *PutAPIUsersIDProfilePictureParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIUsersIDProfilePictureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param file
	if err := r.SetFileParam("file", o.File); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
