// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"context"
	"net/http"
	"time"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIUsersMeParams creates a new PutAPIUsersMeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIUsersMeParams() *PutAPIUsersMeParams {
	return NewPutAPIUsersMeParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutAPIUsersMeParamsWithTimeout creates a new PutAPIUsersMeParams object
// with the ability to set a timeout on a request.
func NewPutAPIUsersMeParamsWithTimeout(timeout time.Duration) *PutAPIUsersMeParams {
	return &PutAPIUsersMeParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutAPIUsersMeParamsWithContext creates a new PutAPIUsersMeParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIUsersMeParams].
func NewPutAPIUsersMeParamsWithContext(ctx context.Context) *PutAPIUsersMeParams {
	return &PutAPIUsersMeParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutAPIUsersMeParamsWithHTTPClient creates a new PutAPIUsersMeParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIUsersMeParamsWithHTTPClient(client *http.Client) *PutAPIUsersMeParams {
	return &PutAPIUsersMeParams{
		HTTPClient: client,
	}
}

/*
PutAPIUsersMeParams contains all the parameters to send to the API endpoint

	for the put API users me operation.

	Typically these are written to a http.Request.
*/
type PutAPIUsersMeParams struct {

	// User.
	//
	// User information
	User *models.GithubComPocketIDPocketIDBackendInternalDtoUserCreateDto

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put API users me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUsersMeParams) WithDefaults() *PutAPIUsersMeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API users me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUsersMeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API users me params.
func (o *PutAPIUsersMeParams) WithTimeout(timeout time.Duration) *PutAPIUsersMeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API users me params.
func (o *PutAPIUsersMeParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put API users me params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIUsersMeParams].
func (o *PutAPIUsersMeParams) WithContext(ctx context.Context) *PutAPIUsersMeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API users me params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIUsersMeParams].
func (o *PutAPIUsersMeParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put API users me params.
func (o *PutAPIUsersMeParams) WithHTTPClient(client *http.Client) *PutAPIUsersMeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API users me params.
func (o *PutAPIUsersMeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the put API users me params.
func (o *PutAPIUsersMeParams) WithUser(user *models.GithubComPocketIDPocketIDBackendInternalDtoUserCreateDto) *PutAPIUsersMeParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the put API users me params.
func (o *PutAPIUsersMeParams) SetUser(user *models.GithubComPocketIDPocketIDBackendInternalDtoUserCreateDto) {
	o.User = user
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutAPIUsersMeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.User != nil {
		if err := r.SetBodyParam(o.User); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
