// Code generated by go-swagger; DO NOT EDIT.

package application_images

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIApplicationImagesBackgroundReader is a Reader for the DeleteAPIApplicationImagesBackground structure.
type DeleteAPIApplicationImagesBackgroundReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIApplicationImagesBackgroundReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIApplicationImagesBackgroundNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/application-images/background] DeleteAPIApplicationImagesBackground", response, response.Code())
	}
}

// NewDeleteAPIApplicationImagesBackgroundNoContent creates a DeleteAPIApplicationImagesBackgroundNoContent with default headers values
func NewDeleteAPIApplicationImagesBackgroundNoContent() *DeleteAPIApplicationImagesBackgroundNoContent {
	return &DeleteAPIApplicationImagesBackgroundNoContent{}
}

/*
DeleteAPIApplicationImagesBackgroundNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteAPIApplicationImagesBackgroundNoContent struct {
}

// IsSuccess returns true when this delete Api application images background no content response has a 2xx status code
func (o *DeleteAPIApplicationImagesBackgroundNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api application images background no content response has a 3xx status code
func (o *DeleteAPIApplicationImagesBackgroundNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api application images background no content response has a 4xx status code
func (o *DeleteAPIApplicationImagesBackgroundNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api application images background no content response has a 5xx status code
func (o *DeleteAPIApplicationImagesBackgroundNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api application images background no content response a status code equal to that given
func (o *DeleteAPIApplicationImagesBackgroundNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api application images background no content response
func (o *DeleteAPIApplicationImagesBackgroundNoContent) Code() int {
	return 204
}

func (o *DeleteAPIApplicationImagesBackgroundNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/application-images/background][%d] deleteApiApplicationImagesBackgroundNoContent", 204)
}

func (o *DeleteAPIApplicationImagesBackgroundNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/application-images/background][%d] deleteApiApplicationImagesBackgroundNoContent", 204)
}

func (o *DeleteAPIApplicationImagesBackgroundNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
