// Code generated by go-swagger; DO NOT EDIT.

package application_images

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteAPIApplicationImagesLogoParams creates a new DeleteAPIApplicationImagesLogoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIApplicationImagesLogoParams() *DeleteAPIApplicationImagesLogoParams {
	return NewDeleteAPIApplicationImagesLogoParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteAPIApplicationImagesLogoParamsWithTimeout creates a new DeleteAPIApplicationImagesLogoParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIApplicationImagesLogoParamsWithTimeout(timeout time.Duration) *DeleteAPIApplicationImagesLogoParams {
	return &DeleteAPIApplicationImagesLogoParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteAPIApplicationImagesLogoParamsWithContext creates a new DeleteAPIApplicationImagesLogoParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIApplicationImagesLogoParams].
func NewDeleteAPIApplicationImagesLogoParamsWithContext(ctx context.Context) *DeleteAPIApplicationImagesLogoParams {
	return &DeleteAPIApplicationImagesLogoParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteAPIApplicationImagesLogoParamsWithHTTPClient creates a new DeleteAPIApplicationImagesLogoParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIApplicationImagesLogoParamsWithHTTPClient(client *http.Client) *DeleteAPIApplicationImagesLogoParams {
	return &DeleteAPIApplicationImagesLogoParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIApplicationImagesLogoParams contains all the parameters to send to the API endpoint

	for the delete API application images logo operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIApplicationImagesLogoParams struct {

	// Light.
	//
	// Light mode logo (true) or dark mode logo (false)
	Light *bool

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete API application images logo params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIApplicationImagesLogoParams) WithDefaults() *DeleteAPIApplicationImagesLogoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API application images logo params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIApplicationImagesLogoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API application images logo params.
func (o *DeleteAPIApplicationImagesLogoParams) WithTimeout(timeout time.Duration) *DeleteAPIApplicationImagesLogoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API application images logo params.
func (o *DeleteAPIApplicationImagesLogoParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete API application images logo params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIApplicationImagesLogoParams].
func (o *DeleteAPIApplicationImagesLogoParams) WithContext(ctx context.Context) *DeleteAPIApplicationImagesLogoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API application images logo params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIApplicationImagesLogoParams].
func (o *DeleteAPIApplicationImagesLogoParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API application images logo params.
func (o *DeleteAPIApplicationImagesLogoParams) WithHTTPClient(client *http.Client) *DeleteAPIApplicationImagesLogoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API application images logo params.
func (o *DeleteAPIApplicationImagesLogoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLight adds the light to the delete API application images logo params.
func (o *DeleteAPIApplicationImagesLogoParams) WithLight(light *bool) *DeleteAPIApplicationImagesLogoParams {
	o.SetLight(light)
	return o
}

// SetLight adds the light to the delete API application images logo params.
func (o *DeleteAPIApplicationImagesLogoParams) SetLight(light *bool) {
	o.Light = light
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteAPIApplicationImagesLogoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Light != nil {

		// query param light
		var qrLight bool

		if o.Light != nil {
			qrLight = *o.Light
		}
		qLight := conv.FormatBool(qrLight)
		if qLight != "" {

			if err := r.SetQueryParam("light", qLight); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
