// Code generated by go-swagger; DO NOT EDIT.

package application_images

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIApplicationImagesDefaultProfilePictureParams creates a new DeleteAPIApplicationImagesDefaultProfilePictureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIApplicationImagesDefaultProfilePictureParams() *DeleteAPIApplicationImagesDefaultProfilePictureParams {
	return NewDeleteAPIApplicationImagesDefaultProfilePictureParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteAPIApplicationImagesDefaultProfilePictureParamsWithTimeout creates a new DeleteAPIApplicationImagesDefaultProfilePictureParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIApplicationImagesDefaultProfilePictureParamsWithTimeout(timeout time.Duration) *DeleteAPIApplicationImagesDefaultProfilePictureParams {
	return &DeleteAPIApplicationImagesDefaultProfilePictureParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteAPIApplicationImagesDefaultProfilePictureParamsWithContext creates a new DeleteAPIApplicationImagesDefaultProfilePictureParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIApplicationImagesDefaultProfilePictureParams].
func NewDeleteAPIApplicationImagesDefaultProfilePictureParamsWithContext(ctx context.Context) *DeleteAPIApplicationImagesDefaultProfilePictureParams {
	return &DeleteAPIApplicationImagesDefaultProfilePictureParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteAPIApplicationImagesDefaultProfilePictureParamsWithHTTPClient creates a new DeleteAPIApplicationImagesDefaultProfilePictureParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIApplicationImagesDefaultProfilePictureParamsWithHTTPClient(client *http.Client) *DeleteAPIApplicationImagesDefaultProfilePictureParams {
	return &DeleteAPIApplicationImagesDefaultProfilePictureParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIApplicationImagesDefaultProfilePictureParams contains all the parameters to send to the API endpoint

	for the delete API application images default profile picture operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIApplicationImagesDefaultProfilePictureParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete API application images default profile picture params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) WithDefaults() *DeleteAPIApplicationImagesDefaultProfilePictureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API application images default profile picture params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API application images default profile picture params.
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) WithTimeout(timeout time.Duration) *DeleteAPIApplicationImagesDefaultProfilePictureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API application images default profile picture params.
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete API application images default profile picture params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIApplicationImagesDefaultProfilePictureParams].
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) WithContext(ctx context.Context) *DeleteAPIApplicationImagesDefaultProfilePictureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API application images default profile picture params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIApplicationImagesDefaultProfilePictureParams].
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API application images default profile picture params.
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) WithHTTPClient(client *http.Client) *DeleteAPIApplicationImagesDefaultProfilePictureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API application images default profile picture params.
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteAPIApplicationImagesDefaultProfilePictureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
