// Code generated by go-swagger; DO NOT EDIT.

package application_images

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIApplicationImagesFaviconReader is a Reader for the GetAPIApplicationImagesFavicon structure.
type GetAPIApplicationImagesFaviconReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIApplicationImagesFaviconReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIApplicationImagesFaviconOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIApplicationImagesFaviconDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIApplicationImagesFaviconOK creates a GetAPIApplicationImagesFaviconOK with default headers values
func NewGetAPIApplicationImagesFaviconOK(writer io.Writer) *GetAPIApplicationImagesFaviconOK {
	return &GetAPIApplicationImagesFaviconOK{

		Payload: writer,
	}
}

// GetAPIApplicationImagesFaviconOK describes a response with status code 200, with default header values.
//
// Favicon image
type GetAPIApplicationImagesFaviconOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get Api application images favicon o k response has a 2xx status code
func (o *GetAPIApplicationImagesFaviconOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api application images favicon o k response has a 3xx status code
func (o *GetAPIApplicationImagesFaviconOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api application images favicon o k response has a 4xx status code
func (o *GetAPIApplicationImagesFaviconOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api application images favicon o k response has a 5xx status code
func (o *GetAPIApplicationImagesFaviconOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api application images favicon o k response a status code equal to that given
func (o *GetAPIApplicationImagesFaviconOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api application images favicon o k response
func (o *GetAPIApplicationImagesFaviconOK) Code() int {
	return 200
}

func (o *GetAPIApplicationImagesFaviconOK) Error() string {
	return fmt.Sprintf("[GET /api/application-images/favicon][%d] getApiApplicationImagesFaviconOK", 200)
}

func (o *GetAPIApplicationImagesFaviconOK) String() string {
	return fmt.Sprintf("[GET /api/application-images/favicon][%d] getApiApplicationImagesFaviconOK", 200)
}

func (o *GetAPIApplicationImagesFaviconOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetAPIApplicationImagesFaviconOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIApplicationImagesFaviconDefault creates a GetAPIApplicationImagesFaviconDefault with default headers values
func NewGetAPIApplicationImagesFaviconDefault(code int) *GetAPIApplicationImagesFaviconDefault {
	return &GetAPIApplicationImagesFaviconDefault{
		_statusCode: code,
	}
}

// GetAPIApplicationImagesFaviconDefault describes a response with status code -1, with default header values.
//
// Error
type GetAPIApplicationImagesFaviconDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this get API application images favicon default response has a 2xx status code
func (o *GetAPIApplicationImagesFaviconDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API application images favicon default response has a 3xx status code
func (o *GetAPIApplicationImagesFaviconDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API application images favicon default response has a 4xx status code
func (o *GetAPIApplicationImagesFaviconDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API application images favicon default response has a 5xx status code
func (o *GetAPIApplicationImagesFaviconDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API application images favicon default response a status code equal to that given
func (o *GetAPIApplicationImagesFaviconDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get API application images favicon default response
func (o *GetAPIApplicationImagesFaviconDefault) Code() int {
	return o._statusCode
}

func (o *GetAPIApplicationImagesFaviconDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-images/favicon][%d] GetAPIApplicationImagesFavicon default %s", o._statusCode, payload)
}

func (o *GetAPIApplicationImagesFaviconDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/application-images/favicon][%d] GetAPIApplicationImagesFavicon default %s", o._statusCode, payload)
}

func (o *GetAPIApplicationImagesFaviconDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *GetAPIApplicationImagesFaviconDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
