// Code generated by go-swagger; DO NOT EDIT.

package application_images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIApplicationImagesDefaultProfilePictureReader is a Reader for the GetAPIApplicationImagesDefaultProfilePicture structure.
type GetAPIApplicationImagesDefaultProfilePictureReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIApplicationImagesDefaultProfilePictureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIApplicationImagesDefaultProfilePictureOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/application-images/default-profile-picture] GetAPIApplicationImagesDefaultProfilePicture", response, response.Code())
	}
}

// NewGetAPIApplicationImagesDefaultProfilePictureOK creates a GetAPIApplicationImagesDefaultProfilePictureOK with default headers values
func NewGetAPIApplicationImagesDefaultProfilePictureOK(writer io.Writer) *GetAPIApplicationImagesDefaultProfilePictureOK {
	return &GetAPIApplicationImagesDefaultProfilePictureOK{

		Payload: writer,
	}
}

/*
GetAPIApplicationImagesDefaultProfilePictureOK describes a response with status code 200, with default header values.

Default profile picture image
*/
type GetAPIApplicationImagesDefaultProfilePictureOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get Api application images default profile picture o k response has a 2xx status code
func (o *GetAPIApplicationImagesDefaultProfilePictureOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api application images default profile picture o k response has a 3xx status code
func (o *GetAPIApplicationImagesDefaultProfilePictureOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api application images default profile picture o k response has a 4xx status code
func (o *GetAPIApplicationImagesDefaultProfilePictureOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api application images default profile picture o k response has a 5xx status code
func (o *GetAPIApplicationImagesDefaultProfilePictureOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api application images default profile picture o k response a status code equal to that given
func (o *GetAPIApplicationImagesDefaultProfilePictureOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api application images default profile picture o k response
func (o *GetAPIApplicationImagesDefaultProfilePictureOK) Code() int {
	return 200
}

func (o *GetAPIApplicationImagesDefaultProfilePictureOK) Error() string {
	return fmt.Sprintf("[GET /api/application-images/default-profile-picture][%d] getApiApplicationImagesDefaultProfilePictureOK", 200)
}

func (o *GetAPIApplicationImagesDefaultProfilePictureOK) String() string {
	return fmt.Sprintf("[GET /api/application-images/default-profile-picture][%d] getApiApplicationImagesDefaultProfilePictureOK", 200)
}

func (o *GetAPIApplicationImagesDefaultProfilePictureOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetAPIApplicationImagesDefaultProfilePictureOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
