// Code generated by go-swagger; DO NOT EDIT.

package application_images

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutAPIApplicationImagesFaviconReader is a Reader for the PutAPIApplicationImagesFavicon structure.
type PutAPIApplicationImagesFaviconReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIApplicationImagesFaviconReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPutAPIApplicationImagesFaviconNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutAPIApplicationImagesFaviconDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutAPIApplicationImagesFaviconNoContent creates a PutAPIApplicationImagesFaviconNoContent with default headers values
func NewPutAPIApplicationImagesFaviconNoContent() *PutAPIApplicationImagesFaviconNoContent {
	return &PutAPIApplicationImagesFaviconNoContent{}
}

// PutAPIApplicationImagesFaviconNoContent describes a response with status code 204, with default header values.
//
// No Content
type PutAPIApplicationImagesFaviconNoContent struct {
}

// IsSuccess returns true when this put Api application images favicon no content response has a 2xx status code
func (o *PutAPIApplicationImagesFaviconNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api application images favicon no content response has a 3xx status code
func (o *PutAPIApplicationImagesFaviconNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api application images favicon no content response has a 4xx status code
func (o *PutAPIApplicationImagesFaviconNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api application images favicon no content response has a 5xx status code
func (o *PutAPIApplicationImagesFaviconNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api application images favicon no content response a status code equal to that given
func (o *PutAPIApplicationImagesFaviconNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the put Api application images favicon no content response
func (o *PutAPIApplicationImagesFaviconNoContent) Code() int {
	return 204
}

func (o *PutAPIApplicationImagesFaviconNoContent) Error() string {
	return fmt.Sprintf("[PUT /api/application-images/favicon][%d] putApiApplicationImagesFaviconNoContent", 204)
}

func (o *PutAPIApplicationImagesFaviconNoContent) String() string {
	return fmt.Sprintf("[PUT /api/application-images/favicon][%d] putApiApplicationImagesFaviconNoContent", 204)
}

func (o *PutAPIApplicationImagesFaviconNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIApplicationImagesFaviconDefault creates a PutAPIApplicationImagesFaviconDefault with default headers values
func NewPutAPIApplicationImagesFaviconDefault(code int) *PutAPIApplicationImagesFaviconDefault {
	return &PutAPIApplicationImagesFaviconDefault{
		_statusCode: code,
	}
}

// PutAPIApplicationImagesFaviconDefault describes a response with status code -1, with default header values.
//
// Error
type PutAPIApplicationImagesFaviconDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this put API application images favicon default response has a 2xx status code
func (o *PutAPIApplicationImagesFaviconDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put API application images favicon default response has a 3xx status code
func (o *PutAPIApplicationImagesFaviconDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put API application images favicon default response has a 4xx status code
func (o *PutAPIApplicationImagesFaviconDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put API application images favicon default response has a 5xx status code
func (o *PutAPIApplicationImagesFaviconDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put API application images favicon default response a status code equal to that given
func (o *PutAPIApplicationImagesFaviconDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put API application images favicon default response
func (o *PutAPIApplicationImagesFaviconDefault) Code() int {
	return o._statusCode
}

func (o *PutAPIApplicationImagesFaviconDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/application-images/favicon][%d] PutAPIApplicationImagesFavicon default %s", o._statusCode, payload)
}

func (o *PutAPIApplicationImagesFaviconDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/application-images/favicon][%d] PutAPIApplicationImagesFavicon default %s", o._statusCode, payload)
}

func (o *PutAPIApplicationImagesFaviconDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *PutAPIApplicationImagesFaviconDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
