// Code generated by go-swagger; DO NOT EDIT.

package application_images

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutAPIApplicationImagesEmailReader is a Reader for the PutAPIApplicationImagesEmail structure.
type PutAPIApplicationImagesEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIApplicationImagesEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPutAPIApplicationImagesEmailNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutAPIApplicationImagesEmailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutAPIApplicationImagesEmailNoContent creates a PutAPIApplicationImagesEmailNoContent with default headers values
func NewPutAPIApplicationImagesEmailNoContent() *PutAPIApplicationImagesEmailNoContent {
	return &PutAPIApplicationImagesEmailNoContent{}
}

// PutAPIApplicationImagesEmailNoContent describes a response with status code 204, with default header values.
//
// No Content
type PutAPIApplicationImagesEmailNoContent struct {
}

// IsSuccess returns true when this put Api application images email no content response has a 2xx status code
func (o *PutAPIApplicationImagesEmailNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api application images email no content response has a 3xx status code
func (o *PutAPIApplicationImagesEmailNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api application images email no content response has a 4xx status code
func (o *PutAPIApplicationImagesEmailNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api application images email no content response has a 5xx status code
func (o *PutAPIApplicationImagesEmailNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api application images email no content response a status code equal to that given
func (o *PutAPIApplicationImagesEmailNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the put Api application images email no content response
func (o *PutAPIApplicationImagesEmailNoContent) Code() int {
	return 204
}

func (o *PutAPIApplicationImagesEmailNoContent) Error() string {
	return fmt.Sprintf("[PUT /api/application-images/email][%d] putApiApplicationImagesEmailNoContent", 204)
}

func (o *PutAPIApplicationImagesEmailNoContent) String() string {
	return fmt.Sprintf("[PUT /api/application-images/email][%d] putApiApplicationImagesEmailNoContent", 204)
}

func (o *PutAPIApplicationImagesEmailNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIApplicationImagesEmailDefault creates a PutAPIApplicationImagesEmailDefault with default headers values
func NewPutAPIApplicationImagesEmailDefault(code int) *PutAPIApplicationImagesEmailDefault {
	return &PutAPIApplicationImagesEmailDefault{
		_statusCode: code,
	}
}

// PutAPIApplicationImagesEmailDefault describes a response with status code -1, with default header values.
//
// Error
type PutAPIApplicationImagesEmailDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this put API application images email default response has a 2xx status code
func (o *PutAPIApplicationImagesEmailDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put API application images email default response has a 3xx status code
func (o *PutAPIApplicationImagesEmailDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put API application images email default response has a 4xx status code
func (o *PutAPIApplicationImagesEmailDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put API application images email default response has a 5xx status code
func (o *PutAPIApplicationImagesEmailDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put API application images email default response a status code equal to that given
func (o *PutAPIApplicationImagesEmailDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put API application images email default response
func (o *PutAPIApplicationImagesEmailDefault) Code() int {
	return o._statusCode
}

func (o *PutAPIApplicationImagesEmailDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/application-images/email][%d] PutAPIApplicationImagesEmail default %s", o._statusCode, payload)
}

func (o *PutAPIApplicationImagesEmailDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/application-images/email][%d] PutAPIApplicationImagesEmail default %s", o._statusCode, payload)
}

func (o *PutAPIApplicationImagesEmailDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *PutAPIApplicationImagesEmailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
