// Code generated by go-swagger; DO NOT EDIT.

package application_images

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutAPIApplicationImagesDefaultProfilePictureReader is a Reader for the PutAPIApplicationImagesDefaultProfilePicture structure.
type PutAPIApplicationImagesDefaultProfilePictureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIApplicationImagesDefaultProfilePictureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPutAPIApplicationImagesDefaultProfilePictureNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutAPIApplicationImagesDefaultProfilePictureDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutAPIApplicationImagesDefaultProfilePictureNoContent creates a PutAPIApplicationImagesDefaultProfilePictureNoContent with default headers values
func NewPutAPIApplicationImagesDefaultProfilePictureNoContent() *PutAPIApplicationImagesDefaultProfilePictureNoContent {
	return &PutAPIApplicationImagesDefaultProfilePictureNoContent{}
}

// PutAPIApplicationImagesDefaultProfilePictureNoContent describes a response with status code 204, with default header values.
//
// No Content
type PutAPIApplicationImagesDefaultProfilePictureNoContent struct {
}

// IsSuccess returns true when this put Api application images default profile picture no content response has a 2xx status code
func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api application images default profile picture no content response has a 3xx status code
func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api application images default profile picture no content response has a 4xx status code
func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api application images default profile picture no content response has a 5xx status code
func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api application images default profile picture no content response a status code equal to that given
func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the put Api application images default profile picture no content response
func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) Code() int {
	return 204
}

func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) Error() string {
	return fmt.Sprintf("[PUT /api/application-images/default-profile-picture][%d] putApiApplicationImagesDefaultProfilePictureNoContent", 204)
}

func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) String() string {
	return fmt.Sprintf("[PUT /api/application-images/default-profile-picture][%d] putApiApplicationImagesDefaultProfilePictureNoContent", 204)
}

func (o *PutAPIApplicationImagesDefaultProfilePictureNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIApplicationImagesDefaultProfilePictureDefault creates a PutAPIApplicationImagesDefaultProfilePictureDefault with default headers values
func NewPutAPIApplicationImagesDefaultProfilePictureDefault(code int) *PutAPIApplicationImagesDefaultProfilePictureDefault {
	return &PutAPIApplicationImagesDefaultProfilePictureDefault{
		_statusCode: code,
	}
}

// PutAPIApplicationImagesDefaultProfilePictureDefault describes a response with status code -1, with default header values.
//
// Error
type PutAPIApplicationImagesDefaultProfilePictureDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this put API application images default profile picture default response has a 2xx status code
func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put API application images default profile picture default response has a 3xx status code
func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put API application images default profile picture default response has a 4xx status code
func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put API application images default profile picture default response has a 5xx status code
func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put API application images default profile picture default response a status code equal to that given
func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put API application images default profile picture default response
func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) Code() int {
	return o._statusCode
}

func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/application-images/default-profile-picture][%d] PutAPIApplicationImagesDefaultProfilePicture default %s", o._statusCode, payload)
}

func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/application-images/default-profile-picture][%d] PutAPIApplicationImagesDefaultProfilePicture default %s", o._statusCode, payload)
}

func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *PutAPIApplicationImagesDefaultProfilePictureDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
