// Code generated by go-swagger; DO NOT EDIT.

package storage

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIStorageSqliteWarningReader is a Reader for the GetAPIStorageSqliteWarning structure.
type GetAPIStorageSqliteWarningReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIStorageSqliteWarningReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIStorageSqliteWarningOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIStorageSqliteWarningDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIStorageSqliteWarningOK creates a GetAPIStorageSqliteWarningOK with default headers values
func NewGetAPIStorageSqliteWarningOK() *GetAPIStorageSqliteWarningOK {
	return &GetAPIStorageSqliteWarningOK{}
}

// GetAPIStorageSqliteWarningOK describes a response with status code 200, with default header values.
//
// SQLite storage warning state
type GetAPIStorageSqliteWarningOK struct {
	Payload map[string]bool
}

// IsSuccess returns true when this get Api storage sqlite warning o k response has a 2xx status code
func (o *GetAPIStorageSqliteWarningOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api storage sqlite warning o k response has a 3xx status code
func (o *GetAPIStorageSqliteWarningOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api storage sqlite warning o k response has a 4xx status code
func (o *GetAPIStorageSqliteWarningOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api storage sqlite warning o k response has a 5xx status code
func (o *GetAPIStorageSqliteWarningOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api storage sqlite warning o k response a status code equal to that given
func (o *GetAPIStorageSqliteWarningOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api storage sqlite warning o k response
func (o *GetAPIStorageSqliteWarningOK) Code() int {
	return 200
}

func (o *GetAPIStorageSqliteWarningOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/storage/sqlite-warning][%d] getApiStorageSqliteWarningOK %s", 200, payload)
}

func (o *GetAPIStorageSqliteWarningOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/storage/sqlite-warning][%d] getApiStorageSqliteWarningOK %s", 200, payload)
}

func (o *GetAPIStorageSqliteWarningOK) GetPayload() map[string]bool {
	return o.Payload
}

func (o *GetAPIStorageSqliteWarningOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIStorageSqliteWarningDefault creates a GetAPIStorageSqliteWarningDefault with default headers values
func NewGetAPIStorageSqliteWarningDefault(code int) *GetAPIStorageSqliteWarningDefault {
	return &GetAPIStorageSqliteWarningDefault{
		_statusCode: code,
	}
}

// GetAPIStorageSqliteWarningDefault describes a response with status code -1, with default header values.
//
// Error
type GetAPIStorageSqliteWarningDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this get API storage sqlite warning default response has a 2xx status code
func (o *GetAPIStorageSqliteWarningDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API storage sqlite warning default response has a 3xx status code
func (o *GetAPIStorageSqliteWarningDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API storage sqlite warning default response has a 4xx status code
func (o *GetAPIStorageSqliteWarningDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API storage sqlite warning default response has a 5xx status code
func (o *GetAPIStorageSqliteWarningDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API storage sqlite warning default response a status code equal to that given
func (o *GetAPIStorageSqliteWarningDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get API storage sqlite warning default response
func (o *GetAPIStorageSqliteWarningDefault) Code() int {
	return o._statusCode
}

func (o *GetAPIStorageSqliteWarningDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/storage/sqlite-warning][%d] GetAPIStorageSqliteWarning default %s", o._statusCode, payload)
}

func (o *GetAPIStorageSqliteWarningDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/storage/sqlite-warning][%d] GetAPIStorageSqliteWarning default %s", o._statusCode, payload)
}

func (o *GetAPIStorageSqliteWarningDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *GetAPIStorageSqliteWarningDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
