// Code generated by go-swagger; DO NOT EDIT.

package device_login

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPIDeviceLoginVerificationReader is a Reader for the PostAPIDeviceLoginVerification structure.
type PostAPIDeviceLoginVerificationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIDeviceLoginVerificationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIDeviceLoginVerificationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/device-login/verification] PostAPIDeviceLoginVerification", response, response.Code())
	}
}

// NewPostAPIDeviceLoginVerificationOK creates a PostAPIDeviceLoginVerificationOK with default headers values
func NewPostAPIDeviceLoginVerificationOK() *PostAPIDeviceLoginVerificationOK {
	return &PostAPIDeviceLoginVerificationOK{}
}

// PostAPIDeviceLoginVerificationOK describes a response with status code 200, with default header values.
//
// Device login request details
type PostAPIDeviceLoginVerificationOK struct {
	Payload *models.DeviceloginVerificationInfoDto
}

// IsSuccess returns true when this post Api device login verification o k response has a 2xx status code
func (o *PostAPIDeviceLoginVerificationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api device login verification o k response has a 3xx status code
func (o *PostAPIDeviceLoginVerificationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api device login verification o k response has a 4xx status code
func (o *PostAPIDeviceLoginVerificationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api device login verification o k response has a 5xx status code
func (o *PostAPIDeviceLoginVerificationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api device login verification o k response a status code equal to that given
func (o *PostAPIDeviceLoginVerificationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api device login verification o k response
func (o *PostAPIDeviceLoginVerificationOK) Code() int {
	return 200
}

func (o *PostAPIDeviceLoginVerificationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/device-login/verification][%d] postApiDeviceLoginVerificationOK %s", 200, payload)
}

func (o *PostAPIDeviceLoginVerificationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/device-login/verification][%d] postApiDeviceLoginVerificationOK %s", 200, payload)
}

func (o *PostAPIDeviceLoginVerificationOK) GetPayload() *models.DeviceloginVerificationInfoDto {
	return o.Payload
}

func (o *PostAPIDeviceLoginVerificationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceloginVerificationInfoDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
