// Code generated by go-swagger; DO NOT EDIT.

package device_login

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPIDeviceLoginRequestsIDExchangeReader is a Reader for the PostAPIDeviceLoginRequestsIDExchange structure.
type PostAPIDeviceLoginRequestsIDExchangeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIDeviceLoginRequestsIDExchangeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIDeviceLoginRequestsIDExchangeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewPostAPIDeviceLoginRequestsIDExchangeAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/device-login/requests/{id}/exchange] PostAPIDeviceLoginRequestsIDExchange", response, response.Code())
	}
}

// NewPostAPIDeviceLoginRequestsIDExchangeOK creates a PostAPIDeviceLoginRequestsIDExchangeOK with default headers values
func NewPostAPIDeviceLoginRequestsIDExchangeOK() *PostAPIDeviceLoginRequestsIDExchangeOK {
	return &PostAPIDeviceLoginRequestsIDExchangeOK{}
}

// PostAPIDeviceLoginRequestsIDExchangeOK describes a response with status code 200, with default header values.
//
// Approved request exchanged for a user session
type PostAPIDeviceLoginRequestsIDExchangeOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoUserDto
}

// IsSuccess returns true when this post Api device login requests Id exchange o k response has a 2xx status code
func (o *PostAPIDeviceLoginRequestsIDExchangeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api device login requests Id exchange o k response has a 3xx status code
func (o *PostAPIDeviceLoginRequestsIDExchangeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api device login requests Id exchange o k response has a 4xx status code
func (o *PostAPIDeviceLoginRequestsIDExchangeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api device login requests Id exchange o k response has a 5xx status code
func (o *PostAPIDeviceLoginRequestsIDExchangeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api device login requests Id exchange o k response a status code equal to that given
func (o *PostAPIDeviceLoginRequestsIDExchangeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api device login requests Id exchange o k response
func (o *PostAPIDeviceLoginRequestsIDExchangeOK) Code() int {
	return 200
}

func (o *PostAPIDeviceLoginRequestsIDExchangeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/device-login/requests/{id}/exchange][%d] postApiDeviceLoginRequestsIdExchangeOK %s", 200, payload)
}

func (o *PostAPIDeviceLoginRequestsIDExchangeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/device-login/requests/{id}/exchange][%d] postApiDeviceLoginRequestsIdExchangeOK %s", 200, payload)
}

func (o *PostAPIDeviceLoginRequestsIDExchangeOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoUserDto {
	return o.Payload
}

func (o *PostAPIDeviceLoginRequestsIDExchangeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoUserDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIDeviceLoginRequestsIDExchangeAccepted creates a PostAPIDeviceLoginRequestsIDExchangeAccepted with default headers values
func NewPostAPIDeviceLoginRequestsIDExchangeAccepted() *PostAPIDeviceLoginRequestsIDExchangeAccepted {
	return &PostAPIDeviceLoginRequestsIDExchangeAccepted{}
}

// PostAPIDeviceLoginRequestsIDExchangeAccepted describes a response with status code 202, with default header values.
//
// Authorization pending
type PostAPIDeviceLoginRequestsIDExchangeAccepted struct {
}

// IsSuccess returns true when this post Api device login requests Id exchange accepted response has a 2xx status code
func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api device login requests Id exchange accepted response has a 3xx status code
func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api device login requests Id exchange accepted response has a 4xx status code
func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api device login requests Id exchange accepted response has a 5xx status code
func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api device login requests Id exchange accepted response a status code equal to that given
func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the post Api device login requests Id exchange accepted response
func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) Code() int {
	return 202
}

func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) Error() string {
	return fmt.Sprintf("[POST /api/device-login/requests/{id}/exchange][%d] postApiDeviceLoginRequestsIdExchangeAccepted", 202)
}

func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) String() string {
	return fmt.Sprintf("[POST /api/device-login/requests/{id}/exchange][%d] postApiDeviceLoginRequestsIdExchangeAccepted", 202)
}

func (o *PostAPIDeviceLoginRequestsIDExchangeAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
