// Code generated by go-swagger; DO NOT EDIT.

package device_login

import (
	"context"
	"net/http"
	"time"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIDeviceLoginVerificationDecisionParams creates a new PostAPIDeviceLoginVerificationDecisionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIDeviceLoginVerificationDecisionParams() *PostAPIDeviceLoginVerificationDecisionParams {
	return NewPostAPIDeviceLoginVerificationDecisionParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAPIDeviceLoginVerificationDecisionParamsWithTimeout creates a new PostAPIDeviceLoginVerificationDecisionParams object
// with the ability to set a timeout on a request.
func NewPostAPIDeviceLoginVerificationDecisionParamsWithTimeout(timeout time.Duration) *PostAPIDeviceLoginVerificationDecisionParams {
	return &PostAPIDeviceLoginVerificationDecisionParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAPIDeviceLoginVerificationDecisionParamsWithContext creates a new PostAPIDeviceLoginVerificationDecisionParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIDeviceLoginVerificationDecisionParams].
func NewPostAPIDeviceLoginVerificationDecisionParamsWithContext(ctx context.Context) *PostAPIDeviceLoginVerificationDecisionParams {
	return &PostAPIDeviceLoginVerificationDecisionParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAPIDeviceLoginVerificationDecisionParamsWithHTTPClient creates a new PostAPIDeviceLoginVerificationDecisionParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIDeviceLoginVerificationDecisionParamsWithHTTPClient(client *http.Client) *PostAPIDeviceLoginVerificationDecisionParams {
	return &PostAPIDeviceLoginVerificationDecisionParams{
		HTTPClient: client,
	}
}

/*
PostAPIDeviceLoginVerificationDecisionParams contains all the parameters to send to the API endpoint

	for the post API device login verification decision operation.

	Typically these are written to a http.Request.
*/
type PostAPIDeviceLoginVerificationDecisionParams struct {

	// Decision.
	//
	// Device login decision
	Decision *models.DeviceloginDecisionDto

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post API device login verification decision params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIDeviceLoginVerificationDecisionParams) WithDefaults() *PostAPIDeviceLoginVerificationDecisionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API device login verification decision params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIDeviceLoginVerificationDecisionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API device login verification decision params.
func (o *PostAPIDeviceLoginVerificationDecisionParams) WithTimeout(timeout time.Duration) *PostAPIDeviceLoginVerificationDecisionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API device login verification decision params.
func (o *PostAPIDeviceLoginVerificationDecisionParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post API device login verification decision params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIDeviceLoginVerificationDecisionParams].
func (o *PostAPIDeviceLoginVerificationDecisionParams) WithContext(ctx context.Context) *PostAPIDeviceLoginVerificationDecisionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API device login verification decision params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIDeviceLoginVerificationDecisionParams].
func (o *PostAPIDeviceLoginVerificationDecisionParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post API device login verification decision params.
func (o *PostAPIDeviceLoginVerificationDecisionParams) WithHTTPClient(client *http.Client) *PostAPIDeviceLoginVerificationDecisionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API device login verification decision params.
func (o *PostAPIDeviceLoginVerificationDecisionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDecision adds the decision to the post API device login verification decision params.
func (o *PostAPIDeviceLoginVerificationDecisionParams) WithDecision(decision *models.DeviceloginDecisionDto) *PostAPIDeviceLoginVerificationDecisionParams {
	o.SetDecision(decision)
	return o
}

// SetDecision adds the decision to the post API device login verification decision params.
func (o *PostAPIDeviceLoginVerificationDecisionParams) SetDecision(decision *models.DeviceloginDecisionDto) {
	o.Decision = decision
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAPIDeviceLoginVerificationDecisionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Decision != nil {
		if err := r.SetBodyParam(o.Decision); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
