// Code generated by go-swagger; DO NOT EDIT.

package device_login

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIDeviceLoginRequestsParams creates a new PostAPIDeviceLoginRequestsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIDeviceLoginRequestsParams() *PostAPIDeviceLoginRequestsParams {
	return NewPostAPIDeviceLoginRequestsParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAPIDeviceLoginRequestsParamsWithTimeout creates a new PostAPIDeviceLoginRequestsParams object
// with the ability to set a timeout on a request.
func NewPostAPIDeviceLoginRequestsParamsWithTimeout(timeout time.Duration) *PostAPIDeviceLoginRequestsParams {
	return &PostAPIDeviceLoginRequestsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAPIDeviceLoginRequestsParamsWithContext creates a new PostAPIDeviceLoginRequestsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIDeviceLoginRequestsParams].
func NewPostAPIDeviceLoginRequestsParamsWithContext(ctx context.Context) *PostAPIDeviceLoginRequestsParams {
	return &PostAPIDeviceLoginRequestsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAPIDeviceLoginRequestsParamsWithHTTPClient creates a new PostAPIDeviceLoginRequestsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIDeviceLoginRequestsParamsWithHTTPClient(client *http.Client) *PostAPIDeviceLoginRequestsParams {
	return &PostAPIDeviceLoginRequestsParams{
		HTTPClient: client,
	}
}

/*
PostAPIDeviceLoginRequestsParams contains all the parameters to send to the API endpoint

	for the post API device login requests operation.

	Typically these are written to a http.Request.
*/
type PostAPIDeviceLoginRequestsParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post API device login requests params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIDeviceLoginRequestsParams) WithDefaults() *PostAPIDeviceLoginRequestsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API device login requests params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIDeviceLoginRequestsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API device login requests params.
func (o *PostAPIDeviceLoginRequestsParams) WithTimeout(timeout time.Duration) *PostAPIDeviceLoginRequestsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API device login requests params.
func (o *PostAPIDeviceLoginRequestsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post API device login requests params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIDeviceLoginRequestsParams].
func (o *PostAPIDeviceLoginRequestsParams) WithContext(ctx context.Context) *PostAPIDeviceLoginRequestsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API device login requests params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIDeviceLoginRequestsParams].
func (o *PostAPIDeviceLoginRequestsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post API device login requests params.
func (o *PostAPIDeviceLoginRequestsParams) WithHTTPClient(client *http.Client) *PostAPIDeviceLoginRequestsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API device login requests params.
func (o *PostAPIDeviceLoginRequestsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAPIDeviceLoginRequestsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
