// Code generated by go-swagger; DO NOT EDIT.

package apis

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new apis API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new apis API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new apis API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for apis API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// DeleteAPIApisID delete API.
	DeleteAPIApisID(params *DeleteAPIApisIDParams, opts ...ClientOption) (*DeleteAPIApisIDNoContent, error)

	// DeleteAPIApisIDContext delete API.
	DeleteAPIApisIDContext(ctx context.Context, params *DeleteAPIApisIDParams, opts ...ClientOption) (*DeleteAPIApisIDNoContent, error)

	// GetAPIAPIAccessClientID get client API access.
	GetAPIAPIAccessClientID(params *GetAPIAPIAccessClientIDParams, opts ...ClientOption) (*GetAPIAPIAccessClientIDOK, error)

	// GetAPIAPIAccessClientIDContext get client API access.
	GetAPIAPIAccessClientIDContext(ctx context.Context, params *GetAPIAPIAccessClientIDParams, opts ...ClientOption) (*GetAPIAPIAccessClientIDOK, error)

	// GetAPIApis list APIs.
	GetAPIApis(params *GetAPIApisParams, opts ...ClientOption) (*GetAPIApisOK, error)

	// GetAPIApisContext list APIs.
	GetAPIApisContext(ctx context.Context, params *GetAPIApisParams, opts ...ClientOption) (*GetAPIApisOK, error)

	// GetAPIApisID get API by ID.
	GetAPIApisID(params *GetAPIApisIDParams, opts ...ClientOption) (*GetAPIApisIDOK, error)

	// GetAPIApisIDContext get API by ID.
	GetAPIApisIDContext(ctx context.Context, params *GetAPIApisIDParams, opts ...ClientOption) (*GetAPIApisIDOK, error)

	// PostAPIApis create API.
	PostAPIApis(params *PostAPIApisParams, opts ...ClientOption) (*PostAPIApisCreated, error)

	// PostAPIApisContext create API.
	PostAPIApisContext(ctx context.Context, params *PostAPIApisParams, opts ...ClientOption) (*PostAPIApisCreated, error)

	// PutAPIAPIAccessClientID update client API access.
	PutAPIAPIAccessClientID(params *PutAPIAPIAccessClientIDParams, opts ...ClientOption) (*PutAPIAPIAccessClientIDOK, error)

	// PutAPIAPIAccessClientIDContext update client API access.
	PutAPIAPIAccessClientIDContext(ctx context.Context, params *PutAPIAPIAccessClientIDParams, opts ...ClientOption) (*PutAPIAPIAccessClientIDOK, error)

	// PutAPIApisID update API.
	PutAPIApisID(params *PutAPIApisIDParams, opts ...ClientOption) (*PutAPIApisIDOK, error)

	// PutAPIApisIDContext update API.
	PutAPIApisIDContext(ctx context.Context, params *PutAPIApisIDParams, opts ...ClientOption) (*PutAPIApisIDOK, error)

	// PutAPIApisIDPermissions update API permissions.
	PutAPIApisIDPermissions(params *PutAPIApisIDPermissionsParams, opts ...ClientOption) (*PutAPIApisIDPermissionsOK, error)

	// PutAPIApisIDPermissionsContext update API permissions.
	PutAPIApisIDPermissionsContext(ctx context.Context, params *PutAPIApisIDPermissionsParams, opts ...ClientOption) (*PutAPIApisIDPermissionsOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// DeleteAPIApisID deletes API.
//
// Delete an API by ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteAPIApisIDContext] instead.
func (a *Client) DeleteAPIApisID(params *DeleteAPIApisIDParams, opts ...ClientOption) (*DeleteAPIApisIDNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteAPIApisIDContext(ctx, params, opts...)
}

// DeleteAPIApisIDContext deletes API.
//
// Delete an API by ID.
//
// Do not use the deprecated [DeleteAPIApisIDParams.Context] with this method: it would be ignored.
func (a *Client) DeleteAPIApisIDContext(ctx context.Context, params *DeleteAPIApisIDParams, opts ...ClientOption) (*DeleteAPIApisIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAPIApisIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "DeleteAPIApisID",
		Method:             "DELETE",
		PathPattern:        "/api/apis/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAPIApisIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAPIApisIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAPIApisID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetAPIAPIAccessClientID gets client API access.
//
// Get the API permissions an OIDC client is allowed to request, split into user-delegated and client (machine-to-machine) access.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetAPIAPIAccessClientIDContext] instead.
func (a *Client) GetAPIAPIAccessClientID(params *GetAPIAPIAccessClientIDParams, opts ...ClientOption) (*GetAPIAPIAccessClientIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetAPIAPIAccessClientIDContext(ctx, params, opts...)
}

// GetAPIAPIAccessClientIDContext gets client API access.
//
// Get the API permissions an OIDC client is allowed to request, split into user-delegated and client (machine-to-machine) access.
//
// Do not use the deprecated [GetAPIAPIAccessClientIDParams.Context] with this method: it would be ignored.
func (a *Client) GetAPIAPIAccessClientIDContext(ctx context.Context, params *GetAPIAPIAccessClientIDParams, opts ...ClientOption) (*GetAPIAPIAccessClientIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIAPIAccessClientIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetAPIAPIAccessClientID",
		Method:             "GET",
		PathPattern:        "/api/api-access/{clientId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIAPIAccessClientIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIAPIAccessClientIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIAPIAccessClientID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetAPIApis lists APIs.
//
// Get a paginated list of APIs with optional search and sorting.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetAPIApisContext] instead.
func (a *Client) GetAPIApis(params *GetAPIApisParams, opts ...ClientOption) (*GetAPIApisOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetAPIApisContext(ctx, params, opts...)
}

// GetAPIApisContext lists APIs.
//
// Get a paginated list of APIs with optional search and sorting.
//
// Do not use the deprecated [GetAPIApisParams.Context] with this method: it would be ignored.
func (a *Client) GetAPIApisContext(ctx context.Context, params *GetAPIApisParams, opts ...ClientOption) (*GetAPIApisOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIApisParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetAPIApis",
		Method:             "GET",
		PathPattern:        "/api/apis",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIApisReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIApisOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIApis: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetAPIApisID gets API by ID.
//
// Retrieve a single API including its permissions.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetAPIApisIDContext] instead.
func (a *Client) GetAPIApisID(params *GetAPIApisIDParams, opts ...ClientOption) (*GetAPIApisIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetAPIApisIDContext(ctx, params, opts...)
}

// GetAPIApisIDContext gets API by ID.
//
// Retrieve a single API including its permissions.
//
// Do not use the deprecated [GetAPIApisIDParams.Context] with this method: it would be ignored.
func (a *Client) GetAPIApisIDContext(ctx context.Context, params *GetAPIApisIDParams, opts ...ClientOption) (*GetAPIApisIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIApisIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetAPIApisID",
		Method:             "GET",
		PathPattern:        "/api/apis/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIApisIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIApisIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIApisID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// PostAPIApis creates API.
//
// Create a new API resource server.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PostAPIApisContext] instead.
func (a *Client) PostAPIApis(params *PostAPIApisParams, opts ...ClientOption) (*PostAPIApisCreated, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostAPIApisContext(ctx, params, opts...)
}

// PostAPIApisContext creates API.
//
// Create a new API resource server.
//
// Do not use the deprecated [PostAPIApisParams.Context] with this method: it would be ignored.
func (a *Client) PostAPIApisContext(ctx context.Context, params *PostAPIApisParams, opts ...ClientOption) (*PostAPIApisCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIApisParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostAPIApis",
		Method:             "POST",
		PathPattern:        "/api/apis",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIApisReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIApisCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIApis: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// PutAPIAPIAccessClientID updates client API access.
//
// Replace the API permissions an OIDC client is allowed to request, split into user-delegated and client (machine-to-machine) access.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PutAPIAPIAccessClientIDContext] instead.
func (a *Client) PutAPIAPIAccessClientID(params *PutAPIAPIAccessClientIDParams, opts ...ClientOption) (*PutAPIAPIAccessClientIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PutAPIAPIAccessClientIDContext(ctx, params, opts...)
}

// PutAPIAPIAccessClientIDContext updates client API access.
//
// Replace the API permissions an OIDC client is allowed to request, split into user-delegated and client (machine-to-machine) access.
//
// Do not use the deprecated [PutAPIAPIAccessClientIDParams.Context] with this method: it would be ignored.
func (a *Client) PutAPIAPIAccessClientIDContext(ctx context.Context, params *PutAPIAPIAccessClientIDParams, opts ...ClientOption) (*PutAPIAPIAccessClientIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIAPIAccessClientIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PutAPIAPIAccessClientID",
		Method:             "PUT",
		PathPattern:        "/api/api-access/{clientId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIAPIAccessClientIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIAPIAccessClientIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIAPIAccessClientID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// PutAPIApisID updates API.
//
// Update an existing API by ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PutAPIApisIDContext] instead.
func (a *Client) PutAPIApisID(params *PutAPIApisIDParams, opts ...ClientOption) (*PutAPIApisIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PutAPIApisIDContext(ctx, params, opts...)
}

// PutAPIApisIDContext updates API.
//
// Update an existing API by ID.
//
// Do not use the deprecated [PutAPIApisIDParams.Context] with this method: it would be ignored.
func (a *Client) PutAPIApisIDContext(ctx context.Context, params *PutAPIApisIDParams, opts ...ClientOption) (*PutAPIApisIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIApisIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PutAPIApisID",
		Method:             "PUT",
		PathPattern:        "/api/apis/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIApisIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIApisIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIApisID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// PutAPIApisIDPermissions updates API permissions.
//
// Replace the full set of permissions for an API.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PutAPIApisIDPermissionsContext] instead.
func (a *Client) PutAPIApisIDPermissions(params *PutAPIApisIDPermissionsParams, opts ...ClientOption) (*PutAPIApisIDPermissionsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PutAPIApisIDPermissionsContext(ctx, params, opts...)
}

// PutAPIApisIDPermissionsContext updates API permissions.
//
// Replace the full set of permissions for an API.
//
// Do not use the deprecated [PutAPIApisIDPermissionsParams.Context] with this method: it would be ignored.
func (a *Client) PutAPIApisIDPermissionsContext(ctx context.Context, params *PutAPIApisIDPermissionsParams, opts ...ClientOption) (*PutAPIApisIDPermissionsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIApisIDPermissionsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PutAPIApisIDPermissions",
		Method:             "PUT",
		PathPattern:        "/api/apis/{id}/permissions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIApisIDPermissionsReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIApisIDPermissionsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIApisIDPermissions: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [ApisParams].
	ctx context.Context
}
