// Code generated by go-swagger; DO NOT EDIT.

package apis

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIApisIDAssignableClientsReader is a Reader for the GetAPIApisIDAssignableClients structure.
type GetAPIApisIDAssignableClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIApisIDAssignableClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIApisIDAssignableClientsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/apis/{id}/assignable-clients] GetAPIApisIDAssignableClients", response, response.Code())
	}
}

// NewGetAPIApisIDAssignableClientsOK creates a GetAPIApisIDAssignableClientsOK with default headers values
func NewGetAPIApisIDAssignableClientsOK() *GetAPIApisIDAssignableClientsOK {
	return &GetAPIApisIDAssignableClientsOK{}
}

// GetAPIApisIDAssignableClientsOK describes a response with status code 200, with default header values.
//
// OK
type GetAPIApisIDAssignableClientsOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedAPIAPIClientDto
}

// IsSuccess returns true when this get Api apis Id assignable clients o k response has a 2xx status code
func (o *GetAPIApisIDAssignableClientsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api apis Id assignable clients o k response has a 3xx status code
func (o *GetAPIApisIDAssignableClientsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api apis Id assignable clients o k response has a 4xx status code
func (o *GetAPIApisIDAssignableClientsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api apis Id assignable clients o k response has a 5xx status code
func (o *GetAPIApisIDAssignableClientsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api apis Id assignable clients o k response a status code equal to that given
func (o *GetAPIApisIDAssignableClientsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api apis Id assignable clients o k response
func (o *GetAPIApisIDAssignableClientsOK) Code() int {
	return 200
}

func (o *GetAPIApisIDAssignableClientsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/apis/{id}/assignable-clients][%d] getApiApisIdAssignableClientsOK %s", 200, payload)
}

func (o *GetAPIApisIDAssignableClientsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/apis/{id}/assignable-clients][%d] getApiApisIdAssignableClientsOK %s", 200, payload)
}

func (o *GetAPIApisIDAssignableClientsOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedAPIAPIClientDto {
	return o.Payload
}

func (o *GetAPIApisIDAssignableClientsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedAPIAPIClientDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
