// Code generated by go-swagger; DO NOT EDIT.

package apis

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIApisIDParams creates a new GetAPIApisIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIApisIDParams() *GetAPIApisIDParams {
	return NewGetAPIApisIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetAPIApisIDParamsWithTimeout creates a new GetAPIApisIDParams object
// with the ability to set a timeout on a request.
func NewGetAPIApisIDParamsWithTimeout(timeout time.Duration) *GetAPIApisIDParams {
	return &GetAPIApisIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetAPIApisIDParamsWithContext creates a new GetAPIApisIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIApisIDParams].
func NewGetAPIApisIDParamsWithContext(ctx context.Context) *GetAPIApisIDParams {
	return &GetAPIApisIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetAPIApisIDParamsWithHTTPClient creates a new GetAPIApisIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIApisIDParamsWithHTTPClient(client *http.Client) *GetAPIApisIDParams {
	return &GetAPIApisIDParams{
		HTTPClient: client,
	}
}

/*
GetAPIApisIDParams contains all the parameters to send to the API endpoint

	for the get API apis ID operation.

	Typically these are written to a http.Request.
*/
type GetAPIApisIDParams struct {

	// ID.
	//
	// API ID
	ID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get API apis ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIApisIDParams) WithDefaults() *GetAPIApisIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API apis ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIApisIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API apis ID params.
func (o *GetAPIApisIDParams) WithTimeout(timeout time.Duration) *GetAPIApisIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API apis ID params.
func (o *GetAPIApisIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get API apis ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIApisIDParams].
func (o *GetAPIApisIDParams) WithContext(ctx context.Context) *GetAPIApisIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API apis ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIApisIDParams].
func (o *GetAPIApisIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get API apis ID params.
func (o *GetAPIApisIDParams) WithHTTPClient(client *http.Client) *GetAPIApisIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API apis ID params.
func (o *GetAPIApisIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API apis ID params.
func (o *GetAPIApisIDParams) WithID(id string) *GetAPIApisIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API apis ID params.
func (o *GetAPIApisIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetAPIApisIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
