// Code generated by go-swagger; DO NOT EDIT.

package apis

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIAPIAccessClientIDParams creates a new GetAPIAPIAccessClientIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIAPIAccessClientIDParams() *GetAPIAPIAccessClientIDParams {
	return NewGetAPIAPIAccessClientIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetAPIAPIAccessClientIDParamsWithTimeout creates a new GetAPIAPIAccessClientIDParams object
// with the ability to set a timeout on a request.
func NewGetAPIAPIAccessClientIDParamsWithTimeout(timeout time.Duration) *GetAPIAPIAccessClientIDParams {
	return &GetAPIAPIAccessClientIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetAPIAPIAccessClientIDParamsWithContext creates a new GetAPIAPIAccessClientIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIAPIAccessClientIDParams].
func NewGetAPIAPIAccessClientIDParamsWithContext(ctx context.Context) *GetAPIAPIAccessClientIDParams {
	return &GetAPIAPIAccessClientIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetAPIAPIAccessClientIDParamsWithHTTPClient creates a new GetAPIAPIAccessClientIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIAPIAccessClientIDParamsWithHTTPClient(client *http.Client) *GetAPIAPIAccessClientIDParams {
	return &GetAPIAPIAccessClientIDParams{
		HTTPClient: client,
	}
}

/*
GetAPIAPIAccessClientIDParams contains all the parameters to send to the API endpoint

	for the get API API access client ID operation.

	Typically these are written to a http.Request.
*/
type GetAPIAPIAccessClientIDParams struct {

	// ClientID.
	//
	// OIDC Client ID
	ClientID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get API API access client ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAPIAccessClientIDParams) WithDefaults() *GetAPIAPIAccessClientIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API API access client ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAPIAccessClientIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API API access client ID params.
func (o *GetAPIAPIAccessClientIDParams) WithTimeout(timeout time.Duration) *GetAPIAPIAccessClientIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API API access client ID params.
func (o *GetAPIAPIAccessClientIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get API API access client ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIAPIAccessClientIDParams].
func (o *GetAPIAPIAccessClientIDParams) WithContext(ctx context.Context) *GetAPIAPIAccessClientIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API API access client ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIAPIAccessClientIDParams].
func (o *GetAPIAPIAccessClientIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get API API access client ID params.
func (o *GetAPIAPIAccessClientIDParams) WithHTTPClient(client *http.Client) *GetAPIAPIAccessClientIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API API access client ID params.
func (o *GetAPIAPIAccessClientIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientID adds the clientID to the get API API access client ID params.
func (o *GetAPIAPIAccessClientIDParams) WithClientID(clientID string) *GetAPIAPIAccessClientIDParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the get API API access client ID params.
func (o *GetAPIAPIAccessClientIDParams) SetClientID(clientID string) {
	o.ClientID = clientID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetAPIAPIAccessClientIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param clientId
	if err := r.SetPathParam("clientId", o.ClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
