// Code generated by go-swagger; DO NOT EDIT.

package apis

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutAPIApisIDCimdAccessReader is a Reader for the PutAPIApisIDCimdAccess structure.
type PutAPIApisIDCimdAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIApisIDCimdAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIApisIDCimdAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/apis/{id}/cimd-access] PutAPIApisIDCimdAccess", response, response.Code())
	}
}

// NewPutAPIApisIDCimdAccessOK creates a PutAPIApisIDCimdAccessOK with default headers values
func NewPutAPIApisIDCimdAccessOK() *PutAPIApisIDCimdAccessOK {
	return &PutAPIApisIDCimdAccessOK{}
}

// PutAPIApisIDCimdAccessOK describes a response with status code 200, with default header values.
//
// Updated API
type PutAPIApisIDCimdAccessOK struct {
	Payload *models.APIAPIResponseDto
}

// IsSuccess returns true when this put Api apis Id cimd access o k response has a 2xx status code
func (o *PutAPIApisIDCimdAccessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api apis Id cimd access o k response has a 3xx status code
func (o *PutAPIApisIDCimdAccessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api apis Id cimd access o k response has a 4xx status code
func (o *PutAPIApisIDCimdAccessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api apis Id cimd access o k response has a 5xx status code
func (o *PutAPIApisIDCimdAccessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api apis Id cimd access o k response a status code equal to that given
func (o *PutAPIApisIDCimdAccessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api apis Id cimd access o k response
func (o *PutAPIApisIDCimdAccessOK) Code() int {
	return 200
}

func (o *PutAPIApisIDCimdAccessOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/apis/{id}/cimd-access][%d] putApiApisIdCimdAccessOK %s", 200, payload)
}

func (o *PutAPIApisIDCimdAccessOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/apis/{id}/cimd-access][%d] putApiApisIdCimdAccessOK %s", 200, payload)
}

func (o *PutAPIApisIDCimdAccessOK) GetPayload() *models.APIAPIResponseDto {
	return o.Payload
}

func (o *PutAPIApisIDCimdAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIAPIResponseDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
