// Code generated by go-swagger; DO NOT EDIT.

package apis

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutAPIAPIAccessClientIDReader is a Reader for the PutAPIAPIAccessClientID structure.
type PutAPIAPIAccessClientIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIAPIAccessClientIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIAPIAccessClientIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/api-access/{clientId}] PutAPIAPIAccessClientID", response, response.Code())
	}
}

// NewPutAPIAPIAccessClientIDOK creates a PutAPIAPIAccessClientIDOK with default headers values
func NewPutAPIAPIAccessClientIDOK() *PutAPIAPIAccessClientIDOK {
	return &PutAPIAPIAccessClientIDOK{}
}

// PutAPIAPIAccessClientIDOK describes a response with status code 200, with default header values.
//
// OK
type PutAPIAPIAccessClientIDOK struct {
	Payload *models.APIClientAPIAccessDto
}

// IsSuccess returns true when this put Api Api access client Id o k response has a 2xx status code
func (o *PutAPIAPIAccessClientIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api Api access client Id o k response has a 3xx status code
func (o *PutAPIAPIAccessClientIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api Api access client Id o k response has a 4xx status code
func (o *PutAPIAPIAccessClientIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api Api access client Id o k response has a 5xx status code
func (o *PutAPIAPIAccessClientIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api Api access client Id o k response a status code equal to that given
func (o *PutAPIAPIAccessClientIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api Api access client Id o k response
func (o *PutAPIAPIAccessClientIDOK) Code() int {
	return 200
}

func (o *PutAPIAPIAccessClientIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/api-access/{clientId}][%d] putApiApiAccessClientIdOK %s", 200, payload)
}

func (o *PutAPIAPIAccessClientIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/api-access/{clientId}][%d] putApiApiAccessClientIdOK %s", 200, payload)
}

func (o *PutAPIAPIAccessClientIDOK) GetPayload() *models.APIClientAPIAccessDto {
	return o.Payload
}

func (o *PutAPIAPIAccessClientIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIClientAPIAccessDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
