// Code generated by go-swagger; DO NOT EDIT.

package apis

import (
	"context"
	"net/http"
	"time"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIApisIDPermissionsParams creates a new PutAPIApisIDPermissionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIApisIDPermissionsParams() *PutAPIApisIDPermissionsParams {
	return NewPutAPIApisIDPermissionsParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutAPIApisIDPermissionsParamsWithTimeout creates a new PutAPIApisIDPermissionsParams object
// with the ability to set a timeout on a request.
func NewPutAPIApisIDPermissionsParamsWithTimeout(timeout time.Duration) *PutAPIApisIDPermissionsParams {
	return &PutAPIApisIDPermissionsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutAPIApisIDPermissionsParamsWithContext creates a new PutAPIApisIDPermissionsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIApisIDPermissionsParams].
func NewPutAPIApisIDPermissionsParamsWithContext(ctx context.Context) *PutAPIApisIDPermissionsParams {
	return &PutAPIApisIDPermissionsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutAPIApisIDPermissionsParamsWithHTTPClient creates a new PutAPIApisIDPermissionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIApisIDPermissionsParamsWithHTTPClient(client *http.Client) *PutAPIApisIDPermissionsParams {
	return &PutAPIApisIDPermissionsParams{
		HTTPClient: client,
	}
}

/*
PutAPIApisIDPermissionsParams contains all the parameters to send to the API endpoint

	for the put API apis ID permissions operation.

	Typically these are written to a http.Request.
*/
type PutAPIApisIDPermissionsParams struct {

	// ID.
	//
	// API ID
	ID string

	// Permissions.
	//
	// Permissions to set
	Permissions *models.APIAPIPermissionsUpdateDto

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put API apis ID permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIApisIDPermissionsParams) WithDefaults() *PutAPIApisIDPermissionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API apis ID permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIApisIDPermissionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API apis ID permissions params.
func (o *PutAPIApisIDPermissionsParams) WithTimeout(timeout time.Duration) *PutAPIApisIDPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API apis ID permissions params.
func (o *PutAPIApisIDPermissionsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put API apis ID permissions params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIApisIDPermissionsParams].
func (o *PutAPIApisIDPermissionsParams) WithContext(ctx context.Context) *PutAPIApisIDPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API apis ID permissions params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutAPIApisIDPermissionsParams].
func (o *PutAPIApisIDPermissionsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put API apis ID permissions params.
func (o *PutAPIApisIDPermissionsParams) WithHTTPClient(client *http.Client) *PutAPIApisIDPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API apis ID permissions params.
func (o *PutAPIApisIDPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put API apis ID permissions params.
func (o *PutAPIApisIDPermissionsParams) WithID(id string) *PutAPIApisIDPermissionsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API apis ID permissions params.
func (o *PutAPIApisIDPermissionsParams) SetID(id string) {
	o.ID = id
}

// WithPermissions adds the permissions to the put API apis ID permissions params.
func (o *PutAPIApisIDPermissionsParams) WithPermissions(permissions *models.APIAPIPermissionsUpdateDto) *PutAPIApisIDPermissionsParams {
	o.SetPermissions(permissions)
	return o
}

// SetPermissions adds the permissions to the put API apis ID permissions params.
func (o *PutAPIApisIDPermissionsParams) SetPermissions(permissions *models.APIAPIPermissionsUpdateDto) {
	o.Permissions = permissions
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutAPIApisIDPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Permissions != nil {
		if err := r.SetBodyParam(o.Permissions); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
