// Code generated by go-swagger; DO NOT EDIT.

package audit_logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIAuditLogsAllParams creates a new GetAPIAuditLogsAllParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIAuditLogsAllParams() *GetAPIAuditLogsAllParams {
	return &GetAPIAuditLogsAllParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIAuditLogsAllParamsWithTimeout creates a new GetAPIAuditLogsAllParams object
// with the ability to set a timeout on a request.
func NewGetAPIAuditLogsAllParamsWithTimeout(timeout time.Duration) *GetAPIAuditLogsAllParams {
	return &GetAPIAuditLogsAllParams{
		timeout: timeout,
	}
}

// NewGetAPIAuditLogsAllParamsWithContext creates a new GetAPIAuditLogsAllParams object
// with the ability to set a context for a request.
func NewGetAPIAuditLogsAllParamsWithContext(ctx context.Context) *GetAPIAuditLogsAllParams {
	return &GetAPIAuditLogsAllParams{
		Context: ctx,
	}
}

// NewGetAPIAuditLogsAllParamsWithHTTPClient creates a new GetAPIAuditLogsAllParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIAuditLogsAllParamsWithHTTPClient(client *http.Client) *GetAPIAuditLogsAllParams {
	return &GetAPIAuditLogsAllParams{
		HTTPClient: client,
	}
}

/*
GetAPIAuditLogsAllParams contains all the parameters to send to the API endpoint

	for the get API audit logs all operation.

	Typically these are written to a http.Request.
*/
type GetAPIAuditLogsAllParams struct {

	/* PaginationLimit.

	   Number of items per page

	   Default: 20
	*/
	PaginationLimit *int64

	/* PaginationPage.

	   Page number for pagination

	   Default: 1
	*/
	PaginationPage *int64

	/* SortColumn.

	   Column to sort by
	*/
	SortColumn *string

	/* SortDirection.

	   Sort direction (asc or desc)

	   Default: "\"asc\""
	*/
	SortDirection *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API audit logs all params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAuditLogsAllParams) WithDefaults() *GetAPIAuditLogsAllParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API audit logs all params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAuditLogsAllParams) SetDefaults() {
	var (
		paginationLimitDefault = int64(20)

		paginationPageDefault = int64(1)

		sortDirectionDefault = string("\"asc\"")
	)

	val := GetAPIAuditLogsAllParams{
		PaginationLimit: &paginationLimitDefault,
		PaginationPage:  &paginationPageDefault,
		SortDirection:   &sortDirectionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) WithTimeout(timeout time.Duration) *GetAPIAuditLogsAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) WithContext(ctx context.Context) *GetAPIAuditLogsAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) WithHTTPClient(client *http.Client) *GetAPIAuditLogsAllParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPaginationLimit adds the paginationLimit to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) WithPaginationLimit(paginationLimit *int64) *GetAPIAuditLogsAllParams {
	o.SetPaginationLimit(paginationLimit)
	return o
}

// SetPaginationLimit adds the paginationLimit to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) SetPaginationLimit(paginationLimit *int64) {
	o.PaginationLimit = paginationLimit
}

// WithPaginationPage adds the paginationPage to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) WithPaginationPage(paginationPage *int64) *GetAPIAuditLogsAllParams {
	o.SetPaginationPage(paginationPage)
	return o
}

// SetPaginationPage adds the paginationPage to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) SetPaginationPage(paginationPage *int64) {
	o.PaginationPage = paginationPage
}

// WithSortColumn adds the sortColumn to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) WithSortColumn(sortColumn *string) *GetAPIAuditLogsAllParams {
	o.SetSortColumn(sortColumn)
	return o
}

// SetSortColumn adds the sortColumn to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) SetSortColumn(sortColumn *string) {
	o.SortColumn = sortColumn
}

// WithSortDirection adds the sortDirection to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) WithSortDirection(sortDirection *string) *GetAPIAuditLogsAllParams {
	o.SetSortDirection(sortDirection)
	return o
}

// SetSortDirection adds the sortDirection to the get API audit logs all params
func (o *GetAPIAuditLogsAllParams) SetSortDirection(sortDirection *string) {
	o.SortDirection = sortDirection
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIAuditLogsAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PaginationLimit != nil {

		// query param pagination[limit]
		var qrPaginationLimit int64

		if o.PaginationLimit != nil {
			qrPaginationLimit = *o.PaginationLimit
		}
		qPaginationLimit := swag.FormatInt64(qrPaginationLimit)
		if qPaginationLimit != "" {

			if err := r.SetQueryParam("pagination[limit]", qPaginationLimit); err != nil {
				return err
			}
		}
	}

	if o.PaginationPage != nil {

		// query param pagination[page]
		var qrPaginationPage int64

		if o.PaginationPage != nil {
			qrPaginationPage = *o.PaginationPage
		}
		qPaginationPage := swag.FormatInt64(qrPaginationPage)
		if qPaginationPage != "" {

			if err := r.SetQueryParam("pagination[page]", qPaginationPage); err != nil {
				return err
			}
		}
	}

	if o.SortColumn != nil {

		// query param sort[column]
		var qrSortColumn string

		if o.SortColumn != nil {
			qrSortColumn = *o.SortColumn
		}
		qSortColumn := qrSortColumn
		if qSortColumn != "" {

			if err := r.SetQueryParam("sort[column]", qSortColumn); err != nil {
				return err
			}
		}
	}

	if o.SortDirection != nil {

		// query param sort[direction]
		var qrSortDirection string

		if o.SortDirection != nil {
			qrSortDirection = *o.SortDirection
		}
		qSortDirection := qrSortDirection
		if qSortDirection != "" {

			if err := r.SetQueryParam("sort[direction]", qSortDirection); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
