// Code generated by go-swagger; DO NOT EDIT.

package audit_logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIAuditLogsFiltersClientNamesParams creates a new GetAPIAuditLogsFiltersClientNamesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIAuditLogsFiltersClientNamesParams() *GetAPIAuditLogsFiltersClientNamesParams {
	return &GetAPIAuditLogsFiltersClientNamesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIAuditLogsFiltersClientNamesParamsWithTimeout creates a new GetAPIAuditLogsFiltersClientNamesParams object
// with the ability to set a timeout on a request.
func NewGetAPIAuditLogsFiltersClientNamesParamsWithTimeout(timeout time.Duration) *GetAPIAuditLogsFiltersClientNamesParams {
	return &GetAPIAuditLogsFiltersClientNamesParams{
		timeout: timeout,
	}
}

// NewGetAPIAuditLogsFiltersClientNamesParamsWithContext creates a new GetAPIAuditLogsFiltersClientNamesParams object
// with the ability to set a context for a request.
func NewGetAPIAuditLogsFiltersClientNamesParamsWithContext(ctx context.Context) *GetAPIAuditLogsFiltersClientNamesParams {
	return &GetAPIAuditLogsFiltersClientNamesParams{
		Context: ctx,
	}
}

// NewGetAPIAuditLogsFiltersClientNamesParamsWithHTTPClient creates a new GetAPIAuditLogsFiltersClientNamesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIAuditLogsFiltersClientNamesParamsWithHTTPClient(client *http.Client) *GetAPIAuditLogsFiltersClientNamesParams {
	return &GetAPIAuditLogsFiltersClientNamesParams{
		HTTPClient: client,
	}
}

/*
GetAPIAuditLogsFiltersClientNamesParams contains all the parameters to send to the API endpoint

	for the get API audit logs filters client names operation.

	Typically these are written to a http.Request.
*/
type GetAPIAuditLogsFiltersClientNamesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API audit logs filters client names params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAuditLogsFiltersClientNamesParams) WithDefaults() *GetAPIAuditLogsFiltersClientNamesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API audit logs filters client names params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAuditLogsFiltersClientNamesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API audit logs filters client names params
func (o *GetAPIAuditLogsFiltersClientNamesParams) WithTimeout(timeout time.Duration) *GetAPIAuditLogsFiltersClientNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API audit logs filters client names params
func (o *GetAPIAuditLogsFiltersClientNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API audit logs filters client names params
func (o *GetAPIAuditLogsFiltersClientNamesParams) WithContext(ctx context.Context) *GetAPIAuditLogsFiltersClientNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API audit logs filters client names params
func (o *GetAPIAuditLogsFiltersClientNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API audit logs filters client names params
func (o *GetAPIAuditLogsFiltersClientNamesParams) WithHTTPClient(client *http.Client) *GetAPIAuditLogsFiltersClientNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API audit logs filters client names params
func (o *GetAPIAuditLogsFiltersClientNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIAuditLogsFiltersClientNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
