// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// APIAPICimdAccessUpdateDto api api cimd access update dto
//
// swagger:model api.apiCimdAccessUpdateDto
type APIAPICimdAccessUpdateDto struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// permission ids
	// Required: true
	PermissionIds []string `json:"permissionIds"`
}

// Validate validates this api api cimd access update dto
func (m *APIAPICimdAccessUpdateDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermissionIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIAPICimdAccessUpdateDto) validatePermissionIds(formats strfmt.Registry) error {

	if err := validate.Required("permissionIds", "body", m.PermissionIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api api cimd access update dto based on context it is used
func (m *APIAPICimdAccessUpdateDto) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIAPICimdAccessUpdateDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAPICimdAccessUpdateDto) UnmarshalBinary(b []byte) error {
	var res APIAPICimdAccessUpdateDto
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
