// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// APIAPIPermissionResponseDto api api permission response dto
//
// swagger:model api.apiPermissionResponseDto
type APIAPIPermissionResponseDto struct {

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this api api permission response dto
func (m *APIAPIPermissionResponseDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api api permission response dto based on context it is used
func (m *APIAPIPermissionResponseDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIAPIPermissionResponseDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAPIPermissionResponseDto) UnmarshalBinary(b []byte) error {
	var res APIAPIPermissionResponseDto
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
