// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// APIClientAPIGrantDto api client Api grant dto
//
// swagger:model api.clientApiGrantDto
type APIClientAPIGrantDto struct {

	// api
	API *APIAPIResponseDto `json:"api,omitempty"`

	// cimd granted access
	CimdGrantedAccess bool `json:"cimdGrantedAccess,omitempty"`

	// cimd granted permission ids
	CimdGrantedPermissionIds []string `json:"cimdGrantedPermissionIds"`

	// client access
	ClientAccess bool `json:"clientAccess,omitempty"`

	// client permission ids
	ClientPermissionIds []string `json:"clientPermissionIds"`

	// user delegated access
	UserDelegatedAccess bool `json:"userDelegatedAccess,omitempty"`

	// user delegated permission ids
	UserDelegatedPermissionIds []string `json:"userDelegatedPermissionIds"`
}

// Validate validates this api client Api grant dto
func (m *APIClientAPIGrantDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPI(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIClientAPIGrantDto) validateAPI(formats strfmt.Registry) error {
	if typeutils.IsZero(m.API) { // not required
		return nil
	}

	if m.API != nil {
		if err := m.API.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("api")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("api")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this api client Api grant dto based on the context it is used
func (m *APIClientAPIGrantDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAPI(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIClientAPIGrantDto) contextValidateAPI(ctx context.Context, formats strfmt.Registry) error {

	if m.API != nil {

		if typeutils.IsZero(m.API) { // not required
			return nil
		}

		if err := m.API.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("api")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("api")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIClientAPIGrantDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIClientAPIGrantDto) UnmarshalBinary(b []byte) error {
	var res APIClientAPIGrantDto
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
