// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto github com pocket id pocket id backend internal dto custom claim dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.CustomClaimDto
type GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto struct {

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this github com pocket id pocket id backend internal dto custom claim dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com pocket id pocket id backend internal dto custom claim dto based on context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
