// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto github com pocket id pocket id backend internal dto oidc client preview dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.OidcClientPreviewDto
type GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto struct {

	// access token
	AccessToken map[string]any `json:"accessToken,omitempty"`

	// id token
	IDToken map[string]any `json:"idToken,omitempty"`

	// user info
	UserInfo map[string]any `json:"userInfo,omitempty"`
}

// Validate validates this github com pocket id pocket id backend internal dto oidc client preview dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com pocket id pocket id backend internal dto oidc client preview dto based on context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
