// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto github com pocket id pocket id backend internal dto authorize oidc client request dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.AuthorizeOidcClientRequestDto
type GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto struct {

	// callback URL
	CallbackURL string `json:"callbackURL,omitempty"`

	// client ID
	// Required: true
	ClientID *string `json:"clientID"`

	// code challenge
	CodeChallenge string `json:"codeChallenge,omitempty"`

	// code challenge method
	CodeChallengeMethod string `json:"codeChallengeMethod,omitempty"`

	// nonce
	Nonce string `json:"nonce,omitempty"`

	// reauthentication token
	ReauthenticationToken string `json:"reauthenticationToken,omitempty"`

	// scope
	// Required: true
	Scope *string `json:"scope"`
}

// Validate validates this github com pocket id pocket id backend internal dto authorize oidc client request dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto) validateClientID(formats strfmt.Registry) error {

	if err := validate.Required("clientID", "body", m.ClientID); err != nil {
		return err
	}

	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto) validateScope(formats strfmt.Registry) error {

	if err := validate.Required("scope", "body", m.Scope); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this github com pocket id pocket id backend internal dto authorize oidc client request dto based on context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
