// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto github com pocket id pocket id backend internal dto Api key response dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.ApiKeyResponseDto
type GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto struct {

	// api key
	APIKey *GithubComPocketIDPocketIDBackendInternalDtoAPIKeyDto `json:"apiKey,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this github com pocket id pocket id backend internal dto Api key response dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto) validateAPIKey(formats strfmt.Registry) error {
	if swag.IsZero(m.APIKey) { // not required
		return nil
	}

	if m.APIKey != nil {
		if err := m.APIKey.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("apiKey")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("apiKey")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this github com pocket id pocket id backend internal dto Api key response dto based on the context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAPIKey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto) contextValidateAPIKey(ctx context.Context, formats strfmt.Registry) error {

	if m.APIKey != nil {

		if swag.IsZero(m.APIKey) { // not required
			return nil
		}

		if err := m.APIKey.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("apiKey")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("apiKey")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoAPIKeyResponseDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
