// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto github com pocket id pocket id backend internal dto oidc client created dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.OidcClientCreatedDto
type GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto struct {

	// access token duration minutes
	AccessTokenDurationMinutes int64 `json:"accessTokenDurationMinutes,omitempty"`

	// allowed user groups
	AllowedUserGroups []*GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto `json:"allowedUserGroups"`

	// backchannel logout URL
	BackchannelLogoutURL string `json:"backchannelLogoutURL,omitempty"`

	// callback URLs
	CallbackURLs []string `json:"callbackURLs"`

	// client type
	ClientType string `json:"clientType,omitempty"`

	// created secret
	CreatedSecret *GithubComPocketIDPocketIDBackendInternalDtoOidcClientSecretCreatedDto `json:"createdSecret,omitempty"`

	// credentials
	Credentials *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCredentialsDto `json:"credentials,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// has dark logo
	HasDarkLogo bool `json:"hasDarkLogo,omitempty"`

	// has logo
	HasLogo bool `json:"hasLogo,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// is group restricted
	IsGroupRestricted bool `json:"isGroupRestricted,omitempty"`

	// is public
	IsPublic bool `json:"isPublic,omitempty"`

	// launch URL
	LaunchURL string `json:"launchURL,omitempty"`

	// logout callback URLs
	LogoutCallbackURLs []string `json:"logoutCallbackURLs"`

	// name
	Name string `json:"name,omitempty"`

	// pkce enabled
	PkceEnabled bool `json:"pkceEnabled,omitempty"`

	// pkce supported
	PkceSupported bool `json:"pkceSupported,omitempty"`

	// refresh token duration minutes
	RefreshTokenDurationMinutes int64 `json:"refreshTokenDurationMinutes,omitempty"`

	// requires pushed authorization requests
	RequiresPushedAuthorizationRequests bool `json:"requiresPushedAuthorizationRequests,omitempty"`

	// requires reauthentication
	RequiresReauthentication bool `json:"requiresReauthentication,omitempty"`

	// skip consent
	SkipConsent bool `json:"skipConsent,omitempty"`
}

// Validate validates this github com pocket id pocket id backend internal dto oidc client created dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowedUserGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedSecret(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCredentials(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) validateAllowedUserGroups(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AllowedUserGroups) { // not required
		return nil
	}

	for i := 0; i < len(m.AllowedUserGroups); i++ {
		if typeutils.IsZero(m.AllowedUserGroups[i]) { // not required
			continue
		}

		if m.AllowedUserGroups[i] != nil {
			if err := m.AllowedUserGroups[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("allowedUserGroups" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("allowedUserGroups" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) validateCreatedSecret(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CreatedSecret) { // not required
		return nil
	}

	if m.CreatedSecret != nil {
		if err := m.CreatedSecret.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("createdSecret")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("createdSecret")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) validateCredentials(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Credentials) { // not required
		return nil
	}

	if m.Credentials != nil {
		if err := m.Credentials.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("credentials")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("credentials")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this github com pocket id pocket id backend internal dto oidc client created dto based on the context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAllowedUserGroups(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedSecret(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCredentials(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) contextValidateAllowedUserGroups(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AllowedUserGroups); i++ {

		if m.AllowedUserGroups[i] != nil {

			if typeutils.IsZero(m.AllowedUserGroups[i]) { // not required
				return nil
			}

			if err := m.AllowedUserGroups[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("allowedUserGroups" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("allowedUserGroups" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) contextValidateCreatedSecret(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedSecret != nil {

		if typeutils.IsZero(m.CreatedSecret) { // not required
			return nil
		}

		if err := m.CreatedSecret.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("createdSecret")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("createdSecret")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) contextValidateCredentials(ctx context.Context, formats strfmt.Registry) error {

	if m.Credentials != nil {

		if typeutils.IsZero(m.Credentials) { // not required
			return nil
		}

		if err := m.Credentials.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("credentials")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("credentials")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreatedDto
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
