// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto github com pocket id pocket id backend internal dto paginated github com pocket id pocket id backend internal dto oidc client with allowed groups count dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.Paginated-github_com_pocket-id_pocket-id_backend_internal_dto_OidcClientWithAllowedGroupsCountDto
type GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto struct {

	// data
	Data []*GithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto `json:"data"`

	// pagination
	Pagination *GithubComPocketIDPocketIDBackendInternalDtoPagination `json:"pagination,omitempty"`
}

// Validate validates this github com pocket id pocket id backend internal dto paginated github com pocket id pocket id backend internal dto oidc client with allowed groups count dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	for i := 0; i < len(m.Data); i++ {
		if swag.IsZero(m.Data[i]) { // not required
			continue
		}

		if m.Data[i] != nil {
			if err := m.Data[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) validatePagination(formats strfmt.Registry) error {
	if swag.IsZero(m.Pagination) { // not required
		return nil
	}

	if m.Pagination != nil {
		if err := m.Pagination.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("pagination")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("pagination")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this github com pocket id pocket id backend internal dto paginated github com pocket id pocket id backend internal dto oidc client with allowed groups count dto based on the context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePagination(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Data); i++ {

		if m.Data[i] != nil {

			if swag.IsZero(m.Data[i]) { // not required
				return nil
			}

			if err := m.Data[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) contextValidatePagination(ctx context.Context, formats strfmt.Registry) error {

	if m.Pagination != nil {

		if swag.IsZero(m.Pagination) { // not required
			return nil
		}

		if err := m.Pagination.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("pagination")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("pagination")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
