// Code generated by go-swagger; DO NOT EDIT.

package models

// GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessTokenCreateDto github com pocket id pocket id backend internal dto one time access token create dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.OneTimeAccessTokenCreateDto
type GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessTokenCreateDto any
