// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto github com pocket id pocket id backend internal dto one time access email as admin dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.OneTimeAccessEmailAsAdminDto
type GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto struct {

	// ttl
	TTL UtilsJSONDuration `json:"ttl,omitempty"`
}

// Validate validates this github com pocket id pocket id backend internal dto one time access email as admin dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com pocket id pocket id backend internal dto one time access email as admin dto based on context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoOneTimeAccessEmailAsAdminDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
