// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto github com pocket id pocket id backend internal dto user group create dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.UserGroupCreateDto
type GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto struct {

	// friendly name
	// Required: true
	// Max Length: 50
	// Min Length: 2
	FriendlyName *string `json:"friendlyName"`

	// name
	// Required: true
	// Max Length: 255
	// Min Length: 2
	Name *string `json:"name"`
}

// Validate validates this github com pocket id pocket id backend internal dto user group create dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFriendlyName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto) validateFriendlyName(formats strfmt.Registry) error {

	if err := validate.Required("friendlyName", "body", m.FriendlyName); err != nil {
		return err
	}

	if err := validate.MinLength("friendlyName", "body", *m.FriendlyName, 2); err != nil {
		return err
	}

	if err := validate.MaxLength("friendlyName", "body", *m.FriendlyName, 50); err != nil {
		return err
	}

	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 2); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 255); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this github com pocket id pocket id backend internal dto user group create dto based on context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
