// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto github com pocket id pocket id backend internal dto user group minimal dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.UserGroupMinimalDto
type GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// custom claims
	CustomClaims []*GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto `json:"customClaims"`

	// friendly name
	FriendlyName string `json:"friendlyName,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// ldap Id
	LdapID string `json:"ldapId,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// user count
	UserCount int64 `json:"userCount,omitempty"`
}

// Validate validates this github com pocket id pocket id backend internal dto user group minimal dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomClaims(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto) validateCustomClaims(formats strfmt.Registry) error {
	if swag.IsZero(m.CustomClaims) { // not required
		return nil
	}

	for i := 0; i < len(m.CustomClaims); i++ {
		if swag.IsZero(m.CustomClaims[i]) { // not required
			continue
		}

		if m.CustomClaims[i] != nil {
			if err := m.CustomClaims[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("customClaims" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("customClaims" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this github com pocket id pocket id backend internal dto user group minimal dto based on the context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCustomClaims(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto) contextValidateCustomClaims(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CustomClaims); i++ {

		if m.CustomClaims[i] != nil {

			if swag.IsZero(m.CustomClaims[i]) { // not required
				return nil
			}

			if err := m.CustomClaims[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("customClaims" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("customClaims" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
