// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPocketIDPocketIDBackendInternalDtoWebauthnCredentialDto github com pocket id pocket id backend internal dto webauthn credential dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.WebauthnCredentialDto
type GithubComPocketIDPocketIDBackendInternalDtoWebauthnCredentialDto struct {

	// attestation type
	AttestationType string `json:"attestationType,omitempty"`

	// backup eligible
	BackupEligible bool `json:"backupEligible,omitempty"`

	// backup state
	BackupState bool `json:"backupState,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// credential ID
	CredentialID string `json:"credentialID,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// transport
	Transport []string `json:"transport"`
}

// Validate validates this github com pocket id pocket id backend internal dto webauthn credential dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoWebauthnCredentialDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com pocket id pocket id backend internal dto webauthn credential dto based on context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoWebauthnCredentialDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoWebauthnCredentialDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoWebauthnCredentialDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoWebauthnCredentialDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
