// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto github com pocket id pocket id backend internal dto oidc update allowed user groups dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.OidcUpdateAllowedUserGroupsDto
type GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto struct {

	// user group ids
	// Required: true
	UserGroupIds []string `json:"userGroupIds"`
}

// Validate validates this github com pocket id pocket id backend internal dto oidc update allowed user groups dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserGroupIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto) validateUserGroupIds(formats strfmt.Registry) error {

	if err := validate.Required("userGroupIds", "body", m.UserGroupIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this github com pocket id pocket id backend internal dto oidc update allowed user groups dto based on context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
