// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPocketIDPocketIDBackendInternalDtoOidcTokenResponseDto github com pocket id pocket id backend internal dto oidc token response dto
//
// swagger:model github_com_pocket-id_pocket-id_backend_internal_dto.OidcTokenResponseDto
type GithubComPocketIDPocketIDBackendInternalDtoOidcTokenResponseDto struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// expires in
	ExpiresIn int64 `json:"expires_in,omitempty"`

	// id token
	IDToken string `json:"id_token,omitempty"`

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`

	// token type
	TokenType string `json:"token_type,omitempty"`
}

// Validate validates this github com pocket id pocket id backend internal dto oidc token response dto
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcTokenResponseDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com pocket id pocket id backend internal dto oidc token response dto based on context it is used
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcTokenResponseDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcTokenResponseDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPocketIDPocketIDBackendInternalDtoOidcTokenResponseDto) UnmarshalBinary(b []byte) error {
	var res GithubComPocketIDPocketIDBackendInternalDtoOidcTokenResponseDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
