// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// ScimsyncScimServiceProviderDTO scimsync scim service provider d t o
//
// swagger:model scimsync.ScimServiceProviderDTO
type ScimsyncScimServiceProviderDTO struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last synced at
	LastSyncedAt string `json:"lastSyncedAt,omitempty"`

	// oidc client
	OidcClient *GithubComPocketIDPocketIDBackendInternalDtoOidcClientMetaDataDto `json:"oidcClient,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this scimsync scim service provider d t o
func (m *ScimsyncScimServiceProviderDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOidcClient(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScimsyncScimServiceProviderDTO) validateOidcClient(formats strfmt.Registry) error {
	if typeutils.IsZero(m.OidcClient) { // not required
		return nil
	}

	if m.OidcClient != nil {
		if err := m.OidcClient.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("oidcClient")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("oidcClient")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this scimsync scim service provider d t o based on the context it is used
func (m *ScimsyncScimServiceProviderDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOidcClient(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScimsyncScimServiceProviderDTO) contextValidateOidcClient(ctx context.Context, formats strfmt.Registry) error {

	if m.OidcClient != nil {

		if typeutils.IsZero(m.OidcClient) { // not required
			return nil
		}

		if err := m.OidcClient.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("oidcClient")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("oidcClient")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ScimsyncScimServiceProviderDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScimsyncScimServiceProviderDTO) UnmarshalBinary(b []byte) error {
	var res ScimsyncScimServiceProviderDTO
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
