// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIOidcUsersMeAuthorizedClientsClientIDParams creates a new DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIOidcUsersMeAuthorizedClientsClientIDParams() *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	return &DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIOidcUsersMeAuthorizedClientsClientIDParamsWithTimeout creates a new DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIOidcUsersMeAuthorizedClientsClientIDParamsWithTimeout(timeout time.Duration) *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	return &DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIOidcUsersMeAuthorizedClientsClientIDParamsWithContext creates a new DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIOidcUsersMeAuthorizedClientsClientIDParamsWithContext(ctx context.Context) *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	return &DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIOidcUsersMeAuthorizedClientsClientIDParamsWithHTTPClient creates a new DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIOidcUsersMeAuthorizedClientsClientIDParamsWithHTTPClient(client *http.Client) *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	return &DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams contains all the parameters to send to the API endpoint

	for the delete API oidc users me authorized clients client ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams struct {

	/* ClientID.

	   Client ID to revoke authorization for
	*/
	ClientID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API oidc users me authorized clients client ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) WithDefaults() *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API oidc users me authorized clients client ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API oidc users me authorized clients client ID params
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) WithTimeout(timeout time.Duration) *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API oidc users me authorized clients client ID params
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API oidc users me authorized clients client ID params
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) WithContext(ctx context.Context) *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API oidc users me authorized clients client ID params
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API oidc users me authorized clients client ID params
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) WithHTTPClient(client *http.Client) *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API oidc users me authorized clients client ID params
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientID adds the clientID to the delete API oidc users me authorized clients client ID params
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) WithClientID(clientID string) *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the delete API oidc users me authorized clients client ID params
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) SetClientID(clientID string) {
	o.ClientID = clientID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIOidcUsersMeAuthorizedClientsClientIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clientId
	if err := r.SetPathParam("clientId", o.ClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
