// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIOidcClientsIDSecretsSecretIDReader is a Reader for the DeleteAPIOidcClientsIDSecretsSecretID structure.
type DeleteAPIOidcClientsIDSecretsSecretIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIOidcClientsIDSecretsSecretIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteAPIOidcClientsIDSecretsSecretIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteAPIOidcClientsIDSecretsSecretIDNoContent creates a DeleteAPIOidcClientsIDSecretsSecretIDNoContent with default headers values
func NewDeleteAPIOidcClientsIDSecretsSecretIDNoContent() *DeleteAPIOidcClientsIDSecretsSecretIDNoContent {
	return &DeleteAPIOidcClientsIDSecretsSecretIDNoContent{}
}

// DeleteAPIOidcClientsIDSecretsSecretIDNoContent describes a response with status code 204, with default header values.
//
// No content
type DeleteAPIOidcClientsIDSecretsSecretIDNoContent struct {
}

// IsSuccess returns true when this delete Api oidc clients Id secrets secret Id no content response has a 2xx status code
func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api oidc clients Id secrets secret Id no content response has a 3xx status code
func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api oidc clients Id secrets secret Id no content response has a 4xx status code
func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api oidc clients Id secrets secret Id no content response has a 5xx status code
func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api oidc clients Id secrets secret Id no content response a status code equal to that given
func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api oidc clients Id secrets secret Id no content response
func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) Code() int {
	return 204
}

func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/oidc/clients/{id}/secrets/{secretId}][%d] deleteApiOidcClientsIdSecretsSecretIdNoContent", 204)
}

func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/oidc/clients/{id}/secrets/{secretId}][%d] deleteApiOidcClientsIdSecretsSecretIdNoContent", 204)
}

func (o *DeleteAPIOidcClientsIDSecretsSecretIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIOidcClientsIDSecretsSecretIDDefault creates a DeleteAPIOidcClientsIDSecretsSecretIDDefault with default headers values
func NewDeleteAPIOidcClientsIDSecretsSecretIDDefault(code int) *DeleteAPIOidcClientsIDSecretsSecretIDDefault {
	return &DeleteAPIOidcClientsIDSecretsSecretIDDefault{
		_statusCode: code,
	}
}

// DeleteAPIOidcClientsIDSecretsSecretIDDefault describes a response with status code -1, with default header values.
//
// Error
type DeleteAPIOidcClientsIDSecretsSecretIDDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this delete API oidc clients ID secrets secret ID default response has a 2xx status code
func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete API oidc clients ID secrets secret ID default response has a 3xx status code
func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete API oidc clients ID secrets secret ID default response has a 4xx status code
func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete API oidc clients ID secrets secret ID default response has a 5xx status code
func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete API oidc clients ID secrets secret ID default response a status code equal to that given
func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete API oidc clients ID secrets secret ID default response
func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/oidc/clients/{id}/secrets/{secretId}][%d] DeleteAPIOidcClientsIDSecretsSecretID default %s", o._statusCode, payload)
}

func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/oidc/clients/{id}/secrets/{secretId}][%d] DeleteAPIOidcClientsIDSecretsSecretID default %s", o._statusCode, payload)
}

func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *DeleteAPIOidcClientsIDSecretsSecretIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
