// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIOidcClientsIDParams creates a new DeleteAPIOidcClientsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIOidcClientsIDParams() *DeleteAPIOidcClientsIDParams {
	return &DeleteAPIOidcClientsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIOidcClientsIDParamsWithTimeout creates a new DeleteAPIOidcClientsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIOidcClientsIDParamsWithTimeout(timeout time.Duration) *DeleteAPIOidcClientsIDParams {
	return &DeleteAPIOidcClientsIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIOidcClientsIDParamsWithContext creates a new DeleteAPIOidcClientsIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIOidcClientsIDParamsWithContext(ctx context.Context) *DeleteAPIOidcClientsIDParams {
	return &DeleteAPIOidcClientsIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIOidcClientsIDParamsWithHTTPClient creates a new DeleteAPIOidcClientsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIOidcClientsIDParamsWithHTTPClient(client *http.Client) *DeleteAPIOidcClientsIDParams {
	return &DeleteAPIOidcClientsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIOidcClientsIDParams contains all the parameters to send to the API endpoint

	for the delete API oidc clients ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIOidcClientsIDParams struct {

	/* ID.

	   Client ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API oidc clients ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIOidcClientsIDParams) WithDefaults() *DeleteAPIOidcClientsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API oidc clients ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIOidcClientsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API oidc clients ID params
func (o *DeleteAPIOidcClientsIDParams) WithTimeout(timeout time.Duration) *DeleteAPIOidcClientsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API oidc clients ID params
func (o *DeleteAPIOidcClientsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API oidc clients ID params
func (o *DeleteAPIOidcClientsIDParams) WithContext(ctx context.Context) *DeleteAPIOidcClientsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API oidc clients ID params
func (o *DeleteAPIOidcClientsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API oidc clients ID params
func (o *DeleteAPIOidcClientsIDParams) WithHTTPClient(client *http.Client) *DeleteAPIOidcClientsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API oidc clients ID params
func (o *DeleteAPIOidcClientsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API oidc clients ID params
func (o *DeleteAPIOidcClientsIDParams) WithID(id string) *DeleteAPIOidcClientsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API oidc clients ID params
func (o *DeleteAPIOidcClientsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIOidcClientsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
