// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIOidcClientsIDSecretsSecretIDParams creates a new DeleteAPIOidcClientsIDSecretsSecretIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIOidcClientsIDSecretsSecretIDParams() *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	return NewDeleteAPIOidcClientsIDSecretsSecretIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteAPIOidcClientsIDSecretsSecretIDParamsWithTimeout creates a new DeleteAPIOidcClientsIDSecretsSecretIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIOidcClientsIDSecretsSecretIDParamsWithTimeout(timeout time.Duration) *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	return &DeleteAPIOidcClientsIDSecretsSecretIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteAPIOidcClientsIDSecretsSecretIDParamsWithContext creates a new DeleteAPIOidcClientsIDSecretsSecretIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIOidcClientsIDSecretsSecretIDParams].
func NewDeleteAPIOidcClientsIDSecretsSecretIDParamsWithContext(ctx context.Context) *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	return &DeleteAPIOidcClientsIDSecretsSecretIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteAPIOidcClientsIDSecretsSecretIDParamsWithHTTPClient creates a new DeleteAPIOidcClientsIDSecretsSecretIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIOidcClientsIDSecretsSecretIDParamsWithHTTPClient(client *http.Client) *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	return &DeleteAPIOidcClientsIDSecretsSecretIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIOidcClientsIDSecretsSecretIDParams contains all the parameters to send to the API endpoint

	for the delete API oidc clients ID secrets secret ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIOidcClientsIDSecretsSecretIDParams struct {

	// ID.
	//
	// Client ID
	ID string

	// SecretID.
	//
	// Client secret ID
	SecretID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete API oidc clients ID secrets secret ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) WithDefaults() *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API oidc clients ID secrets secret ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API oidc clients ID secrets secret ID params.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) WithTimeout(timeout time.Duration) *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API oidc clients ID secrets secret ID params.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete API oidc clients ID secrets secret ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIOidcClientsIDSecretsSecretIDParams].
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) WithContext(ctx context.Context) *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API oidc clients ID secrets secret ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAPIOidcClientsIDSecretsSecretIDParams].
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API oidc clients ID secrets secret ID params.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) WithHTTPClient(client *http.Client) *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API oidc clients ID secrets secret ID params.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API oidc clients ID secrets secret ID params.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) WithID(id string) *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API oidc clients ID secrets secret ID params.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) SetID(id string) {
	o.ID = id
}

// WithSecretID adds the secretID to the delete API oidc clients ID secrets secret ID params.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) WithSecretID(secretID string) *DeleteAPIOidcClientsIDSecretsSecretIDParams {
	o.SetSecretID(secretID)
	return o
}

// SetSecretID adds the secretId to the delete API oidc clients ID secrets secret ID params.
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) SetSecretID(secretID string) {
	o.SecretID = secretID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteAPIOidcClientsIDSecretsSecretIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param secretId
	if err := r.SetPathParam("secretId", o.SecretID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
