// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIOidcClientsIDScimServiceProviderParams creates a new GetAPIOidcClientsIDScimServiceProviderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIOidcClientsIDScimServiceProviderParams() *GetAPIOidcClientsIDScimServiceProviderParams {
	return &GetAPIOidcClientsIDScimServiceProviderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIOidcClientsIDScimServiceProviderParamsWithTimeout creates a new GetAPIOidcClientsIDScimServiceProviderParams object
// with the ability to set a timeout on a request.
func NewGetAPIOidcClientsIDScimServiceProviderParamsWithTimeout(timeout time.Duration) *GetAPIOidcClientsIDScimServiceProviderParams {
	return &GetAPIOidcClientsIDScimServiceProviderParams{
		timeout: timeout,
	}
}

// NewGetAPIOidcClientsIDScimServiceProviderParamsWithContext creates a new GetAPIOidcClientsIDScimServiceProviderParams object
// with the ability to set a context for a request.
func NewGetAPIOidcClientsIDScimServiceProviderParamsWithContext(ctx context.Context) *GetAPIOidcClientsIDScimServiceProviderParams {
	return &GetAPIOidcClientsIDScimServiceProviderParams{
		Context: ctx,
	}
}

// NewGetAPIOidcClientsIDScimServiceProviderParamsWithHTTPClient creates a new GetAPIOidcClientsIDScimServiceProviderParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIOidcClientsIDScimServiceProviderParamsWithHTTPClient(client *http.Client) *GetAPIOidcClientsIDScimServiceProviderParams {
	return &GetAPIOidcClientsIDScimServiceProviderParams{
		HTTPClient: client,
	}
}

/*
GetAPIOidcClientsIDScimServiceProviderParams contains all the parameters to send to the API endpoint

	for the get API oidc clients ID scim service provider operation.

	Typically these are written to a http.Request.
*/
type GetAPIOidcClientsIDScimServiceProviderParams struct {

	/* ID.

	   Client ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API oidc clients ID scim service provider params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIOidcClientsIDScimServiceProviderParams) WithDefaults() *GetAPIOidcClientsIDScimServiceProviderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API oidc clients ID scim service provider params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIOidcClientsIDScimServiceProviderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API oidc clients ID scim service provider params
func (o *GetAPIOidcClientsIDScimServiceProviderParams) WithTimeout(timeout time.Duration) *GetAPIOidcClientsIDScimServiceProviderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API oidc clients ID scim service provider params
func (o *GetAPIOidcClientsIDScimServiceProviderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API oidc clients ID scim service provider params
func (o *GetAPIOidcClientsIDScimServiceProviderParams) WithContext(ctx context.Context) *GetAPIOidcClientsIDScimServiceProviderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API oidc clients ID scim service provider params
func (o *GetAPIOidcClientsIDScimServiceProviderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API oidc clients ID scim service provider params
func (o *GetAPIOidcClientsIDScimServiceProviderParams) WithHTTPClient(client *http.Client) *GetAPIOidcClientsIDScimServiceProviderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API oidc clients ID scim service provider params
func (o *GetAPIOidcClientsIDScimServiceProviderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API oidc clients ID scim service provider params
func (o *GetAPIOidcClientsIDScimServiceProviderParams) WithID(id string) *GetAPIOidcClientsIDScimServiceProviderParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API oidc clients ID scim service provider params
func (o *GetAPIOidcClientsIDScimServiceProviderParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIOidcClientsIDScimServiceProviderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
