// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
)

// GetAPIOidcClientsIDScimServiceProviderReader is a Reader for the GetAPIOidcClientsIDScimServiceProvider structure.
type GetAPIOidcClientsIDScimServiceProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIOidcClientsIDScimServiceProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIOidcClientsIDScimServiceProviderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/oidc/clients/{id}/scim-service-provider] GetAPIOidcClientsIDScimServiceProvider", response, response.Code())
	}
}

// NewGetAPIOidcClientsIDScimServiceProviderOK creates a GetAPIOidcClientsIDScimServiceProviderOK with default headers values
func NewGetAPIOidcClientsIDScimServiceProviderOK() *GetAPIOidcClientsIDScimServiceProviderOK {
	return &GetAPIOidcClientsIDScimServiceProviderOK{}
}

/*
GetAPIOidcClientsIDScimServiceProviderOK describes a response with status code 200, with default header values.

SCIM service provider configuration
*/
type GetAPIOidcClientsIDScimServiceProviderOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoScimServiceProviderDTO
}

// IsSuccess returns true when this get Api oidc clients Id scim service provider o k response has a 2xx status code
func (o *GetAPIOidcClientsIDScimServiceProviderOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api oidc clients Id scim service provider o k response has a 3xx status code
func (o *GetAPIOidcClientsIDScimServiceProviderOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api oidc clients Id scim service provider o k response has a 4xx status code
func (o *GetAPIOidcClientsIDScimServiceProviderOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api oidc clients Id scim service provider o k response has a 5xx status code
func (o *GetAPIOidcClientsIDScimServiceProviderOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api oidc clients Id scim service provider o k response a status code equal to that given
func (o *GetAPIOidcClientsIDScimServiceProviderOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api oidc clients Id scim service provider o k response
func (o *GetAPIOidcClientsIDScimServiceProviderOK) Code() int {
	return 200
}

func (o *GetAPIOidcClientsIDScimServiceProviderOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/scim-service-provider][%d] getApiOidcClientsIdScimServiceProviderOK %s", 200, payload)
}

func (o *GetAPIOidcClientsIDScimServiceProviderOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/scim-service-provider][%d] getApiOidcClientsIdScimServiceProviderOK %s", 200, payload)
}

func (o *GetAPIOidcClientsIDScimServiceProviderOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoScimServiceProviderDTO {
	return o.Payload
}

func (o *GetAPIOidcClientsIDScimServiceProviderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoScimServiceProviderDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
