// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIOidcClientsIDLogoReader is a Reader for the GetAPIOidcClientsIDLogo structure.
type GetAPIOidcClientsIDLogoReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIOidcClientsIDLogoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIOidcClientsIDLogoOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIOidcClientsIDLogoDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIOidcClientsIDLogoOK creates a GetAPIOidcClientsIDLogoOK with default headers values
func NewGetAPIOidcClientsIDLogoOK(writer io.Writer) *GetAPIOidcClientsIDLogoOK {
	return &GetAPIOidcClientsIDLogoOK{

		Payload: writer,
	}
}

// GetAPIOidcClientsIDLogoOK describes a response with status code 200, with default header values.
//
// Logo image
type GetAPIOidcClientsIDLogoOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get Api oidc clients Id logo o k response has a 2xx status code
func (o *GetAPIOidcClientsIDLogoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api oidc clients Id logo o k response has a 3xx status code
func (o *GetAPIOidcClientsIDLogoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api oidc clients Id logo o k response has a 4xx status code
func (o *GetAPIOidcClientsIDLogoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api oidc clients Id logo o k response has a 5xx status code
func (o *GetAPIOidcClientsIDLogoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api oidc clients Id logo o k response a status code equal to that given
func (o *GetAPIOidcClientsIDLogoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api oidc clients Id logo o k response
func (o *GetAPIOidcClientsIDLogoOK) Code() int {
	return 200
}

func (o *GetAPIOidcClientsIDLogoOK) Error() string {
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/logo][%d] getApiOidcClientsIdLogoOK", 200)
}

func (o *GetAPIOidcClientsIDLogoOK) String() string {
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/logo][%d] getApiOidcClientsIdLogoOK", 200)
}

func (o *GetAPIOidcClientsIDLogoOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetAPIOidcClientsIDLogoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIOidcClientsIDLogoDefault creates a GetAPIOidcClientsIDLogoDefault with default headers values
func NewGetAPIOidcClientsIDLogoDefault(code int) *GetAPIOidcClientsIDLogoDefault {
	return &GetAPIOidcClientsIDLogoDefault{
		_statusCode: code,
	}
}

// GetAPIOidcClientsIDLogoDefault describes a response with status code -1, with default header values.
//
// Error
type GetAPIOidcClientsIDLogoDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this get API oidc clients ID logo default response has a 2xx status code
func (o *GetAPIOidcClientsIDLogoDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API oidc clients ID logo default response has a 3xx status code
func (o *GetAPIOidcClientsIDLogoDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API oidc clients ID logo default response has a 4xx status code
func (o *GetAPIOidcClientsIDLogoDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API oidc clients ID logo default response has a 5xx status code
func (o *GetAPIOidcClientsIDLogoDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API oidc clients ID logo default response a status code equal to that given
func (o *GetAPIOidcClientsIDLogoDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get API oidc clients ID logo default response
func (o *GetAPIOidcClientsIDLogoDefault) Code() int {
	return o._statusCode
}

func (o *GetAPIOidcClientsIDLogoDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/logo][%d] GetAPIOidcClientsIDLogo default %s", o._statusCode, payload)
}

func (o *GetAPIOidcClientsIDLogoDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/logo][%d] GetAPIOidcClientsIDLogo default %s", o._statusCode, payload)
}

func (o *GetAPIOidcClientsIDLogoDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *GetAPIOidcClientsIDLogoDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
