// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIOidcClientsIDPreviewUserIDReader is a Reader for the GetAPIOidcClientsIDPreviewUserID structure.
type GetAPIOidcClientsIDPreviewUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIOidcClientsIDPreviewUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIOidcClientsIDPreviewUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIOidcClientsIDPreviewUserIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIOidcClientsIDPreviewUserIDOK creates a GetAPIOidcClientsIDPreviewUserIDOK with default headers values
func NewGetAPIOidcClientsIDPreviewUserIDOK() *GetAPIOidcClientsIDPreviewUserIDOK {
	return &GetAPIOidcClientsIDPreviewUserIDOK{}
}

// GetAPIOidcClientsIDPreviewUserIDOK describes a response with status code 200, with default header values.
//
// Preview data including ID token, access token, and userinfo payloads
type GetAPIOidcClientsIDPreviewUserIDOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto
}

// IsSuccess returns true when this get Api oidc clients Id preview user Id o k response has a 2xx status code
func (o *GetAPIOidcClientsIDPreviewUserIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api oidc clients Id preview user Id o k response has a 3xx status code
func (o *GetAPIOidcClientsIDPreviewUserIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api oidc clients Id preview user Id o k response has a 4xx status code
func (o *GetAPIOidcClientsIDPreviewUserIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api oidc clients Id preview user Id o k response has a 5xx status code
func (o *GetAPIOidcClientsIDPreviewUserIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api oidc clients Id preview user Id o k response a status code equal to that given
func (o *GetAPIOidcClientsIDPreviewUserIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api oidc clients Id preview user Id o k response
func (o *GetAPIOidcClientsIDPreviewUserIDOK) Code() int {
	return 200
}

func (o *GetAPIOidcClientsIDPreviewUserIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/preview/{userId}][%d] getApiOidcClientsIdPreviewUserIdOK %s", 200, payload)
}

func (o *GetAPIOidcClientsIDPreviewUserIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/preview/{userId}][%d] getApiOidcClientsIdPreviewUserIdOK %s", 200, payload)
}

func (o *GetAPIOidcClientsIDPreviewUserIDOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto {
	return o.Payload
}

func (o *GetAPIOidcClientsIDPreviewUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientPreviewDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIOidcClientsIDPreviewUserIDDefault creates a GetAPIOidcClientsIDPreviewUserIDDefault with default headers values
func NewGetAPIOidcClientsIDPreviewUserIDDefault(code int) *GetAPIOidcClientsIDPreviewUserIDDefault {
	return &GetAPIOidcClientsIDPreviewUserIDDefault{
		_statusCode: code,
	}
}

// GetAPIOidcClientsIDPreviewUserIDDefault describes a response with status code -1, with default header values.
//
// Error
type GetAPIOidcClientsIDPreviewUserIDDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this get API oidc clients ID preview user ID default response has a 2xx status code
func (o *GetAPIOidcClientsIDPreviewUserIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API oidc clients ID preview user ID default response has a 3xx status code
func (o *GetAPIOidcClientsIDPreviewUserIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API oidc clients ID preview user ID default response has a 4xx status code
func (o *GetAPIOidcClientsIDPreviewUserIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API oidc clients ID preview user ID default response has a 5xx status code
func (o *GetAPIOidcClientsIDPreviewUserIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API oidc clients ID preview user ID default response a status code equal to that given
func (o *GetAPIOidcClientsIDPreviewUserIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get API oidc clients ID preview user ID default response
func (o *GetAPIOidcClientsIDPreviewUserIDDefault) Code() int {
	return o._statusCode
}

func (o *GetAPIOidcClientsIDPreviewUserIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/preview/{userId}][%d] GetAPIOidcClientsIDPreviewUserID default %s", o._statusCode, payload)
}

func (o *GetAPIOidcClientsIDPreviewUserIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}/preview/{userId}][%d] GetAPIOidcClientsIDPreviewUserID default %s", o._statusCode, payload)
}

func (o *GetAPIOidcClientsIDPreviewUserIDDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *GetAPIOidcClientsIDPreviewUserIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
