// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIOidcUsersIDAuthorizedClientsReader is a Reader for the GetAPIOidcUsersIDAuthorizedClients structure.
type GetAPIOidcUsersIDAuthorizedClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIOidcUsersIDAuthorizedClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIOidcUsersIDAuthorizedClientsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIOidcUsersIDAuthorizedClientsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIOidcUsersIDAuthorizedClientsOK creates a GetAPIOidcUsersIDAuthorizedClientsOK with default headers values
func NewGetAPIOidcUsersIDAuthorizedClientsOK() *GetAPIOidcUsersIDAuthorizedClientsOK {
	return &GetAPIOidcUsersIDAuthorizedClientsOK{}
}

// GetAPIOidcUsersIDAuthorizedClientsOK describes a response with status code 200, with default header values.
//
// OK
type GetAPIOidcUsersIDAuthorizedClientsOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoAuthorizedOidcClientDto
}

// IsSuccess returns true when this get Api oidc users Id authorized clients o k response has a 2xx status code
func (o *GetAPIOidcUsersIDAuthorizedClientsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api oidc users Id authorized clients o k response has a 3xx status code
func (o *GetAPIOidcUsersIDAuthorizedClientsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api oidc users Id authorized clients o k response has a 4xx status code
func (o *GetAPIOidcUsersIDAuthorizedClientsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api oidc users Id authorized clients o k response has a 5xx status code
func (o *GetAPIOidcUsersIDAuthorizedClientsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api oidc users Id authorized clients o k response a status code equal to that given
func (o *GetAPIOidcUsersIDAuthorizedClientsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api oidc users Id authorized clients o k response
func (o *GetAPIOidcUsersIDAuthorizedClientsOK) Code() int {
	return 200
}

func (o *GetAPIOidcUsersIDAuthorizedClientsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/users/{id}/authorized-clients][%d] getApiOidcUsersIdAuthorizedClientsOK %s", 200, payload)
}

func (o *GetAPIOidcUsersIDAuthorizedClientsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/users/{id}/authorized-clients][%d] getApiOidcUsersIdAuthorizedClientsOK %s", 200, payload)
}

func (o *GetAPIOidcUsersIDAuthorizedClientsOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoAuthorizedOidcClientDto {
	return o.Payload
}

func (o *GetAPIOidcUsersIDAuthorizedClientsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoAuthorizedOidcClientDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIOidcUsersIDAuthorizedClientsDefault creates a GetAPIOidcUsersIDAuthorizedClientsDefault with default headers values
func NewGetAPIOidcUsersIDAuthorizedClientsDefault(code int) *GetAPIOidcUsersIDAuthorizedClientsDefault {
	return &GetAPIOidcUsersIDAuthorizedClientsDefault{
		_statusCode: code,
	}
}

// GetAPIOidcUsersIDAuthorizedClientsDefault describes a response with status code -1, with default header values.
//
// Error
type GetAPIOidcUsersIDAuthorizedClientsDefault struct {
	_statusCode int

	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto
}

// IsSuccess returns true when this get API oidc users ID authorized clients default response has a 2xx status code
func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API oidc users ID authorized clients default response has a 3xx status code
func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API oidc users ID authorized clients default response has a 4xx status code
func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API oidc users ID authorized clients default response has a 5xx status code
func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API oidc users ID authorized clients default response a status code equal to that given
func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get API oidc users ID authorized clients default response
func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) Code() int {
	return o._statusCode
}

func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/users/{id}/authorized-clients][%d] GetAPIOidcUsersIDAuthorizedClients default %s", o._statusCode, payload)
}

func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/users/{id}/authorized-clients][%d] GetAPIOidcUsersIDAuthorizedClients default %s", o._statusCode, payload)
}

func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto {
	return o.Payload
}

func (o *GetAPIOidcUsersIDAuthorizedClientsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
