// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/models"
)

// GetAPIOidcUsersMeClientsReader is a Reader for the GetAPIOidcUsersMeClients structure.
type GetAPIOidcUsersMeClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIOidcUsersMeClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIOidcUsersMeClientsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/oidc/users/me/clients] GetAPIOidcUsersMeClients", response, response.Code())
	}
}

// NewGetAPIOidcUsersMeClientsOK creates a GetAPIOidcUsersMeClientsOK with default headers values
func NewGetAPIOidcUsersMeClientsOK() *GetAPIOidcUsersMeClientsOK {
	return &GetAPIOidcUsersMeClientsOK{}
}

/*
GetAPIOidcUsersMeClientsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIOidcUsersMeClientsOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoAccessibleOidcClientDto
}

// IsSuccess returns true when this get Api oidc users me clients o k response has a 2xx status code
func (o *GetAPIOidcUsersMeClientsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api oidc users me clients o k response has a 3xx status code
func (o *GetAPIOidcUsersMeClientsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api oidc users me clients o k response has a 4xx status code
func (o *GetAPIOidcUsersMeClientsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api oidc users me clients o k response has a 5xx status code
func (o *GetAPIOidcUsersMeClientsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api oidc users me clients o k response a status code equal to that given
func (o *GetAPIOidcUsersMeClientsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api oidc users me clients o k response
func (o *GetAPIOidcUsersMeClientsOK) Code() int {
	return 200
}

func (o *GetAPIOidcUsersMeClientsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/users/me/clients][%d] getApiOidcUsersMeClientsOK %s", 200, payload)
}

func (o *GetAPIOidcUsersMeClientsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/users/me/clients][%d] getApiOidcUsersMeClientsOK %s", 200, payload)
}

func (o *GetAPIOidcUsersMeClientsOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoAccessibleOidcClientDto {
	return o.Payload
}

func (o *GetAPIOidcUsersMeClientsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoPaginatedGithubComPocketIDPocketIDBackendInternalDtoAccessibleOidcClientDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
