// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIOidcClientsIDSecretsParams creates a new GetAPIOidcClientsIDSecretsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIOidcClientsIDSecretsParams() *GetAPIOidcClientsIDSecretsParams {
	return NewGetAPIOidcClientsIDSecretsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetAPIOidcClientsIDSecretsParamsWithTimeout creates a new GetAPIOidcClientsIDSecretsParams object
// with the ability to set a timeout on a request.
func NewGetAPIOidcClientsIDSecretsParamsWithTimeout(timeout time.Duration) *GetAPIOidcClientsIDSecretsParams {
	return &GetAPIOidcClientsIDSecretsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetAPIOidcClientsIDSecretsParamsWithContext creates a new GetAPIOidcClientsIDSecretsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIOidcClientsIDSecretsParams].
func NewGetAPIOidcClientsIDSecretsParamsWithContext(ctx context.Context) *GetAPIOidcClientsIDSecretsParams {
	return &GetAPIOidcClientsIDSecretsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetAPIOidcClientsIDSecretsParamsWithHTTPClient creates a new GetAPIOidcClientsIDSecretsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIOidcClientsIDSecretsParamsWithHTTPClient(client *http.Client) *GetAPIOidcClientsIDSecretsParams {
	return &GetAPIOidcClientsIDSecretsParams{
		HTTPClient: client,
	}
}

/*
GetAPIOidcClientsIDSecretsParams contains all the parameters to send to the API endpoint

	for the get API oidc clients ID secrets operation.

	Typically these are written to a http.Request.
*/
type GetAPIOidcClientsIDSecretsParams struct {

	// ID.
	//
	// Client ID
	ID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get API oidc clients ID secrets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIOidcClientsIDSecretsParams) WithDefaults() *GetAPIOidcClientsIDSecretsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API oidc clients ID secrets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIOidcClientsIDSecretsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API oidc clients ID secrets params.
func (o *GetAPIOidcClientsIDSecretsParams) WithTimeout(timeout time.Duration) *GetAPIOidcClientsIDSecretsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API oidc clients ID secrets params.
func (o *GetAPIOidcClientsIDSecretsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get API oidc clients ID secrets params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIOidcClientsIDSecretsParams].
func (o *GetAPIOidcClientsIDSecretsParams) WithContext(ctx context.Context) *GetAPIOidcClientsIDSecretsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API oidc clients ID secrets params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAPIOidcClientsIDSecretsParams].
func (o *GetAPIOidcClientsIDSecretsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get API oidc clients ID secrets params.
func (o *GetAPIOidcClientsIDSecretsParams) WithHTTPClient(client *http.Client) *GetAPIOidcClientsIDSecretsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API oidc clients ID secrets params.
func (o *GetAPIOidcClientsIDSecretsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API oidc clients ID secrets params.
func (o *GetAPIOidcClientsIDSecretsParams) WithID(id string) *GetAPIOidcClientsIDSecretsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API oidc clients ID secrets params.
func (o *GetAPIOidcClientsIDSecretsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetAPIOidcClientsIDSecretsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
