// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/models"
)

// GetAPIOidcClientsIDReader is a Reader for the GetAPIOidcClientsID structure.
type GetAPIOidcClientsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIOidcClientsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIOidcClientsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/oidc/clients/{id}] GetAPIOidcClientsID", response, response.Code())
	}
}

// NewGetAPIOidcClientsIDOK creates a GetAPIOidcClientsIDOK with default headers values
func NewGetAPIOidcClientsIDOK() *GetAPIOidcClientsIDOK {
	return &GetAPIOidcClientsIDOK{}
}

/*
GetAPIOidcClientsIDOK describes a response with status code 200, with default header values.

Client information
*/
type GetAPIOidcClientsIDOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedUserGroupsDto
}

// IsSuccess returns true when this get Api oidc clients Id o k response has a 2xx status code
func (o *GetAPIOidcClientsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api oidc clients Id o k response has a 3xx status code
func (o *GetAPIOidcClientsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api oidc clients Id o k response has a 4xx status code
func (o *GetAPIOidcClientsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api oidc clients Id o k response has a 5xx status code
func (o *GetAPIOidcClientsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api oidc clients Id o k response a status code equal to that given
func (o *GetAPIOidcClientsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api oidc clients Id o k response
func (o *GetAPIOidcClientsIDOK) Code() int {
	return 200
}

func (o *GetAPIOidcClientsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}][%d] getApiOidcClientsIdOK %s", 200, payload)
}

func (o *GetAPIOidcClientsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/oidc/clients/{id}][%d] getApiOidcClientsIdOK %s", 200, payload)
}

func (o *GetAPIOidcClientsIDOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedUserGroupsDto {
	return o.Payload
}

func (o *GetAPIOidcClientsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedUserGroupsDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
