// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIOidcTokenParams creates a new PostAPIOidcTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIOidcTokenParams() *PostAPIOidcTokenParams {
	return &PostAPIOidcTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIOidcTokenParamsWithTimeout creates a new PostAPIOidcTokenParams object
// with the ability to set a timeout on a request.
func NewPostAPIOidcTokenParamsWithTimeout(timeout time.Duration) *PostAPIOidcTokenParams {
	return &PostAPIOidcTokenParams{
		timeout: timeout,
	}
}

// NewPostAPIOidcTokenParamsWithContext creates a new PostAPIOidcTokenParams object
// with the ability to set a context for a request.
func NewPostAPIOidcTokenParamsWithContext(ctx context.Context) *PostAPIOidcTokenParams {
	return &PostAPIOidcTokenParams{
		Context: ctx,
	}
}

// NewPostAPIOidcTokenParamsWithHTTPClient creates a new PostAPIOidcTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIOidcTokenParamsWithHTTPClient(client *http.Client) *PostAPIOidcTokenParams {
	return &PostAPIOidcTokenParams{
		HTTPClient: client,
	}
}

/*
PostAPIOidcTokenParams contains all the parameters to send to the API endpoint

	for the post API oidc token operation.

	Typically these are written to a http.Request.
*/
type PostAPIOidcTokenParams struct {

	/* ClientAssertion.

	   Client assertion type (for 'authorization_code' grant when using client assertions)
	*/
	ClientAssertion *string

	/* ClientAssertionType.

	   Client assertion type (for 'authorization_code' grant when using client assertions)
	*/
	ClientAssertionType *string

	/* ClientID.

	   Client ID (if not using Basic Auth)
	*/
	ClientID *string

	/* ClientSecret.

	   Client secret (if not using Basic Auth or client assertions)
	*/
	ClientSecret *string

	/* Code.

	   Authorization code (required for 'authorization_code' grant)
	*/
	Code *string

	/* CodeVerifier.

	   PKCE code verifier (for authorization_code with PKCE)
	*/
	CodeVerifier *string

	/* GrantType.

	   Grant type ('authorization_code' or 'refresh_token')
	*/
	GrantType string

	/* RefreshToken.

	   Refresh token (required for 'refresh_token' grant)
	*/
	RefreshToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API oidc token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOidcTokenParams) WithDefaults() *PostAPIOidcTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API oidc token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOidcTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithTimeout(timeout time.Duration) *PostAPIOidcTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithContext(ctx context.Context) *PostAPIOidcTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithHTTPClient(client *http.Client) *PostAPIOidcTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientAssertion adds the clientAssertion to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithClientAssertion(clientAssertion *string) *PostAPIOidcTokenParams {
	o.SetClientAssertion(clientAssertion)
	return o
}

// SetClientAssertion adds the clientAssertion to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetClientAssertion(clientAssertion *string) {
	o.ClientAssertion = clientAssertion
}

// WithClientAssertionType adds the clientAssertionType to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithClientAssertionType(clientAssertionType *string) *PostAPIOidcTokenParams {
	o.SetClientAssertionType(clientAssertionType)
	return o
}

// SetClientAssertionType adds the clientAssertionType to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetClientAssertionType(clientAssertionType *string) {
	o.ClientAssertionType = clientAssertionType
}

// WithClientID adds the clientID to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithClientID(clientID *string) *PostAPIOidcTokenParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetClientID(clientID *string) {
	o.ClientID = clientID
}

// WithClientSecret adds the clientSecret to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithClientSecret(clientSecret *string) *PostAPIOidcTokenParams {
	o.SetClientSecret(clientSecret)
	return o
}

// SetClientSecret adds the clientSecret to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetClientSecret(clientSecret *string) {
	o.ClientSecret = clientSecret
}

// WithCode adds the code to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithCode(code *string) *PostAPIOidcTokenParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetCode(code *string) {
	o.Code = code
}

// WithCodeVerifier adds the codeVerifier to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithCodeVerifier(codeVerifier *string) *PostAPIOidcTokenParams {
	o.SetCodeVerifier(codeVerifier)
	return o
}

// SetCodeVerifier adds the codeVerifier to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetCodeVerifier(codeVerifier *string) {
	o.CodeVerifier = codeVerifier
}

// WithGrantType adds the grantType to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithGrantType(grantType string) *PostAPIOidcTokenParams {
	o.SetGrantType(grantType)
	return o
}

// SetGrantType adds the grantType to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetGrantType(grantType string) {
	o.GrantType = grantType
}

// WithRefreshToken adds the refreshToken to the post API oidc token params
func (o *PostAPIOidcTokenParams) WithRefreshToken(refreshToken *string) *PostAPIOidcTokenParams {
	o.SetRefreshToken(refreshToken)
	return o
}

// SetRefreshToken adds the refreshToken to the post API oidc token params
func (o *PostAPIOidcTokenParams) SetRefreshToken(refreshToken *string) {
	o.RefreshToken = refreshToken
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIOidcTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ClientAssertion != nil {

		// form param client_assertion
		var frClientAssertion string
		if o.ClientAssertion != nil {
			frClientAssertion = *o.ClientAssertion
		}
		fClientAssertion := frClientAssertion
		if fClientAssertion != "" {
			if err := r.SetFormParam("client_assertion", fClientAssertion); err != nil {
				return err
			}
		}
	}

	if o.ClientAssertionType != nil {

		// form param client_assertion_type
		var frClientAssertionType string
		if o.ClientAssertionType != nil {
			frClientAssertionType = *o.ClientAssertionType
		}
		fClientAssertionType := frClientAssertionType
		if fClientAssertionType != "" {
			if err := r.SetFormParam("client_assertion_type", fClientAssertionType); err != nil {
				return err
			}
		}
	}

	if o.ClientID != nil {

		// form param client_id
		var frClientID string
		if o.ClientID != nil {
			frClientID = *o.ClientID
		}
		fClientID := frClientID
		if fClientID != "" {
			if err := r.SetFormParam("client_id", fClientID); err != nil {
				return err
			}
		}
	}

	if o.ClientSecret != nil {

		// form param client_secret
		var frClientSecret string
		if o.ClientSecret != nil {
			frClientSecret = *o.ClientSecret
		}
		fClientSecret := frClientSecret
		if fClientSecret != "" {
			if err := r.SetFormParam("client_secret", fClientSecret); err != nil {
				return err
			}
		}
	}

	if o.Code != nil {

		// form param code
		var frCode string
		if o.Code != nil {
			frCode = *o.Code
		}
		fCode := frCode
		if fCode != "" {
			if err := r.SetFormParam("code", fCode); err != nil {
				return err
			}
		}
	}

	if o.CodeVerifier != nil {

		// form param code_verifier
		var frCodeVerifier string
		if o.CodeVerifier != nil {
			frCodeVerifier = *o.CodeVerifier
		}
		fCodeVerifier := frCodeVerifier
		if fCodeVerifier != "" {
			if err := r.SetFormParam("code_verifier", fCodeVerifier); err != nil {
				return err
			}
		}
	}

	// form param grant_type
	frGrantType := o.GrantType
	fGrantType := frGrantType
	if fGrantType != "" {
		if err := r.SetFormParam("grant_type", fGrantType); err != nil {
			return err
		}
	}

	if o.RefreshToken != nil {

		// form param refresh_token
		var frRefreshToken string
		if o.RefreshToken != nil {
			frRefreshToken = *o.RefreshToken
		}
		fRefreshToken := frRefreshToken
		if fRefreshToken != "" {
			if err := r.SetFormParam("refresh_token", fRefreshToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
