// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

import (
	"context"
	"net/http"
	"time"

	"github.com/aclerici38/pocket-id-go-client/v2/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIOidcAuthorizeParams creates a new PostAPIOidcAuthorizeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIOidcAuthorizeParams() *PostAPIOidcAuthorizeParams {
	return NewPostAPIOidcAuthorizeParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAPIOidcAuthorizeParamsWithTimeout creates a new PostAPIOidcAuthorizeParams object
// with the ability to set a timeout on a request.
func NewPostAPIOidcAuthorizeParamsWithTimeout(timeout time.Duration) *PostAPIOidcAuthorizeParams {
	return &PostAPIOidcAuthorizeParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAPIOidcAuthorizeParamsWithContext creates a new PostAPIOidcAuthorizeParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIOidcAuthorizeParams].
func NewPostAPIOidcAuthorizeParamsWithContext(ctx context.Context) *PostAPIOidcAuthorizeParams {
	return &PostAPIOidcAuthorizeParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAPIOidcAuthorizeParamsWithHTTPClient creates a new PostAPIOidcAuthorizeParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIOidcAuthorizeParamsWithHTTPClient(client *http.Client) *PostAPIOidcAuthorizeParams {
	return &PostAPIOidcAuthorizeParams{
		HTTPClient: client,
	}
}

/*
PostAPIOidcAuthorizeParams contains all the parameters to send to the API endpoint

	for the post API oidc authorize operation.

	Typically these are written to a http.Request.
*/
type PostAPIOidcAuthorizeParams struct {

	/* Request.

	   Authorization request parameters
	*/
	Request *models.GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post API oidc authorize params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOidcAuthorizeParams) WithDefaults() *PostAPIOidcAuthorizeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API oidc authorize params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOidcAuthorizeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API oidc authorize params.
func (o *PostAPIOidcAuthorizeParams) WithTimeout(timeout time.Duration) *PostAPIOidcAuthorizeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API oidc authorize params.
func (o *PostAPIOidcAuthorizeParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post API oidc authorize params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIOidcAuthorizeParams].
func (o *PostAPIOidcAuthorizeParams) WithContext(ctx context.Context) *PostAPIOidcAuthorizeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API oidc authorize params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIOidcAuthorizeParams].
func (o *PostAPIOidcAuthorizeParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post API oidc authorize params.
func (o *PostAPIOidcAuthorizeParams) WithHTTPClient(client *http.Client) *PostAPIOidcAuthorizeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API oidc authorize params.
func (o *PostAPIOidcAuthorizeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post API oidc authorize params.
func (o *PostAPIOidcAuthorizeParams) WithRequest(request *models.GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto) *PostAPIOidcAuthorizeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API oidc authorize params.
func (o *PostAPIOidcAuthorizeParams) SetRequest(request *models.GithubComPocketIDPocketIDBackendInternalDtoAuthorizeOidcClientRequestDto) {
	o.Request = request
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAPIOidcAuthorizeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
