// Code generated by go-swagger; DO NOT EDIT.

package o_id_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aclerici38/pocket-id-go-client/models"
)

// PostAPIOidcIntrospectReader is a Reader for the PostAPIOidcIntrospect structure.
type PostAPIOidcIntrospectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIOidcIntrospectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIOidcIntrospectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/oidc/introspect] PostAPIOidcIntrospect", response, response.Code())
	}
}

// NewPostAPIOidcIntrospectOK creates a PostAPIOidcIntrospectOK with default headers values
func NewPostAPIOidcIntrospectOK() *PostAPIOidcIntrospectOK {
	return &PostAPIOidcIntrospectOK{}
}

/*
PostAPIOidcIntrospectOK describes a response with status code 200, with default header values.

Response with the introspection result.
*/
type PostAPIOidcIntrospectOK struct {
	Payload *models.GithubComPocketIDPocketIDBackendInternalDtoOidcIntrospectionResponseDto
}

// IsSuccess returns true when this post Api oidc introspect o k response has a 2xx status code
func (o *PostAPIOidcIntrospectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api oidc introspect o k response has a 3xx status code
func (o *PostAPIOidcIntrospectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api oidc introspect o k response has a 4xx status code
func (o *PostAPIOidcIntrospectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api oidc introspect o k response has a 5xx status code
func (o *PostAPIOidcIntrospectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api oidc introspect o k response a status code equal to that given
func (o *PostAPIOidcIntrospectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api oidc introspect o k response
func (o *PostAPIOidcIntrospectOK) Code() int {
	return 200
}

func (o *PostAPIOidcIntrospectOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/oidc/introspect][%d] postApiOidcIntrospectOK %s", 200, payload)
}

func (o *PostAPIOidcIntrospectOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/oidc/introspect][%d] postApiOidcIntrospectOK %s", 200, payload)
}

func (o *PostAPIOidcIntrospectOK) GetPayload() *models.GithubComPocketIDPocketIDBackendInternalDtoOidcIntrospectionResponseDto {
	return o.Payload
}

func (o *PostAPIOidcIntrospectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComPocketIDPocketIDBackendInternalDtoOidcIntrospectionResponseDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
